const { loadScriptEnv, timeNow, generateToken } = require('../../services/shared');
const dbService = require('../../services/db');
const cacheService = require('../../services/cache');
const { deleteKeys } = require('../../services/cache');

loadScriptEnv();

function main() {
    return new Promise(async (resolve, reject) => {
        try {
            console.log('Add instruments');

            let conn = await dbService.conn();

            //clear cache
            await deleteKeys(cacheService.keys.instruments);

            for (let instrument of module.exports.data) {
                let check = await conn('instruments').where('name', instrument.name).first();

                if (!check) {
                    await conn('instruments').insert({
                        token: instrument.token,
                        name: instrument.name,
                        category: instrument.category,
                        is_common: instrument.is_common,
                        popularity: instrument.popularity,
                        created: timeNow(),
                        updated: timeNow(),
                    });
                } else {
                    await conn('instruments')
                        .where('id', check.id)
                        .update({
                            token: instrument.token,
                            category: instrument.category,
                            is_common: instrument.is_common,
                            popularity: instrument.popularity,
                            updated: timeNow(),
                    });
                }
            }

            resolve();
        } catch (e) {
            console.error(e);
        }

        resolve();
    });
}

module.exports = {
    main: main,
    data: [
        {
            token: 'ins_acco',
            name: 'Accordion',
            category: 'Keyboard',
            is_common: 1,
            popularity: 650,
        },
        {
            token: 'ins_acou',
            name: 'Acoustic bass guitar',
            category: 'String',
            is_common: 0,
            popularity: 550,
        },
        {
            token: 'ins_acos',
            name: 'Acoustic guitar',
            category: 'String',
            is_common: 0,
            popularity: 770,
        },
        {
            token: 'ins_aeol',
            name: 'Aeolian Harp',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_agun',
            name: 'Agung',
            category: 'Percussion',
            is_common: 0,
            popularity: 45,
        },
        {
            token: 'ins_agug',
            name: 'Agung a Tamlang',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_ahok',
            name: 'Ahoko',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_ajae',
            name: 'Ajaeng',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_albo',
            name: 'Alboka',
            category: 'Wind',
            is_common: 0,
            popularity: 35,
        },
        {
            token: 'ins_alph',
            name: 'Alphorn',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_alpi',
            name: 'Alpine bell',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_alto',
            name: 'Alto clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 280,
        },
        {
            token: 'ins_altf',
            name: 'Alto flute',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_alth',
            name: 'Alto horn',
            category: 'Brass',
            is_common: 0,
            popularity: 220,
        },
        {
            token: 'ins_alts',
            name: 'Alto sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_alta',
            name: 'Alto saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 750,
        },
        {
            token: 'ins_angk',
            name: 'Angklung',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_appa',
            name: 'Appalachian dulcimer',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_arch',
            name: 'Archlute',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_argh',
            name: 'Arghul',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_arpa',
            name: 'Arpa nottolini',
            category: 'String',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_arpe',
            name: 'Arpeggione',
            category: 'String',
            is_common: 0,
            popularity: 45,
        },
        {
            token: 'ins_arra',
            name: 'Array Mbira',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_aru-',
            name: 'Aru-ding',
            category: 'Percussion',
            is_common: 0,
            popularity: 25,
        },
        {
            token: 'ins_aulo',
            name: 'Aulochrome',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_babe',
            name: 'Babendil',
            category: 'Percussion',
            is_common: 0,
            popularity: 25,
        },
        {
            token: 'ins_bagl',
            name: 'Baglama',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_bala',
            name: 'Balafon',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_ball',
            name: 'Balalaika',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_band',
            name: 'Bandola',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'ins_bano',
            name: 'Bandoneón',
            category: 'Wind',
            is_common: 0,
            popularity: 280,
        },
        {
            token: 'ins_banu',
            name: 'Bandurria',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_banh',
            name: 'Banhu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_banj',
            name: 'Banjo',
            category: 'String',
            is_common: 1,
            popularity: 560,
        },
        {
            token: 'ins_barb',
            name: 'Barbat',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_bari',
            name: 'Baritone horn',
            category: 'Brass',
            is_common: 1,
            popularity: 250,
        },
        {
            token: 'ins_bart',
            name: 'Baritone sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_baro',
            name: 'Baritone saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_barq',
            name: 'Baroque Wooden Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_bary',
            name: 'Baryton',
            category: 'Brass',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_bass',
            name: 'Bass Clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 460,
        },
        {
            token: 'ins_basd',
            name: 'Bass Drum',
            category: 'Percussion',
            is_common: 1,
            popularity: 900,
        },
        {
            token: 'ins_basf',
            name: 'Bass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_basg',
            name: 'Bass guitar',
            category: 'String',
            is_common: 0,
            popularity: 830,
        },
        {
            token: 'ins_baso',
            name: 'Bass oboe',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_basa',
            name: 'Bass sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_basx',
            name: 'Bass saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_base',
            name: 'Basse a Pistons',
            category: 'Brass',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_basc',
            name: 'Basse Cor',
            category: 'Brass',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_bast',
            name: 'Basset clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_bash',
            name: 'Basset horn',
            category: 'Wind',
            is_common: 0,
            popularity: 130,
        },
        {
            token: 'ins_basn',
            name: 'Bassoon',
            category: 'Wind',
            is_common: 1,
            popularity: 480,
        },
        {
            token: 'ins_bawu',
            name: 'Bawu',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_baya',
            name: 'Bayan',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_bazo',
            name: 'Bazooka',
            category: 'Brass',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_bell',
            name: 'Bell',
            category: 'Percussion',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'ins_beri',
            name: 'Berimbau',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_bian',
            name: 'Bianqing',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_biaz',
            name: 'Bianzhong',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_bifo',
            name: 'Bifora',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_bini',
            name: 'Biniou',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_biwa',
            name: 'Biwa',
            category: 'String',
            is_common: 0,
            popularity: 130,
        },
        {
            token: 'ins_bock',
            name: 'Bock',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_bode',
            name: 'Bodega',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_bodh',
            name: 'Bodhrán',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_boha',
            name: 'Boha',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_bomb',
            name: 'Bombarde',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_boma',
            name: 'Bombardino',
            category: 'Brass',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_bong',
            name: 'Bongo drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 450,
        },
        {
            token: 'ins_bord',
            name: 'Border pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_boro',
            name: 'Bordonua',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_bouz',
            name: 'Bouzouki',
            category: 'String',
            is_common: 0,
            popularity: 220,
        },
        {
            token: 'ins_bria',
            name: 'Brian Boru bagpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_bull',
            name: 'Bullroarer',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_butt',
            name: 'Button accordian',
            category: 'Wind',
            is_common: 0,
            popularity: 280,
        },
        {
            token: 'ins_cabr',
            name: 'Cabrette',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_call',
            name: 'Calliope',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_cari',
            name: 'Carillon',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_cast',
            name: 'Castanets',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_cava',
            name: 'Cavaco',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_cavq',
            name: 'Cavaquinho',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_caxi',
            name: 'Caxixi',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_cele',
            name: 'Celesta',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_cell',
            name: 'Cello',
            category: 'String',
            is_common: 1,
            popularity: 780,
        },
        {
            token: 'ins_ceng',
            name: 'Ceng',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_chab',
            name: 'Chabrette',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_chap',
            name: 'Chapman stick',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_char',
            name: 'Charango',
            category: 'String',
            is_common: 0,
            popularity: 160,
        },
        {
            token: 'ins_chen',
            name: 'Chenda',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_chi',
            name: 'Chi',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_chim',
            name: 'Chimes',
            category: 'Percussion',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'ins_chin',
            name: 'Ching',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_chit',
            name: 'Chitarra battente',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_chia',
            name: 'Chitarrone',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_chro',
            name: 'Chromatic accordian',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_ciga',
            name: 'Cigar box guitar',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_cimb',
            name: 'Cimbalom',
            category: 'String',
            is_common: 0,
            popularity: 140,
        },
        {
            token: 'ins_cima',
            name: 'Cimbasso',
            category: 'Brass',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_cimp',
            name: 'Cimpoi',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_citt',
            name: 'Cittern',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'ins_clap',
            name: 'Clapped hands',
            category: 'Percussion',
            is_common: 0,
            popularity: 500,
        },
        {
            token: 'ins_clar',
            name: 'Clarinet',
            category: 'Wind',
            is_common: 1,
            popularity: 800,
        },
        {
            token: 'ins_clai',
            name: "Clarinette d'amour",
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_clas',
            name: 'Classical guitar',
            category: 'String',
            is_common: 0,
            popularity: 750,
        },
        {
            token: 'ins_clav',
            name: 'Clavicembelo',
            category: 'Keyboard',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_clac',
            name: 'Clavichord',
            category: 'Keyboard',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_conc',
            name: 'Concertina',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_conh',
            name: 'Conch',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_cong',
            name: 'Conga',
            category: 'Percussion',
            is_common: 0,
            popularity: 450,
        },
        {
            token: 'ins_cont',
            name: 'Contra-alto clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_conr',
            name: 'Contra-alto flute',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_cona',
            name: 'Contrabass clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_conb',
            name: 'Contrabass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_cons',
            name: 'Contrabass oboe',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_cons',
            name: 'Contrabass Sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_conx',
            name: 'Contrabass saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_cono',
            name: 'Contrabassoon',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_corn',
            name: 'Cornet',
            category: 'Brass',
            is_common: 1,
            popularity: 350,
        },
        {
            token: 'ins_cori',
            name: 'Cornish bagpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_cowb',
            name: 'Cowbell',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_croa',
            name: 'Croatian bagpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_crom',
            name: 'Cromorne',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_crot',
            name: 'Crotales',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_crum',
            name: 'Crumhorn',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_crwt',
            name: 'Crwth',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_cuat',
            name: 'Cuatro',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_cuíc',
            name: 'Cuíca',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_cymb',
            name: 'Cymbals',
            category: 'Percussion',
            is_common: 1,
            popularity: 600,
        },
        {
            token: 'ins_cyma',
            name: 'Cymbalum',
            category: 'String',
            is_common: 0,
            popularity: 130,
        },
        {
            token: "da'u",
            name: "Da'uli da'uli",
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_daba',
            name: 'Dabakan',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_dadi',
            name: 'Dadihu',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_dahu',
            name: 'Dahu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_daik',
            name: 'Daiko',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_dank',
            name: 'Dankiyo',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_dara',
            name: 'Daraboukka',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_darb',
            name: 'Darabukka',
            category: 'Percussion',
            is_common: 0,
            popularity: 170,
        },
        {
            token: 'ins_daru',
            name: 'Darbuka',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_darv',
            name: 'Darvyra',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_deni',
            name: "Denis d'or",
            category: 'String',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_dhol',
            name: 'Dhol',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_dhoa',
            name: 'Dholak',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_didg',
            name: 'Didgeridoo',
            category: 'Wind',
            is_common: 0,
            popularity: 340,
        },
        {
            token: 'ins_dihu',
            name: 'Dihu',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_diyi',
            name: 'Diyingehu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_djem',
            name: 'Djembe',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_doed',
            name: 'Doedelzak',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_domb',
            name: 'Dombak',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_domr',
            name: 'Domra',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_dota',
            name: 'Dotara',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_doub',
            name: 'Double Bass',
            category: 'String',
            is_common: 1,
            popularity: 720,
        },
        {
            token: 'ins_doul',
            name: 'Double contrabass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_douo',
            name: 'Doulophone',
            category: 'Brass',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_drum',
            name: 'Drum machine',
            category: 'Electronic',
            is_common: 1,
            popularity: 500,
        },
        {
            token: 'ins_dubr',
            name: 'Dubreq stylophone',
            category: 'Electronic',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_duct',
            name: 'Duct Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_dude',
            name: 'Dudelsack',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_dudy',
            name: 'Dudy',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_duff',
            name: 'Duff',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_dulc',
            name: 'Dulcian',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_duli',
            name: 'Dulcimer',
            category: 'String',
            is_common: 0,
            popularity: 210,
        },
        {
            token: 'ins_dulz',
            name: 'Dulzaina',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_dumb',
            name: 'Dumbelek',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_dun ',
            name: 'Dun dun',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_duta',
            name: 'Dutar',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'ins_duxi',
            name: 'Duxianqin',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_ekta',
            name: 'Ektara',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_elec',
            name: 'Electric guitar',
            category: 'String',
            is_common: 0,
            popularity: 880,
        },
        {
            token: 'ins_elet',
            name: 'Electric organ',
            category: 'Electronic',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'ins_eler',
            name: 'Electric piano',
            category: 'Electronic',
            is_common: 1,
            popularity: 600,
        },
        {
            token: 'ins_engl',
            name: 'English Horn',
            category: 'Wind',
            is_common: 1,
            popularity: 300,
        },
        {
            token: 'ins_erhu',
            name: 'Erhu',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_erxi',
            name: 'Erxian',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_euph',
            name: 'Euphonium',
            category: 'Brass',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'ins_fang',
            name: 'Fangxiang',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_fidd',
            name: 'Fiddle',
            category: 'String',
            is_common: 0,
            popularity: 450,
        },
        {
            token: 'ins_fing',
            name: 'Finger Cymbals',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_fine',
            name: 'Fingerboard synthesizer',
            category: 'Electronic',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_fisc',
            name: 'Fiscarmonica',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_flag',
            name: 'Flageolets',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_flug',
            name: 'Flugelhorn',
            category: 'Brass',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_flut',
            name: 'Flute',
            category: 'Wind',
            is_common: 1,
            popularity: 820,
        },
        {
            token: 'ins_folg',
            name: 'Folgerphone',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_fren',
            name: 'French Horn',
            category: 'Brass',
            is_common: 1,
            popularity: 670,
        },
        {
            token: 'ins_gaid',
            name: 'Gaida',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_gait',
            name: 'Gaita',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_gajd',
            name: 'Gajdy',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_gamb',
            name: 'Gambang',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_gan ',
            name: 'Gan gan',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_gand',
            name: 'Gandingan',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_gani',
            name: 'Gandingan a kayo',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_ganz',
            name: 'Ganza',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_gaoh',
            name: 'Gaohu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_gaya',
            name: 'Gayageum',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_gehu',
            name: 'Gehu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_gend',
            name: 'Gender',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_geom',
            name: 'Geomungo',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_ghat',
            name: 'Ghatam',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_glas',
            name: 'Glass marimba',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_glac',
            name: 'Glasschord',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_gloc',
            name: 'Glockenspiel',
            category: 'Percussion',
            is_common: 1,
            popularity: 350,
        },
        {
            token: 'ins_gong',
            name: 'Gong',
            category: 'Percussion',
            is_common: 1,
            popularity: 450,
        },
        {
            token: 'ins_gott',
            name: 'Gottuvadhyam',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_grea',
            name: 'Great Highland bagpipe',
            category: 'Wind',
            is_common: 0,
            popularity: 360,
        },
        {
            token: 'ins_gret',
            name: 'Great Irish warpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_guan',
            name: 'Guan',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_gugi',
            name: 'Gugin',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_guir',
            name: 'Guiro',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_guit',
            name: 'Guitar',
            category: 'String',
            is_common: 1,
            popularity: 990,
        },
        {
            token: 'ins_guia',
            name: 'Guitar 12 Strings',
            category: 'String',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_guió',
            name: 'Guitarrón',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_guqi',
            name: 'Guqin',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_gusl',
            name: 'Gusle',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_gusi',
            name: 'Gusli',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_guzh',
            name: 'Guzheng',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_hamm',
            name: 'Hammered dulcimer',
            category: 'String',
            is_common: 0,
            popularity: 170,
        },
        {
            token: 'ins_hand',
            name: 'Handbells',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_hang',
            name: 'Hang',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_hard',
            name: 'Hardanger fiddle',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_harm',
            name: 'Harmonica',
            category: 'Wind',
            is_common: 1,
            popularity: 550,
        },
        {
            token: 'ins_haro',
            name: 'Harmonium',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_harp',
            name: 'Harp',
            category: 'String',
            is_common: 1,
            popularity: 700,
        },
        {
            token: 'ins_harg',
            name: 'Harp guitar',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_hars',
            name: 'Harpsichord',
            category: 'Keyboard',
            is_common: 1,
            popularity: 380,
        },
        {
            token: 'ins_heck',
            name: 'Heckelphone',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_hege',
            name: 'Hegelong',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_héli',
            name: 'Hélicon',
            category: 'Brass',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_hich',
            name: 'Hichiriki',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_hocc',
            name: 'Hocchiku',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_hook',
            name: 'Hooked harp',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_hora',
            name: 'Horagai',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_horn',
            name: 'Horn',
            category: 'Brass',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'ins_hosh',
            name: 'Hosho',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_hsai',
            name: 'Hsaio',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_huem',
            name: 'Huemmelchen',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_hulu',
            name: 'Huluhu',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_hun',
            name: 'Hun',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_hunt',
            name: 'Hunting Horn',
            category: 'Brass',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_huqi',
            name: 'Huqin',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_hurd',
            name: 'Hurdy Gurdy',
            category: 'String',
            is_common: 0,
            popularity: 240,
        },
        {
            token: 'ins_igil',
            name: 'Igil',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_inci',
            name: 'Inci',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_ipu',
            name: 'Ipu',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_iris',
            name: 'Irish bouzouki',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_irih',
            name: 'Irish Uilleann',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_ista',
            name: 'Istarski mih',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_jang',
            name: 'Janggu',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_japa',
            name: 'Japanese Bamboo Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: "jew'",
            name: "Jew's harp",
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_jiao',
            name: 'Jiaohu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_jing',
            name: 'Jinghu',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_jug',
            name: 'Jug',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_kadl',
            name: 'Kadlong',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_kagu',
            name: 'Kagul',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_kang',
            name: 'Kangling',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_kava',
            name: 'Kaval',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_kèn ',
            name: 'Kèn bầu',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_kett',
            name: 'Kettle drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_keye',
            name: 'Keyed Bugle',
            category: 'Brass',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_keyd',
            name: 'Keyed Trumpet',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_khen',
            name: 'Khene',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_khim',
            name: 'Khim',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_khlo',
            name: 'Khloy',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_khol',
            name: 'Khol',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_kiss',
            name: 'Kissar',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_knat',
            name: 'Knatele',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_koky',
            name: 'Kokyu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_komu',
            name: 'Komungo',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_kora',
            name: 'Kora',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_koto',
            name: 'Koto',
            category: 'String',
            is_common: 0,
            popularity: 220,
        },
        {
            token: 'ins_koud',
            name: 'Koudi',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_kozi',
            name: 'Koziol',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_kubi',
            name: 'Kubing',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_kuli',
            name: 'Kulintang',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_kuln',
            name: 'Kulintang a kayo',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_kuti',
            name: 'Kutiyapi',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_kwa-',
            name: 'Kwa-yen',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_kwin',
            name: 'Kwintangen kayo',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_lamb',
            name: 'Lambeg',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_lanc',
            name: 'Lancashire great-pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_lang',
            name: 'Langeleik',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_laru',
            name: 'Laruan',
            category: 'String',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ins_lass',
            name: "Lasso d'amore",
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_laun',
            name: 'Launeddas',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_leie',
            name: 'Leier',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_leiq',
            name: 'Leiqin',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_liro',
            name: 'Lirone',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_lith',
            name: 'Lithophone',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_lush',
            name: 'Lusheng',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_lute',
            name: 'Lute',
            category: 'String',
            is_common: 0,
            popularity: 280,
        },
        {
            token: 'ins_lyre',
            name: 'Lyre',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_magu',
            name: 'Maguhu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_magy',
            name: 'Magyar duda',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_mali',
            name: 'Malimba',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_mand',
            name: 'Mando-bass',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_mano',
            name: 'Mandocello',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_manl',
            name: 'Mandola',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_mani',
            name: 'Mandolin',
            category: 'String',
            is_common: 1,
            popularity: 600,
        },
        {
            token: 'ins_mang',
            name: 'Mangtong',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_mara',
            name: 'Maraca',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_mari',
            name: 'Marimba',
            category: 'Percussion',
            is_common: 1,
            popularity: 420,
        },
        {
            token: 'ins_marm',
            name: 'Marimbao',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_marn',
            name: 'Marinbaphone',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_mbir',
            name: 'Mbira',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_mell',
            name: 'Mellophone',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_melo',
            name: 'Mellotron',
            category: 'Electronic',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_meld',
            name: 'Melodeon',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_meli',
            name: 'Melodica',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_meta',
            name: 'Metallophones',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_mijw',
            name: 'Mijwiz',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_mitt',
            name: 'Mittlealtersackpfeife',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_mizw',
            name: 'Mizwad',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_moha',
            name: 'Mohan veena',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_mood',
            name: 'Moodswinger',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_mori',
            name: 'Morin khuur',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_mrid',
            name: 'Mridangam',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_much',
            name: 'Muchosac',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_muse',
            name: 'Musette bressane',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_must',
            name: 'Musette de cour',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_musd',
            name: 'Musette du centre',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_musi',
            name: 'Musical bow',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_musc',
            name: 'Musical Saw',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_nada',
            name: 'Nadaswaram',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_naqa',
            name: 'Naqara',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_natu',
            name: 'Natural Trumpet',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_nay',
            name: 'Nay',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_ney',
            name: 'Ney',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_nort',
            name: 'Northumbrian smallpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_nose',
            name: 'Nose flute',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_nyck',
            name: 'Nyckelharpa',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_oboe',
            name: 'Oboe',
            category: 'Wind',
            is_common: 1,
            popularity: 680,
        },
        {
            token: 'ins_obod',
            name: "Oboe d'amore",
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_oboa',
            name: 'Oboe da caccia',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_ocar',
            name: 'Ocarina',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_octa',
            name: 'Octaban',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_octp',
            name: 'Octapad',
            category: 'Electronic',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_octv',
            name: 'Octave mandolin',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_octi',
            name: 'Octavin',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_octo',
            name: 'Octocontra-alto clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_octc',
            name: 'Octocontrabass clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_olip',
            name: 'Oliphant',
            category: 'Brass',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_onde',
            name: 'Ondes martenot',
            category: 'Electronic',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_ophi',
            name: 'Ophicleide',
            category: 'Brass',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_orga',
            name: 'Organ',
            category: 'Keyboard',
            is_common: 1,
            popularity: 750,
        },
        {
            token: 'ins_orgn',
            name: 'Organ pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_over',
            name: 'Overtone guitar',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_paix',
            name: 'Paixiao',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_pale',
            name: 'Palendang',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_pan ',
            name: 'Pan pipes',
            category: 'Wind',
            is_common: 0,
            popularity: 260,
        },
        {
            token: 'ins_past',
            name: 'Pastoral pipes',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_pian',
            name: 'Piano',
            category: 'Keyboard',
            is_common: 1,
            popularity: 1000,
        },
        {
            token: 'ins_picc',
            name: 'Piccolo',
            category: 'Wind',
            is_common: 1,
            popularity: 500,
        },
        {
            token: 'ins_pico',
            name: 'Piccolo clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_picl',
            name: 'Piccolo heckelphone',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_picb',
            name: 'Piccolo oboe',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_pipa',
            name: 'Pipa',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_pipe',
            name: 'Pipe organ',
            category: 'Wind',
            is_common: 0,
            popularity: 520,
        },
        {
            token: 'ins_piva',
            name: 'Piva',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_psal',
            name: 'Psaltery',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_pula',
            name: 'Pulalu',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_qanu',
            name: 'Qanun',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_quen',
            name: 'Quena',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_quin',
            name: 'Quinticlave',
            category: 'Brass',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_rack',
            name: 'Racket',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_rain',
            name: 'Rainstick',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_rait',
            name: 'Raita',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_raja',
            name: 'Rajao',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_rana',
            name: 'Ranat ek elk',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_rant',
            name: 'Ranat thum lek',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_ratc',
            name: 'Ratchet',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_ratt',
            name: 'Rattle',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_reba',
            name: 'Rebab',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_rebe',
            name: 'Rebec',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_reco',
            name: 'Recorder',
            category: 'Wind',
            is_common: 1,
            popularity: 450,
        },
        {
            token: 'ins_reed',
            name: 'Reed contrabass',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_reep',
            name: 'Reed Pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_riq',
            name: 'Riq',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_roma',
            name: 'Roman tuba',
            category: 'Brass',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_ruan',
            name: 'Ruan',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'ins_rudr',
            name: 'Rudra veena',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_ryut',
            name: 'Ryuteki',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_saba',
            name: 'Sabar',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_sac ',
            name: 'Sac de gemecs',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_sack',
            name: 'Sackbutt',
            category: 'Brass',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_säck',
            name: 'Säckpipa',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_saen',
            name: 'Saenghwang',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_sall',
            name: 'Sallaneh',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_samp',
            name: 'Sampho',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_saml',
            name: 'Sampler',
            category: 'Electronic',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'ins_sang',
            name: 'Sang-auk',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_sant',
            name: 'Santur',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_sanx',
            name: 'Sanxian',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_sara',
            name: 'Saraswati veena',
            category: 'String',
            is_common: 0,
            popularity: 140,
        },
        {
            token: 'ins_sarr',
            name: 'Sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_saru',
            name: 'Sarunay',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_saun',
            name: 'Saung',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_saw ',
            name: 'Saw ou',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_saws',
            name: 'Saw sam sai',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_saxh',
            name: 'Saxhorn',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_saxo',
            name: 'Saxonette',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_saxp',
            name: 'Saxophone',
            category: 'Wind',
            is_common: 1,
            popularity: 850,
        },
        {
            token: 'ins_schw',
            name: 'Schweizer sackpfeife',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_scot',
            name: 'Scottish smallpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_se',
            name: 'Se',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_serp',
            name: 'Serpent',
            category: 'Brass',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_seru',
            name: 'Serunai',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_seta',
            name: 'Setar',
            category: 'String',
            is_common: 0,
            popularity: 140,
        },
        {
            token: 'ins_sham',
            name: 'Shamisen',
            category: 'String',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_shaw',
            name: 'Shawm',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_shek',
            name: 'Shekere',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_shen',
            name: 'Sheng',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_shin',
            name: 'Shinobue',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_shof',
            name: 'Shofar',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_sihu',
            name: 'Sihu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_sing',
            name: 'Singing bowl',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_sire',
            name: 'Siren',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_sita',
            name: 'Sitar',
            category: 'String',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_slei',
            name: 'Sleigh Bells',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_slid',
            name: 'Slide guitar',
            category: 'String',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_slie',
            name: 'Slide whistle',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_slit',
            name: 'Slit drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_snar',
            name: 'Snare Drum',
            category: 'Percussion',
            is_common: 1,
            popularity: 700,
        },
        {
            token: 'ins_sopr',
            name: 'Sopranino clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_sopa',
            name: 'Sopranino saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_sopn',
            name: 'Soprano clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'ins_sopo',
            name: 'Soprano mandolin',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_sops',
            name: 'Soprano saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_sopi',
            name: 'Soprillo',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_sorn',
            name: 'Sorna',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_sous',
            name: 'Sousaphone',
            category: 'Brass',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_spoo',
            name: 'Spoons',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_sral',
            name: 'Sralai',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_stee',
            name: 'Steel drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_stel',
            name: 'Steel guitar',
            category: 'String',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_subc',
            name: 'Subcontrabass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_subo',
            name: 'Subcontrabass saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_suli',
            name: 'Suling',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_suon',
            name: 'Suona',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_sync',
            name: 'Synclavier',
            category: 'Electronic',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_synt',
            name: 'Synthesizer',
            category: 'Electronic',
            is_common: 1,
            popularity: 640,
        },
        {
            token: 'ins_tabl',
            name: 'Tabla',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_tagu',
            name: 'Tagutok',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_taik',
            name: 'Taiko',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_talk',
            name: 'Talking drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_tamb',
            name: 'Tambour',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_tamo',
            name: 'Tambourine',
            category: 'Percussion',
            is_common: 1,
            popularity: 430,
        },
        {
            token: 'ins_tamu',
            name: 'Tamburitza',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_tan-',
            name: 'Tan-tan',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_taph',
            name: 'Taphon',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_tar',
            name: 'Tar',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_táro',
            name: 'Tárogató',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_tea ',
            name: 'Tea chest bass',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_teno',
            name: 'Tenor horn',
            category: 'Brass',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_tenr',
            name: 'Tenor mandola',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_tens',
            name: 'Tenor sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_tena',
            name: 'Tenor saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 500,
        },
        {
            token: 'ins_tenn',
            name: 'Tenoroon',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_tepo',
            name: 'Teponaztli',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_thav',
            name: 'Thavil',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_theo',
            name: 'Theorbo',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_ther',
            name: 'Theremin',
            category: 'Electronic',
            is_common: 0,
            popularity: 320,
        },
        {
            token: 'ins_timp',
            name: 'Timpani',
            category: 'Percussion',
            is_common: 1,
            popularity: 500,
        },
        {
            token: 'ins_timl',
            name: 'Timple',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_tin ',
            name: 'Tin whistle',
            category: 'Wind',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_tjel',
            name: 'Tjelempung',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_tom-',
            name: 'Tom-tom',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'ins_tone',
            name: 'Tonette',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_toru',
            name: 'Torupill',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_tran',
            name: 'Transverse Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_trek',
            name: 'Trekspill',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_tres',
            name: 'Tres',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'ins_tria',
            name: 'Triangle',
            category: 'Percussion',
            is_common: 1,
            popularity: 440,
        },
        {
            token: 'ins_tro ',
            name: 'Tro u',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_trom',
            name: 'Tromba marina',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_trob',
            name: 'Trombone',
            category: 'Brass',
            is_common: 1,
            popularity: 750,
        },
        {
            token: 'ins_troo',
            name: 'Tromboon',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_trop',
            name: 'Trompeta china',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_trum',
            name: 'Trumpet',
            category: 'Brass',
            is_common: 1,
            popularity: 840,
        },
        {
            token: 'ins_tsam',
            name: 'Tsampouna',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_tsur',
            name: 'Tsuri-daiko',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_tuba',
            name: 'Tuba',
            category: 'Brass',
            is_common: 1,
            popularity: 580,
        },
        {
            token: 'ins_tubu',
            name: 'Tubular Bells',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_tuhu',
            name: 'Tuhu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ins_tulu',
            name: 'Tulum',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_tump',
            name: 'Tumpong',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_turn',
            name: 'Turntables',
            category: 'Electronic',
            is_common: 1,
            popularity: 450,
        },
        {
            token: 'ins_ud',
            name: 'Ud',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ins_udu',
            name: 'Udu',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_ukul',
            name: 'Ukulele',
            category: 'String',
            is_common: 1,
            popularity: 630,
        },
        {
            token: 'ins_vali',
            name: 'Valiha',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_vert',
            name: 'Vertical flute',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_veri',
            name: 'Vertical viola',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_veuz',
            name: 'Veuze',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_vibr',
            name: 'Vibraphone',
            category: 'Percussion',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'ins_vich',
            name: 'Vichitra veena',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_viel',
            name: 'Vielle',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_vihu',
            name: 'Vihuela',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_viol',
            name: 'Viola',
            category: 'String',
            is_common: 1,
            popularity: 730,
        },
        {
            token: 'ins_vioa',
            name: "Viola d'amore",
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_viod',
            name: 'Viola da gamba',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ins_vioo',
            name: 'Viola organista',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_vioi',
            name: 'Violin',
            category: 'String',
            is_common: 1,
            popularity: 920,
        },
        {
            token: 'ins_viot',
            name: 'Violotta',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_vlad',
            name: 'Vladimirsky Rozhok',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_voic',
            name: 'Voice',
            category: 'Natural',
            is_common: 1,
            popularity: 1000,
        },
        {
            token: 'ins_voli',
            name: 'Volinka',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_wagn',
            name: 'Wagner Tuba',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_wash',
            name: 'Washboard',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_wasi',
            name: 'Washint',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_wast',
            name: 'Washtub bass',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_wels',
            name: 'Welsh pipes',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_whip',
            name: 'Whip',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_whis',
            name: 'Whistle',
            category: 'Wind',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'ins_will',
            name: 'Willow flute',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_wind',
            name: 'Wind Chimes',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'ins_xala',
            name: 'Xalam',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_xiao',
            name: 'Xiao',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ins_xiad',
            name: 'Xiaodihu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_xun',
            name: 'Xun',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_xylo',
            name: 'Xylophone',
            category: 'Percussion',
            is_common: 1,
            popularity: 530,
        },
        {
            token: 'ins_xylr',
            name: 'Xylorimba',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ins_yang',
            name: "Yang chi'in",
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_yanc',
            name: 'Yang Chin',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_yayl',
            name: 'Yayli tanbur',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_yazh',
            name: 'Yazheng',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_yehu',
            name: 'Yehu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_yu',
            name: 'Yu',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_yueh',
            name: "Yueh Ch'in",
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ins_yun ',
            name: 'Yun Lo',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_zamp',
            name: 'Zampogna',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'ins_zaqq',
            name: 'Zaqq',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_zhon',
            name: 'Zhongdihu',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_zhui',
            name: 'Zhuihu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ins_zith',
            name: 'Zither',
            category: 'String',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ins_zong',
            name: 'Zonghu',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ins_zufa',
            name: 'Zufalo',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ins_zurn',
            name: 'Zurna',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ins_sop',
            name: 'Soprano',
            category: 'Voice',
            is_common: 1,
            popularity: 900,
        },
        {
            token: 'ins_mezz',
            name: 'Mezzo-soprano',
            category: 'Voice',
            is_common: 1,
            popularity: 850,
        },
        {
            token: 'ins_alt',
            name: 'Alto',
            category: 'Voice',
            is_common: 1,
            popularity: 850,
        },
        {
            token: 'ins_coun',
            name: 'Countertenor',
            category: 'Voice',
            is_common: 1,
            popularity: 700,
        },
        {
            token: 'ins_ten',
            name: 'Tenor',
            category: 'Voice',
            is_common: 1,
            popularity: 900,
        },
        {
            token: 'ins_barn',
            name: 'Baritone',
            category: 'Voice',
            is_common: 1,
            popularity: 850,
        },
        {
            token: 'ins_bas',
            name: 'Bass',
            category: 'Voice',
            is_common: 1,
            popularity: 800,
        },
    ],
};

if (require.main === module) {
    (async function () {
        try {
            await main();
            process.exit();
        } catch (e) {
            console.error(e);
        }
    })();
}
