const { loadScriptEnv, timeNow, generateToken } = require('../../services/shared');
const dbService = require('../../services/db');

loadScriptEnv();

function main() {
    return new Promise(async (resolve, reject) => {
        try {
            console.log('Add instruments');

            let conn = await dbService.conn();

            for (let instrument of module.exports.data) {
                let check = await conn('instruments').where('name', instrument.name).first();

                if (!check) {
                    await conn('instruments').insert({
                        token: instrument.token,
                        name: instrument.name,
                        category: instrument.category,
                        is_common: instrument.is_common,
                        popularity: instrument.popularity,
                        created: timeNow(),
                        updated: timeNow(),
                    });
                }
            }

            resolve();
        } catch (e) {
            console.error(e);
        }

        resolve();
    });
}

module.exports = {
    main: main,
    data: [
        {
            token: 'oz1cmtk73vljcaorqt5b',
            name: 'Accordion',
            category: 'Keyboard',
            is_common: 1,
            popularity: 650,
        },
        {
            token: 'fuvrd7xe0yjljk14vk0q',
            name: 'Acoustic bass guitar',
            category: 'String',
            is_common: 0,
            popularity: 550,
        },
        {
            token: '35ssy15j4be1ckbvhvqp',
            name: 'Acoustic guitar',
            category: 'String',
            is_common: 0,
            popularity: 770,
        },
        {
            token: 'i15qbj5c36zwx1zcr2t6',
            name: 'Aeolian Harp',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'xe9d93g1ecmhnqzlqqn8',
            name: 'Agung',
            category: 'Percussion',
            is_common: 0,
            popularity: 45,
        },
        {
            token: 'rxzuh88ohtz8tsohwsvo',
            name: 'Agung a Tamlang',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'w3ghb4f3j9vhhyduyvio',
            name: 'Ahoko',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'kxn498bbb1seq27p2c7r',
            name: 'Ajaeng',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '18sdclcpzj4mqlvv7x7r',
            name: 'Alboka',
            category: 'Wind',
            is_common: 0,
            popularity: 35,
        },
        {
            token: '58puc9bxtmhqeorj6pij',
            name: 'Alphorn',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'b3grtz40jkilc2f8qgmn',
            name: 'Alpine bell',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'hv1o8f6zm9n4yy5bw8fu',
            name: 'Alto clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 280,
        },
        {
            token: '7c8kewp6ohucwc14n6uh',
            name: 'Alto flute',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'pxfsjv8f1x64uc6f1gol',
            name: 'Alto horn',
            category: 'Brass',
            is_common: 0,
            popularity: 220,
        },
        {
            token: 'y4g833ocgqq14xit1lfu',
            name: 'Alto sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'kawtlep26ko5lsjukam7',
            name: 'Alto saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 750,
        },
        {
            token: 'gwdnyjgz5u278cwyqi3c',
            name: 'Angklung',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'zwphgbqf0uamdshdu8yk',
            name: 'Appalachian dulcimer',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'i63ucn2e93n4qd8yy07h',
            name: 'Archlute',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'b81j6s3nwj937zwf50ju',
            name: 'Arghul',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'a6i6qkt8lr7n4ac6rsht',
            name: 'Arpa nottolini',
            category: 'String',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'wkhfgp5idznwi066s8qm',
            name: 'Arpeggione',
            category: 'String',
            is_common: 0,
            popularity: 45,
        },
        {
            token: '3bfbyxczvosq3mawbgvo',
            name: 'Array Mbira',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ue4tsyfikm8poso2yo2u',
            name: 'Aru-ding',
            category: 'Percussion',
            is_common: 0,
            popularity: 25,
        },
        {
            token: 'q6db4xktlsnrh4f0rfnr',
            name: 'Aulochrome',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'hq7ml9rwfhdk73nhvwre',
            name: 'Babendil',
            category: 'Percussion',
            is_common: 0,
            popularity: 25,
        },
        {
            token: 'wghg4jz9mc8pb4vtn5mg',
            name: 'Baglama',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'g5c67oqx8p150hk1wf3g',
            name: 'Balafon',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'tmzhr1sxgqjci5421t16',
            name: 'Balalaika',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ghgr7r1wzr2i5lhqdp8y',
            name: 'Bandola',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: '71zqj38v5llpbgbxc1b8',
            name: 'Bandoneón',
            category: 'Wind',
            is_common: 0,
            popularity: 280,
        },
        {
            token: 'ku32e3s3m8uu30qsasjg',
            name: 'Bandurria',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '5sm0s8l779a8u85xuz99',
            name: 'Banhu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 't370bz7l353ipkosaexf',
            name: 'Banjo',
            category: 'String',
            is_common: 1,
            popularity: 560,
        },
        {
            token: 'rjqzabng7i6f3b7tn3me',
            name: 'Barbat',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 's2k2crginz5shd83wtug',
            name: 'Baritone horn',
            category: 'Brass',
            is_common: 1,
            popularity: 250,
        },
        {
            token: 'ztxpqq4cj66jvuqqw8xf',
            name: 'Baritone sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'pszfzab8rpgfej2je0k1',
            name: 'Baritone saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'fpgvd2q6yyi9bqbl35b6',
            name: 'Baroque Wooden Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '77vjjn1gdy36eqjvdkf3',
            name: 'Baryton',
            category: 'Brass',
            is_common: 0,
            popularity: 90,
        },
        {
            token: '5t5nicu74sl1h6j5zw1x',
            name: 'Bass Clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 460,
        },
        {
            token: 'dadgirty9sh65orewh5n',
            name: 'Bass Drum',
            category: 'Percussion',
            is_common: 1,
            popularity: 900,
        },
        {
            token: 'd7gm26so3u1eiowc5xnj',
            name: 'Bass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: '7pvir6be45dzy0ltorgb',
            name: 'Bass guitar',
            category: 'String',
            is_common: 0,
            popularity: 830,
        },
        {
            token: 'i7zxu8socgw721kds8yd',
            name: 'Bass oboe',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'rw7th50mu0z37cq9z1wk',
            name: 'Bass sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: '9v5eweum4xxr38lvu9d6',
            name: 'Bass saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '5npmd3d8bcrpjwwf3nhg',
            name: 'Basse a Pistons',
            category: 'Brass',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'qrw58hjh32nrs7z5fm8s',
            name: 'Basse Cor',
            category: 'Brass',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'stpmpzc2ug03gkhexwmq',
            name: 'Basset clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'xdtivm845tw5vklk84uq',
            name: 'Basset horn',
            category: 'Wind',
            is_common: 0,
            popularity: 130,
        },
        {
            token: 'op8jf435oihqqk01r3sk',
            name: 'Bassoon',
            category: 'Wind',
            is_common: 1,
            popularity: 480,
        },
        {
            token: 'ohsgrtv5yoltsu8q5zt2',
            name: 'Bawu',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'vtfx64y3ogcd5i55uqgi',
            name: 'Bayan',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'eku36b4nuqe8rp84qgmd',
            name: 'Bazooka',
            category: 'Brass',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '2c3ecac21jcky1yujgh2',
            name: 'Bell',
            category: 'Percussion',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'dxg2ji2j9ulshqodxa29',
            name: 'Berimbau',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'eycv97il9z4si5vfsjc7',
            name: 'Bianqing',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'qh2zdj4rryol8j86s0sg',
            name: 'Bianzhong',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'kbwiqol6t3718dgswt01',
            name: 'Bifora',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'fzrznko66p3po92jze15',
            name: 'Biniou',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'xntpgv2j5mztk5prb62o',
            name: 'Biwa',
            category: 'String',
            is_common: 0,
            popularity: 130,
        },
        {
            token: '1g2saw2rc0c22jnmsi9u',
            name: 'Bock',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ook5aa4car4725mlthk5',
            name: 'Bodega',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'uk5i2w96b2yd5aj7yiad',
            name: 'Bodhrán',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'o8tl5hknldsydeyb8sht',
            name: 'Boha',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'atjcde39m4claned7n52',
            name: 'Bombarde',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ndbknn4gfllxg3oxjunh',
            name: 'Bombardino',
            category: 'Brass',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 's6wbu9mb83z6oxxzgmny',
            name: 'Bongo drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 450,
        },
        {
            token: '9jxu0uq04m4j7hjn0gij',
            name: 'Border pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '1hpcxmglb1kyyjh78tid',
            name: 'Bordonua',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '7jgn8bl4fmjme67p7l17',
            name: 'Bouzouki',
            category: 'String',
            is_common: 0,
            popularity: 220,
        },
        {
            token: 'spr3fw8nqzwk5ybtcvta',
            name: 'Brian Boru bagpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ilncjoo2jcv9hzhkryp0',
            name: 'Bullroarer',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'bmoc48fk7hlyjflvr7xd',
            name: 'Button accordian',
            category: 'Wind',
            is_common: 0,
            popularity: 280,
        },
        {
            token: 'yigxb9x5cktd6yljtkq3',
            name: 'Cabrette',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '7mxkeqkumf5mxslt2haf',
            name: 'Calliope',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'lw99wqe9ff1rgirjdnc7',
            name: 'Carillon',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ohnzn8qswkqixi4uznx0',
            name: 'Castanets',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'sxflbtjg3rilhmpvx5v2',
            name: 'Cavaco',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'qrbo1xykayahwdfk0q6c',
            name: 'Cavaquinho',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '6vst7slchgygghuzco93',
            name: 'Caxixi',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '6mcsaodqsreitd0oi7cs',
            name: 'Celesta',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'r3jnwncnqto2pjm9yrfl',
            name: 'Cello',
            category: 'String',
            is_common: 1,
            popularity: 780,
        },
        {
            token: '543p7alexvsxs2ztorqy',
            name: 'Ceng',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '5cddd92v6li3z6ojg6j0',
            name: 'Chabrette',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'ivfqt7mxvq2zlq49oynz',
            name: 'Chapman stick',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'd6pkiwsffjgashe14fl3',
            name: 'Charango',
            category: 'String',
            is_common: 0,
            popularity: 160,
        },
        {
            token: 'i015zhys8pshp1ymjx5s',
            name: 'Chenda',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '385ccfentuzsx6f7n3ei',
            name: 'Chi',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'ihnj8ozkl9ex44rqn17d',
            name: 'Chimes',
            category: 'Percussion',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'h23h8h67tts7yofwdr1e',
            name: 'Ching',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'x1bgsh2hy38j5dfptwqk',
            name: 'Chitarra battente',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'rqp1257fh985w0xubmcp',
            name: 'Chitarrone',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'z85jnqzeb1oq647llx3l',
            name: 'Chromatic accordian',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ri2jmnjazic6zlcd7xyu',
            name: 'Cigar box guitar',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'qey9j2kw2crh83oy1wem',
            name: 'Cimbalom',
            category: 'String',
            is_common: 0,
            popularity: 140,
        },
        {
            token: 'hdc7jdqbgr302h32qye1',
            name: 'Cimbasso',
            category: 'Brass',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'qxnm9w96jim6i1u1np6o',
            name: 'Cimpoi',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '55m5c2c780x4b1nwsipf',
            name: 'Cittern',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'w2c89fv80hmk7o9r4ruq',
            name: 'Clapped hands',
            category: 'Percussion',
            is_common: 0,
            popularity: 500,
        },
        {
            token: '51h878jioxct6mhi9q8m',
            name: 'Clarinet',
            category: 'Wind',
            is_common: 1,
            popularity: 800,
        },
        {
            token: '36f84pfzrwekhw0qasz2',
            name: "Clarinette d'amour",
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ctvdbtdpdf8rqgurykrj',
            name: 'Classical guitar',
            category: 'String',
            is_common: 0,
            popularity: 750,
        },
        {
            token: 'fqybz9s18wx3tjgv9iwq',
            name: 'Clavicembelo',
            category: 'Keyboard',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'qxfohe8h731x3gt2ww6t',
            name: 'Clavichord',
            category: 'Keyboard',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '2ibzpygyyazb8hxelclw',
            name: 'Concertina',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'fbusbyowwh1gtkxoyq4p',
            name: 'Conch',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'lbczgxuclv9wa32hs53o',
            name: 'Conga',
            category: 'Percussion',
            is_common: 0,
            popularity: 450,
        },
        {
            token: 'syeozguc4io6ic37fq9l',
            name: 'Contra-alto clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'bvljb7nzwgv248mvoefn',
            name: 'Contra-alto flute',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: '5tckxrdvsqrtcfucvy13',
            name: 'Contrabass clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '2ie4agesg48f3dgbech9',
            name: 'Contrabass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'dntdx02877gdzb1w16vn',
            name: 'Contrabass oboe',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'efefezbpk65z3hpitb1b',
            name: 'Contrabass Sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'o46r61hjy1qm12vxex9x',
            name: 'Contrabass saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '4ewx6qoh81dtseyu2hrg',
            name: 'Contrabassoon',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'y1dko52ert2vq6mwl1p1',
            name: 'Cornet',
            category: 'Brass',
            is_common: 1,
            popularity: 350,
        },
        {
            token: 'qf7gi7tymor9q5iiqm84',
            name: 'Cornish bagpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '65sevrvsu9e9g6c3xsho',
            name: 'Cowbell',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'pqx2jhthht55cmed2k1g',
            name: 'Croatian bagpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'q19bqivzcjdpzzjd3zmj',
            name: 'Cromorne',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '2kxhve8je3nrjjtrczhm',
            name: 'Crotales',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'xt9n710lqk9anefjhkqu',
            name: 'Crumhorn',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'i1meuejhvqk4c8b6o3ze',
            name: 'Crwth',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'kkne5nede91pkq16qs3l',
            name: 'Cuatro',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '86xdb1utwgsob5bkrphr',
            name: 'Cuíca',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'h2urt5ehfskggc2acbqj',
            name: 'Cymbals',
            category: 'Percussion',
            is_common: 1,
            popularity: 600,
        },
        {
            token: 'x36s11uhrhxfidiwin8j',
            name: 'Cymbalum',
            category: 'String',
            is_common: 0,
            popularity: 130,
        },
        {
            token: 'kaun22ca1trptyih72u8',
            name: "Da'uli da'uli",
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'tjbvj32ryvh34zbkw5tg',
            name: 'Dabakan',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '41edh96xtz7j8chwc6va',
            name: 'Dadihu',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'gz9vr0x1f02ni3bhwxcz',
            name: 'Dahu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'k0ybonxgj5ke1cn74vtt',
            name: 'Daiko',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'y6vmk4glnmbu3zrlatol',
            name: 'Dankiyo',
            category: 'Wind',
            is_common: 0,
            popularity: 30,
        },
        {
            token: '6ggg2d8076yjnm8u127z',
            name: 'Daraboukka',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '36x0bqwe9m12nb95kgh6',
            name: 'Darabukka',
            category: 'Percussion',
            is_common: 0,
            popularity: 170,
        },
        {
            token: '6m3q3u38xhpr9qb1c6ot',
            name: 'Darbuka',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: '4rer25ltm34mdf3xbh9d',
            name: 'Darvyra',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'er0xwozskszazsx7twqq',
            name: "Denis d'or",
            category: 'String',
            is_common: 0,
            popularity: 30,
        },
        {
            token: '96g3bbxs22asu90ovqzz',
            name: 'Dhol',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: '7y2ksratjqa9gdb2zan6',
            name: 'Dholak',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'niqj2bwdi6qstppvmvh3',
            name: 'Didgeridoo',
            category: 'Wind',
            is_common: 0,
            popularity: 340,
        },
        {
            token: '92udmjkx2knpmb7gr621',
            name: 'Dihu',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'dwk1ltl5vg4dp4hhsu4y',
            name: 'Diyingehu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'eoleqfy7l8r7kjqwrgyp',
            name: 'Djembe',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: '8b1mk56uequkfvexd01u',
            name: 'Doedelzak',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'bc4dqyeqdnfh4a644xvp',
            name: 'Dombak',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'iwn6y7sl3yy6sw4kt6e2',
            name: 'Domra',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'u25muwou7atfx3585dlg',
            name: 'Dotara',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'q2bsnu06u66uzgev13x9',
            name: 'Double Bass',
            category: 'String',
            is_common: 1,
            popularity: 720,
        },
        {
            token: 'ms2rjjkptywry5p7uo3q',
            name: 'Double contrabass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'h5ikwm3hnhv3a0sa6ezb',
            name: 'Doulophone',
            category: 'Brass',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'frqprdi3n9nkx0v40e7z',
            name: 'Drum machine',
            category: 'Electronic',
            is_common: 1,
            popularity: 500,
        },
        {
            token: 'atp4x1t4bmsh7puwyydp',
            name: 'Dubreq stylophone',
            category: 'Electronic',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'odlci3z42zhh5l6c7w5y',
            name: 'Duct Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'hqkz0kguckvbzj5gluxw',
            name: 'Dudelsack',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'wr6ix2l799ezbfxnplbi',
            name: 'Dudy',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'zps9wp96oeso7rj64a1k',
            name: 'Duff',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'p8opg9gx0cd5rvxk7clw',
            name: 'Dulcian',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'z7x3sv4wddetdqrxvj90',
            name: 'Dulcimer',
            category: 'String',
            is_common: 0,
            popularity: 210,
        },
        {
            token: '9o3ynj2aghqbc9sgy4g6',
            name: 'Dulzaina',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '11h6bj32dk6qiqvtxllu',
            name: 'Dumbelek',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'v5ciqjuh2xay8mh4wbfm',
            name: 'Dun dun',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '0o13j8nfx0edc61zds7m',
            name: 'Dutar',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'ipdr6fcdrhgubzjodp3r',
            name: 'Duxianqin',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'e49335g5gfydq1gpm8br',
            name: 'Ektara',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'yiip37gqvwtklk7xnrjn',
            name: 'Electric guitar',
            category: 'String',
            is_common: 0,
            popularity: 880,
        },
        {
            token: 'ycll5jt895dtgwjx4irk',
            name: 'Electric organ',
            category: 'Electronic',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'aio4yjxzmgcnjmgac7pq',
            name: 'Electric piano',
            category: 'Electronic',
            is_common: 1,
            popularity: 600,
        },
        {
            token: '601phsojhelwoxqx4ckl',
            name: 'English Horn',
            category: 'Wind',
            is_common: 1,
            popularity: 300,
        },
        {
            token: '44wr1xups3l8ulj9ajfh',
            name: 'Erhu',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: '41a1r3nqglse0y0mo29z',
            name: 'Erxian',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '9n7oor44390fu3h9vofw',
            name: 'Euphonium',
            category: 'Brass',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'vejdiih5m1gsezzeyhuu',
            name: 'Fangxiang',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '6mpz258zgi1y6yulk4vj',
            name: 'Fiddle',
            category: 'String',
            is_common: 0,
            popularity: 450,
        },
        {
            token: 'b38li8g5osvyyktzswtv',
            name: 'Finger Cymbals',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: '4kbwit2h7o423f9i8ipu',
            name: 'Fingerboard synthesizer',
            category: 'Electronic',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'vbz8t9yohl81j76r28g9',
            name: 'Fiscarmonica',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'nfhc1ven6z2yf83is9j2',
            name: 'Flageolets',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: '32w1uwgresg7pibe2fi3',
            name: 'Flugelhorn',
            category: 'Brass',
            is_common: 0,
            popularity: 250,
        },
        {
            token: '4d1qe2tw568llv6yezn8',
            name: 'Flute',
            category: 'Wind',
            is_common: 1,
            popularity: 820,
        },
        {
            token: '53lef1bbv1k6whx2nouq',
            name: 'Folgerphone',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'y53iud6crif9lyor8lsk',
            name: 'French Horn',
            category: 'Brass',
            is_common: 1,
            popularity: 670,
        },
        {
            token: 'gf1bjfu1j27ul5oty8bf',
            name: 'Gaida',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'jd7p5fa8fybh5pu4odni',
            name: 'Gaita',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '06rhjibrua13f603z9ph',
            name: 'Gajdy',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '6t7okiv9e89rn5lypeit',
            name: 'Gambang',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 't2mjgdply73jsbdxnyss',
            name: 'Gan gan',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'noenloqvfb6kynvri31f',
            name: 'Gandingan',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'vpusvlaoz4rhx20vwbnz',
            name: 'Gandingan a kayo',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'vk3nmkrl9pl32amtjexy',
            name: 'Ganza',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'mmyg8h0v30ngppwzsbzt',
            name: 'Gaohu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'x95mdspu6k58utougjm7',
            name: 'Gayageum',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'rcla656gqa5jn6mssotj',
            name: 'Gehu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'n94nb6mc0focfvcb74do',
            name: 'Gender',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'gdsujps3z31j8d31ic2g',
            name: 'Geomungo',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'tnxwp7iu8431oedo73in',
            name: 'Ghatam',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '2stub53nzvkm6aau13vj',
            name: 'Glass marimba',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'xoi4s1p6y98mo7lwflik',
            name: 'Glasschord',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'bvzhxmur2f5dyxbs5mx9',
            name: 'Glockenspiel',
            category: 'Percussion',
            is_common: 1,
            popularity: 350,
        },
        {
            token: 'ytyenqfln2wip1iib9co',
            name: 'Gong',
            category: 'Percussion',
            is_common: 1,
            popularity: 450,
        },
        {
            token: 'd3pcsrjpm8mkfivq9n4b',
            name: 'Gottuvadhyam',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'yw2jhbg1wgo9s1zqq6w9',
            name: 'Great Highland bagpipe',
            category: 'Wind',
            is_common: 0,
            popularity: 360,
        },
        {
            token: 'o1hvgwgy8fzohbjk5tm7',
            name: 'Great Irish warpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'fptplxsq4hgwlzy3qcso',
            name: 'Guan',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'xoel4jucukxp6cbjnbe7',
            name: 'Gugin',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'c8rrt6mapg19n5kd3qal',
            name: 'Guiro',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'mjh0za0sk6khh5oqt3vs',
            name: 'Guitar',
            category: 'String',
            is_common: 1,
            popularity: 990,
        },
        {
            token: '6plznz9h9p92lld7ev3m',
            name: 'Guitar 12 Strings',
            category: 'String',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'rolm2kc349vvo1ucy7mx',
            name: 'Guitarrón',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'jamcx2dguxxm9aaq6uqm',
            name: 'Guqin',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ls83jpph2owiysi42nh5',
            name: 'Gusle',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'yt1g6680saxqzrgg1lzn',
            name: 'Gusli',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'vwd3hwkqn31a2m7n12ml',
            name: 'Guzheng',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '2mgaw1of08zkkjvyw60b',
            name: 'Hammered dulcimer',
            category: 'String',
            is_common: 0,
            popularity: 170,
        },
        {
            token: 'xhun138rj8oknmfh9b23',
            name: 'Handbells',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'euazhcuolv6xbgxk2cw1',
            name: 'Hang',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'sp7k3577iw0tghnm4vyb',
            name: 'Hardanger fiddle',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '28tzgcnsth4typdkje4m',
            name: 'Harmonica',
            category: 'Wind',
            is_common: 1,
            popularity: 550,
        },
        {
            token: '7vgl4ccho93ez9jpd8bp',
            name: 'Harmonium',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'guq9go5sm7t9ohelcir2',
            name: 'Harp',
            category: 'String',
            is_common: 1,
            popularity: 700,
        },
        {
            token: 'v4f2lyyjqohjt1kkpew9',
            name: 'Harp guitar',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'hwqzfvz15zgslj2bv25e',
            name: 'Harpsichord',
            category: 'Keyboard',
            is_common: 1,
            popularity: 380,
        },
        {
            token: 'bz8rtus62rcgw25oyb4g',
            name: 'Heckelphone',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'v9tzveomgfflpij9xvp5',
            name: 'Hegelong',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'skvqw4ejxl4nec6r4nbn',
            name: 'Hélicon',
            category: 'Brass',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 's529lnnqt797c4jtse1y',
            name: 'Hichiriki',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'gluufsu2k1n3fkq63zgh',
            name: 'Hocchiku',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'fii3eypz214egsbyk5as',
            name: 'Hooked harp',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'p8vppnso0i77ek8lckjo',
            name: 'Horagai',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'rxckuwwkhv5eks65cj39',
            name: 'Horn',
            category: 'Brass',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'pd1bs1wku41tc3cigci7',
            name: 'Hosho',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'yznme4buozyk5d5lk1ip',
            name: 'Hsaio',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'f3dg4f8ug5vf6a28iwjf',
            name: 'Huemmelchen',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'mm0std8ragmtyosxjgfd',
            name: 'Huluhu',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'pzxjxtfxksqqetapgq7o',
            name: 'Hun',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'yw6rpwle636yh3v24ylw',
            name: 'Hunting Horn',
            category: 'Brass',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'oi71grrqvyfsmvmve2rz',
            name: 'Huqin',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '4ax3xp4k1l0bze02rsqf',
            name: 'Hurdy Gurdy',
            category: 'String',
            is_common: 0,
            popularity: 240,
        },
        {
            token: '3rvaml5qrca2p18qc1qv',
            name: 'Igil',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'wkkztxkj2957ksomp1lq',
            name: 'Inci',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '4tbjeamt0q4tum5ivly3',
            name: 'Ipu',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'muf3q9ltulnqjvew6wgj',
            name: 'Irish bouzouki',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '2ggxlhv1erzrg8fqyb6n',
            name: 'Irish Uilleann',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'j1oweky3bpybkah7fzc1',
            name: 'Istarski mih',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'bjed5d374vf3b5dsq8io',
            name: 'Janggu',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'u141lsajtx9xqqdv3p87',
            name: 'Japanese Bamboo Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'htx5we2rq58nu7ukjrtb',
            name: "Jew's harp",
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'lnbx71sxhnj85766fw9d',
            name: 'Jiaohu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '1h947kxn75g1893svlci',
            name: 'Jinghu',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'dvtdiggy62rdpzguvx6w',
            name: 'Jug',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ym7dthrzvpk9iuj2grrv',
            name: 'Kadlong',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'z04t4wiuwhppb9sgpst5',
            name: 'Kagul',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'hkzt33b32fb877czghpn',
            name: 'Kangling',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'ku5de6ly2n3mlgr9ksje',
            name: 'Kaval',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'rdfh6mna8qij7k5p5grp',
            name: 'Kèn bầu',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '9e76m6fic84j47mmc8ow',
            name: 'Kettle drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'fqolu6g0lqczm4kgwmpg',
            name: 'Keyed Bugle',
            category: 'Brass',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'k16u93bce3v36rsgzbsr',
            name: 'Keyed Trumpet',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'exnscxuk4wphbo8f62s5',
            name: 'Khene',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'yxvpy2cng4zzp0i4zgwz',
            name: 'Khim',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'mzf2cktzrd75lnf46o5f',
            name: 'Khloy',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '3i2c539hynk5j3yglu4g',
            name: 'Khol',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '1nb23iswph7ezftlc74p',
            name: 'Kissar',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'fl5fqecbk790kke6fzj6',
            name: 'Knatele',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'au8iq7s6elr7djz165mp',
            name: 'Kokyu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'nfwyug2u27hoennn8jmk',
            name: 'Komungo',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '8zgvythr75v4cc4gfi10',
            name: 'Kora',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'jkq8lwmm173gdnnrdffo',
            name: 'Koto',
            category: 'String',
            is_common: 0,
            popularity: 220,
        },
        {
            token: 'zkogmloh2d43ex06gdwi',
            name: 'Koudi',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '7f7ncir2941x5u8ks46g',
            name: 'Koziol',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'dvdh4rj04ucdivwo9dtn',
            name: 'Kubing',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: 'oq9suqhc253efu7t45o7',
            name: 'Kulintang',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'uqb6n9jgr21u3f1seb99',
            name: 'Kulintang a kayo',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '2pgcvs48nn4ccw9zfuk3',
            name: 'Kutiyapi',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'zojwglzsos93zdocxhjg',
            name: 'Kwa-yen',
            category: 'Percussion',
            is_common: 0,
            popularity: 30,
        },
        {
            token: '2b993123zm9btapijm2m',
            name: 'Kwintangen kayo',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'k47bwqdu727fg1kxwn1l',
            name: 'Lambeg',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'uq4t2f5xd2yv12lab5zp',
            name: 'Lancashire great-pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'u8gpgvemwbks65vz1tls',
            name: 'Langeleik',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '2fii8sgyts8yd8mdn5sc',
            name: 'Laruan',
            category: 'String',
            is_common: 0,
            popularity: 30,
        },
        {
            token: '9nkactghfe4cijannatv',
            name: "Lasso d'amore",
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'o5h58rtw7sroyezdx9aj',
            name: 'Launeddas',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'phui6ojrcp62vpxy7wel',
            name: 'Leier',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '8lijp9hw1x6r0g3fpyk6',
            name: 'Leiqin',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '7bqwm57b4pqc0gyiz0e9',
            name: 'Lirone',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '8x9mtq887x79b8jcvswt',
            name: 'Lithophone',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'z09qbvhwid0fhvydiuey',
            name: 'Lusheng',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '1vgyx6sdjtz8jc8lohgn',
            name: 'Lute',
            category: 'String',
            is_common: 0,
            popularity: 280,
        },
        {
            token: '9k8smacyhpxxdten812w',
            name: 'Lyre',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'c8huhn46hugnktisoqe2',
            name: 'Maguhu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '1fipbvb8o3r2c4d9a6i4',
            name: 'Magyar duda',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'vuug0srb3luiodrg8wjn',
            name: 'Malimba',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'mxw4s45l7ittbiem96sc',
            name: 'Mando-bass',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'lhfs2btigl4znom3c87o',
            name: 'Mandocello',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '6iybyvnvg8eaczc21fwc',
            name: 'Mandola',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'ibf1gkfcqyej6aplgndk',
            name: 'Mandolin',
            category: 'String',
            is_common: 1,
            popularity: 600,
        },
        {
            token: 'ps4iocrl1hno7srjyctx',
            name: 'Mangtong',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '7wfirqzuhi4qupoy9tcw',
            name: 'Maraca',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'yyjf7wfyq3qufn9r1doq',
            name: 'Marimba',
            category: 'Percussion',
            is_common: 1,
            popularity: 420,
        },
        {
            token: 'kb6kolpqq6k55fb57hf5',
            name: 'Marimbao',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '3ty9nuxkc4mg9gp471jb',
            name: 'Marinbaphone',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'clar9cch8b95q56glyzs',
            name: 'Mbira',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'g3jsb2wed7cmitv3twld',
            name: 'Mellophone',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '4e3r9spzmz8vtlhx51r1',
            name: 'Mellotron',
            category: 'Electronic',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'cinf2yqs8ljhe1271q6r',
            name: 'Melodeon',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'p098ew2j9s1zmrutsybh',
            name: 'Melodica',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'ho191543y836213wojs7',
            name: 'Metallophones',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'tz6hqo3koojnr3xzsqli',
            name: 'Mijwiz',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'r2nlqyk5qq6oiy9bpt8s',
            name: 'Mittlealtersackpfeife',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'j5ugyemivdkw8qwb43di',
            name: 'Mizwad',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '383yzc58iv7kjs133pou',
            name: 'Mohan veena',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'ppihlsgxz78okumpzfyi',
            name: 'Moodswinger',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'gagqec31942pglckcfns',
            name: 'Morin khuur',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '89btmpv08qf534c583o4',
            name: 'Mridangam',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'gcogekmbwqrlu6269a6w',
            name: 'Muchosac',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'yo567rwindnnd4nhwue5',
            name: 'Musette bressane',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ygddzb1an4htgue38rgp',
            name: 'Musette de cour',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 't6xwonvwjggouu6x4n3u',
            name: 'Musette du centre',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '7nc0qc42476dai9yeilh',
            name: 'Musical bow',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'f3qez9q8trzwbr3ibvq4',
            name: 'Musical Saw',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'd4zfdmq5j99ct751n97k',
            name: 'Nadaswaram',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ec532lzmb85hic5e4tk3',
            name: 'Naqara',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '456l8fvwsuuyriqvh4du',
            name: 'Natural Trumpet',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'ihi726rvh4ewtb59wgge',
            name: 'Nay',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'wolz4131frevxhmx3i7s',
            name: 'Ney',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'gazcpvjtlinepi7vik5i',
            name: 'Northumbrian smallpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: '5rjuqnujikzp4xj16bt8',
            name: 'Nose flute',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'gdfj4raegw8sftyfe8wo',
            name: 'Nyckelharpa',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '10rkup2xkdd2zw441jy7',
            name: 'Oboe',
            category: 'Wind',
            is_common: 1,
            popularity: 680,
        },
        {
            token: '1ai85pzst827enxc46ix',
            name: "Oboe d'amore",
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'zx7sqrrqr05p8703myey',
            name: 'Oboe da caccia',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'f8sntp9v41nnfglimxvv',
            name: 'Ocarina',
            category: 'Wind',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'wpmtq3h8v21g6qk1qu6e',
            name: 'Octaban',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'avwx6i2vp6h0jidydlr2',
            name: 'Octapad',
            category: 'Electronic',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'zykmmy8c6i5m2idwqsd8',
            name: 'Octave mandolin',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'imtazr3smbiotu5gb3gw',
            name: 'Octavin',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'k3odb9lepouk997gyf8u',
            name: 'Octocontra-alto clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'g2nziqoy4eph7stcjyw4',
            name: 'Octocontrabass clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '4otvp4izw16yeywh7hxt',
            name: 'Oliphant',
            category: 'Brass',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '67cei2nlipb23c4rlft7',
            name: 'Ondes martenot',
            category: 'Electronic',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'yxl12bc8xqep9ocy5hlw',
            name: 'Ophicleide',
            category: 'Brass',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'd84ksa3843kd82ka834',
            name: 'Organ',
            category: 'Keyboard',
            is_common: 1,
            popularity: 750,
        },
        {
            token: 'm90rcoz3jtpgj129eslh',
            name: 'Organ pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'sn23sexjb2my8owphrkc',
            name: 'Overtone guitar',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 't86816bqn59dlbieefox',
            name: 'Paixiao',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'y4hkmwg4jvw4r8i7m9yu',
            name: 'Palendang',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'wwjqmuw85pd8yb2u85oo',
            name: 'Pan pipes',
            category: 'Wind',
            is_common: 0,
            popularity: 260,
        },
        {
            token: 'n9nmtu7640egsyfr5tih',
            name: 'Pastoral pipes',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'hjdwqbuqnc58vnccocts',
            name: 'Piano',
            category: 'Keyboard',
            is_common: 1,
            popularity: 1000,
        },
        {
            token: 'mejc1se7uobx4lj1ba2l',
            name: 'Piccolo',
            category: 'Wind',
            is_common: 1,
            popularity: 500,
        },
        {
            token: 'yn6l1841ti5ndifjfmcc',
            name: 'Piccolo clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'rl4tmgj60sho7xiw268e',
            name: 'Piccolo heckelphone',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ji74ybl5qk4z39p2oo3a',
            name: 'Piccolo oboe',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '4qtvftafe77oupgy9l93',
            name: 'Pipa',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'wakpzb6pjh2zhezy69qp',
            name: 'Pipe organ',
            category: 'Wind',
            is_common: 0,
            popularity: 520,
        },
        {
            token: 'b5dvofhssol68qucuozf',
            name: 'Piva',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'evoo3gktkkozniyhuprn',
            name: 'Psaltery',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'xez5e5428py0ubt9g8bh',
            name: 'Pulalu',
            category: 'Wind',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'mktqn7x8yil44nul2mpi',
            name: 'Qanun',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'kn37v43hy7r7upcd1cql',
            name: 'Quena',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'usyx868u9bd4coo73pcd',
            name: 'Quinticlave',
            category: 'Brass',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '1v29ykrqccxcsaw9zjzy',
            name: 'Racket',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '8zcfm1pitqt3cumlbwds',
            name: 'Rainstick',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: '6k9xsmyr4c48nlwqo3yh',
            name: 'Raita',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '9vxrjnmvjsfxw2by3gic',
            name: 'Rajao',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '8gojeumz6qichtj3pw4q',
            name: 'Ranat ek elk',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'fbq7om798hq49rux2mz5',
            name: 'Ranat thum lek',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'qjq0cxmev8z57ndmo659',
            name: 'Ratchet',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'qtskso652bzhnbxl1qhx',
            name: 'Rattle',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'lyu4jx3nd5vccumr3m79',
            name: 'Rebab',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'kf7stedbj2rxz06yry9g',
            name: 'Rebec',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: '5vwxvd4sgy2yexf7snjp',
            name: 'Recorder',
            category: 'Wind',
            is_common: 1,
            popularity: 450,
        },
        {
            token: 'vwfng3y9af968hg91evx',
            name: 'Reed contrabass',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '75lh36ds4uuf8y8s5p48',
            name: 'Reed Pipe',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: '76lw7dzkcsihez5qvyz2',
            name: 'Riq',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '5fttqr7ilys0cr5qauh5',
            name: 'Roman tuba',
            category: 'Brass',
            is_common: 0,
            popularity: 90,
        },
        {
            token: '78tu8xx8i9sym7mry0o6',
            name: 'Ruan',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'unojr2fwritgrzxfmgz0',
            name: 'Rudra veena',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'w5uy73nklrad45sum1en',
            name: 'Ryuteki',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'okuumygblloeyny0l55d',
            name: 'Sabar',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'hgfz2rdo1fugqspk70qd',
            name: 'Sac de gemecs',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'trvepdw4um5v5ikm3zy5',
            name: 'Sackbutt',
            category: 'Brass',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'ulkkzhbmxjgq1hvelx70',
            name: 'Säckpipa',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'opju7a2z0hbqyjr7oztq',
            name: 'Saenghwang',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'yo2xlexbwt469emkrabw',
            name: 'Sallaneh',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '5407aajgbiids3auqgrz',
            name: 'Sampho',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'gig32vr525tlhp4ekgqx',
            name: 'Sampler',
            category: 'Electronic',
            is_common: 1,
            popularity: 400,
        },
        {
            token: 'rhof18jglbdwq6ylmk76',
            name: 'Sang-auk',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: '3nhf7n66cpssrqv49l68',
            name: 'Santur',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '3qr339fvszli5wx4yi3z',
            name: 'Sanxian',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'e8s4hkwnmgqye9ry2xzd',
            name: 'Saraswati veena',
            category: 'String',
            is_common: 0,
            popularity: 140,
        },
        {
            token: 'inhy9z85cvm9p6vnobb8',
            name: 'Sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ii6733o5t44qbvpj5abh',
            name: 'Sarunay',
            category: 'Percussion',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'lkmw60ow8gryjqrcgzrq',
            name: 'Saung',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'dfqpuuxf49sbzz06icdp',
            name: 'Saw ou',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'dvbbs43sb3t6xi1v84e1',
            name: 'Saw sam sai',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '3rva3ul6ep2gniwgnocx',
            name: 'Saxhorn',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'tvyx8mkwcit67xdbp1xb',
            name: 'Saxonette',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'o33trxfzcqyu9n6wpfxv',
            name: 'Saxophone',
            category: 'Wind',
            is_common: 1,
            popularity: 850,
        },
        {
            token: '2u4ekopiz0zdnxv3rw5i',
            name: 'Schweizer sackpfeife',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'buei77aw8rfhmvv4bujl',
            name: 'Scottish smallpipes',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'gm95pxqxvhbi9egrugmr',
            name: 'Se',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'nvkup6leui9rf18hu9rm',
            name: 'Serpent',
            category: 'Brass',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'v3wjcohix88vjll4dduz',
            name: 'Serunai',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ewfoor03ihdf61g56f1h',
            name: 'Setar',
            category: 'String',
            is_common: 0,
            popularity: 140,
        },
        {
            token: 'qn6zbmuizrly19n8rkpj',
            name: 'Shamisen',
            category: 'String',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'jddolh9qky1qxenjptrr',
            name: 'Shawm',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'bh4g0ekf49uclwolceut',
            name: 'Shekere',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'yf9frlgfz5ffr2rld20b',
            name: 'Sheng',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'z77riqqds7iacx3ttcty',
            name: 'Shinobue',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'fby4t39em6nfbty8lost',
            name: 'Shofar',
            category: 'Wind',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '1vaat5t1zql2bk2qsemy',
            name: 'Sihu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '29k9l4p1pj2ti9kvdx27',
            name: 'Singing bowl',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: '041ze5966o5tbw4gel25',
            name: 'Siren',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'ojb9o67bfwl0dnv8u57r',
            name: 'Sitar',
            category: 'String',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'xc8zvzuew6hvwp5f3cm5',
            name: 'Sleigh Bells',
            category: 'Percussion',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'kkdgxv9vzw61fzh9kzvi',
            name: 'Slide guitar',
            category: 'String',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'm2zaeeu8moh6tkols2g7',
            name: 'Slide whistle',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '8882j7p7e09m4x3fm9bu',
            name: 'Slit drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'kw3j9i7hpu8o83tdbg5h',
            name: 'Snare Drum',
            category: 'Percussion',
            is_common: 1,
            popularity: 700,
        },
        {
            token: 'pzkh7jurfl5cruxre5up',
            name: 'Sopranino clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'x6htls4prsmh0c4g6otf',
            name: 'Sopranino saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '6cbhm4v9wbvqdogyr9s1',
            name: 'Soprano clarinet',
            category: 'Wind',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'ibgcm1o9iecm6ygmrbx2',
            name: 'Soprano mandolin',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'o1e3sih1wt5n2nvbuhez',
            name: 'Soprano saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'qjnjxtoapu43ahqworzh',
            name: 'Soprillo',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'mo4fssiyg6vllzqgcrsr',
            name: 'Sorna',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'v4jsrf7tby07iglwksx1',
            name: 'Sousaphone',
            category: 'Brass',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'jzqvcl1pply2hl3asw09',
            name: 'Spoons',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'efpzrnriw566m3vsr01y',
            name: 'Sralai',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'h6rx3p5r6wy854hm8jpj',
            name: 'Steel drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: '240dc3ov6dfjueekucpy',
            name: 'Steel guitar',
            category: 'String',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'mtz996id5zyj6hj68es7',
            name: 'Subcontrabass flute',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'npd63wmctj57n5dxl9s5',
            name: 'Subcontrabass saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'i7ufdsit6r3n706ibc4v',
            name: 'Suling',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'qxxtw0h09181xbyy9cib',
            name: 'Suona',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'vb07lklplzn0c8esipm6',
            name: 'Synclavier',
            category: 'Electronic',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'sdfmcqvsqt0srkvjw6ad',
            name: 'Synthesizer',
            category: 'Electronic',
            is_common: 1,
            popularity: 640,
        },
        {
            token: '2xvx1hubteit9w77umih',
            name: 'Tabla',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: '1wxbfxarpx0stkrig2x5',
            name: 'Tagutok',
            category: 'Percussion',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 'kf7646l1u5rptohmdpr5',
            name: 'Taiko',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: '9i83x2r24p8zpb2pkgx1',
            name: 'Talking drum',
            category: 'Percussion',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ppeaqou1nst8oi5hvq4p',
            name: 'Tambour',
            category: 'Percussion',
            is_common: 0,
            popularity: 180,
        },
        {
            token: '3dq236x6o940ofg77x7o',
            name: 'Tambourine',
            category: 'Percussion',
            is_common: 1,
            popularity: 430,
        },
        {
            token: 'z4cy3lze7d9s3kk3kkn1',
            name: 'Tamburitza',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'tqbyuugj6bpzy5xmtxfy',
            name: 'Tan-tan',
            category: 'Percussion',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'rr565md76vz2eltkcfo4',
            name: 'Taphon',
            category: 'Percussion',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '5i96w8gg6r5wc45xbk9r',
            name: 'Tar',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'j8h5telz8ez66yhvkl3w',
            name: 'Tárogató',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'yg0msddtvx8l2vvqr1e1',
            name: 'Tea chest bass',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'j53fa8mr7qbevbj8aqmo',
            name: 'Tenor horn',
            category: 'Brass',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'tc2fa7mic863m87jqp1z',
            name: 'Tenor mandola',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'gsyj4nfyycikoytem63t',
            name: 'Tenor sarrusophone',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'b3r1wp4jf2on8i8hfccf',
            name: 'Tenor saxophone',
            category: 'Wind',
            is_common: 0,
            popularity: 500,
        },
        {
            token: 'tx6cc9t6okqfpsjt2sqh',
            name: 'Tenoroon',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'lx16m6evg41kipucdeny',
            name: 'Teponaztli',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '937be1aibe343zziehsg',
            name: 'Thavil',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'qhxizhl1vyscgqf2jj4k',
            name: 'Theorbo',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'tu4tmo3fa76vl2ei6yod',
            name: 'Theremin',
            category: 'Electronic',
            is_common: 0,
            popularity: 320,
        },
        {
            token: 'slyskspw229xq3nhnh8o',
            name: 'Timpani',
            category: 'Percussion',
            is_common: 1,
            popularity: 500,
        },
        {
            token: '5hqdn3wjyl5zvm98n6tj',
            name: 'Timple',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'jf2xmbok0d1mymbuafh5',
            name: 'Tin whistle',
            category: 'Wind',
            is_common: 0,
            popularity: 300,
        },
        {
            token: '9ot1xhla3qjm4kiwethz',
            name: 'Tjelempung',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'rswrmn6s1tmkzrbf2fu0',
            name: 'Tom-tom',
            category: 'Percussion',
            is_common: 0,
            popularity: 400,
        },
        {
            token: 'w11lido82e6u4d7n0bmr',
            name: 'Tonette',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'gzo5igca2y61jpjubw74',
            name: 'Torupill',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'vsfri6i1338vj68o6bov',
            name: 'Transverse Flute',
            category: 'Wind',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ncrdzdpd1phnp8338url',
            name: 'Trekspill',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'n5zmvderrmet5lnpnfsb',
            name: 'Tres',
            category: 'String',
            is_common: 0,
            popularity: 110,
        },
        {
            token: 'dv2fknsa7msz3xl7d9xs',
            name: 'Triangle',
            category: 'Percussion',
            is_common: 1,
            popularity: 440,
        },
        {
            token: 'vxuhqvq8niwutbwhvji2',
            name: 'Tro u',
            category: 'String',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'rzbjcyfgjv89971ta03k',
            name: 'Tromba marina',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'v212b3zjng5oq1b5d55x',
            name: 'Trombone',
            category: 'Brass',
            is_common: 1,
            popularity: 750,
        },
        {
            token: 'j3841x2xyxdpcno2sxd6',
            name: 'Tromboon',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '85och1jo70zjln6cwx9c',
            name: 'Trompeta china',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '7wyhryktoom02gzclb8o',
            name: 'Trumpet',
            category: 'Brass',
            is_common: 1,
            popularity: 840,
        },
        {
            token: 'g4ryahgjit2g27lgwyt5',
            name: 'Tsampouna',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'zqshk0cb6wyipul75bs5',
            name: 'Tsuri-daiko',
            category: 'Percussion',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'bvx93o6pf2ikiht42kfo',
            name: 'Tuba',
            category: 'Brass',
            is_common: 1,
            popularity: 580,
        },
        {
            token: 'spl7wm81zswgyjmj19dk',
            name: 'Tubular Bells',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'rywbuee294ggi7v6p9yg',
            name: 'Tuhu',
            category: 'String',
            is_common: 0,
            popularity: 40,
        },
        {
            token: 't4y3cpz38scz9ycy20uw',
            name: 'Tulum',
            category: 'Wind',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'yfm18hmbtwe65ki668xe',
            name: 'Tumpong',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'gaimy7ri92z6ncsixzf8',
            name: 'Turntables',
            category: 'Electronic',
            is_common: 1,
            popularity: 450,
        },
        {
            token: 'zjfb46576k8uf3hnofi1',
            name: 'Ud',
            category: 'String',
            is_common: 0,
            popularity: 180,
        },
        {
            token: 'pt8tvyvhdi9uix6yagof',
            name: 'Udu',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'yuy1eb6uq6x243u2cwkv',
            name: 'Ukulele',
            category: 'String',
            is_common: 1,
            popularity: 630,
        },
        {
            token: 's7vrx37plgwfwzvgjywe',
            name: 'Valiha',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'x6l27mikjljmrpxczjqp',
            name: 'Vertical flute',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'kzo3yhclze9y04xocu82',
            name: 'Vertical viola',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'h6vhoglf6e2gsc56wxmh',
            name: 'Veuze',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '967jukgwqrczxldwc9kx',
            name: 'Vibraphone',
            category: 'Percussion',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'uqju7hqq1b71h194mdnh',
            name: 'Vichitra veena',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: '9vlp7p9bs6b17ah1tqez',
            name: 'Vielle',
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: '9ecc7av6ff4bjp00374k',
            name: 'Vihuela',
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'zdfq0ck41nmnvz0zcuwi',
            name: 'Viola',
            category: 'String',
            is_common: 1,
            popularity: 730,
        },
        {
            token: '1ke9yu4nwk3z63r6h9hz',
            name: "Viola d'amore",
            category: 'String',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'tid7zijlf31rdtrkyene',
            name: 'Viola da gamba',
            category: 'String',
            is_common: 0,
            popularity: 200,
        },
        {
            token: 'ubw1dgfvezl1wclm9x50',
            name: 'Viola organista',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'nx4h7gpy54e21dhwh0ot',
            name: 'Violin',
            category: 'String',
            is_common: 1,
            popularity: 920,
        },
        {
            token: 't4n5cgq5we0qut2ninto',
            name: 'Violotta',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'c1vx2qhn98rnuqn84mbv',
            name: 'Vladimirsky Rozhok',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'sd948da84kjf9029d82a',
            name: 'Voice',
            category: 'Natural',
            is_common: 1,
            popularity: 1000,
        },
        {
            token: 'ykas7q5u67oehpwlygu9',
            name: 'Volinka',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '18mzbgugtxqjn57ezs39',
            name: 'Wagner Tuba',
            category: 'Brass',
            is_common: 0,
            popularity: 150,
        },
        {
            token: '9rgnqzmc75ocr7gp42ni',
            name: 'Washboard',
            category: 'Percussion',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'cjoa7z55gqwjv5t7huoo',
            name: 'Washint',
            category: 'Wind',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'yoze2ygdn9uoyab56pko',
            name: 'Washtub bass',
            category: 'String',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'tlthwhytmfxhlxudqxus',
            name: 'Welsh pipes',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'et6dclt9fmtm075hudgq',
            name: 'Whip',
            category: 'Percussion',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'a8glaxcyx4am7s7w8sda',
            name: 'Whistle',
            category: 'Wind',
            is_common: 0,
            popularity: 350,
        },
        {
            token: 'j24p389jxk7m16i3f8rk',
            name: 'Willow flute',
            category: 'Wind',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'pzk4b5ml6qjx8kdojuyu',
            name: 'Wind Chimes',
            category: 'Percussion',
            is_common: 0,
            popularity: 300,
        },
        {
            token: 'qjdb77x4oqw9mruj80fe',
            name: 'Xalam',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '7cm1ps6w9iwxsba8pl6m',
            name: 'Xiao',
            category: 'Wind',
            is_common: 0,
            popularity: 150,
        },
        {
            token: 'qk24xgz9i9oj1hjfrzgy',
            name: 'Xiaodihu',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'y6zbio8rfstii378uy93',
            name: 'Xun',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'hgz6ucxpukxstxppvz5b',
            name: 'Xylophone',
            category: 'Percussion',
            is_common: 1,
            popularity: 530,
        },
        {
            token: '7y8uo9qd3cn6p9mbxk82',
            name: 'Xylorimba',
            category: 'Percussion',
            is_common: 0,
            popularity: 120,
        },
        {
            token: 'zfykwvgmzz5e6u6jbs11',
            name: "Yang chi'in",
            category: 'String',
            is_common: 0,
            popularity: 90,
        },
        {
            token: 'r3oetiliwo6b49qie21f',
            name: 'Yang Chin',
            category: 'String',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'kweeltbt8cd3enlgz5ze',
            name: 'Yayli tanbur',
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: '691dmksp8fypy6534qki',
            name: 'Yazheng',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '84hke0u6tw11cdy3jtmr',
            name: 'Yehu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: '9c472ihuac7nmbl6or3u',
            name: 'Yu',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '6mvnhkxoz6kxp9mmysp5',
            name: "Yueh Ch'in",
            category: 'String',
            is_common: 0,
            popularity: 80,
        },
        {
            token: 'fhifptic6c6se6x5f7xe',
            name: 'Yun Lo',
            category: 'Percussion',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '6fnr1s4odqv4ldtsvgd2',
            name: 'Zampogna',
            category: 'Wind',
            is_common: 0,
            popularity: 100,
        },
        {
            token: 'v0f4mooxj7f7i2c248cs',
            name: 'Zaqq',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: 'sjbp4f25ih8uguu64213',
            name: 'Zhongdihu',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: 'ktmsu4vpeej4rhp51gw3',
            name: 'Zhuihu',
            category: 'String',
            is_common: 0,
            popularity: 60,
        },
        {
            token: 'ylkiao2qt0mvwv0txnnm',
            name: 'Zither',
            category: 'String',
            is_common: 0,
            popularity: 250,
        },
        {
            token: 'zun4fwcoxbsiw3uxjjq7',
            name: 'Zonghu',
            category: 'String',
            is_common: 0,
            popularity: 70,
        },
        {
            token: '7lqivb3sn4xceykpl605',
            name: 'Zufalo',
            category: 'Wind',
            is_common: 0,
            popularity: 50,
        },
        {
            token: '05cx2v3s1jpgbck1x6zh',
            name: 'Zurna',
            category: 'Wind',
            is_common: 0,
            popularity: 90,
        },
    ],
};

if (require.main === module) {
    (async function () {
        try {
            await main();
            process.exit();
        } catch (e) {
            console.error(e);
        }
    })();
}
