module.exports = {
    'école primaire': 1,
    'ecole primaire': 1,
    'primary school': 1,
    'école élémentaire': 1,
    'école maternelle': 1,
    ecole: 1,
    kumon: 1,
    escuela: 1,
    schülerhilfe: 1,
    школа: 1,
    grundschule: 1,
    مدرسة: 1,
    'музыкальная школа': 1,
    volksschule: 1,
    'secondary school': 1,
    'szkoła podstawowa': 1,
    'escuela primaria': 1,
    ceg: 1,
    studienkreis: 1,
    volkshochschule: 1,
    'escola municipal': 1,
    'école élémentaire publique': 1,
    epp: 1,
    'általános iskola': 1,
    مدرسه: 1,
    'govt primary school': 1,
    ishule: 1,
    école: 1,
    'nursery school': 1,
    'základná škola': 1,
    musikschule: 1,
    school: 1,
    wizard: 1,
    'high school': 1,
    mathnasium: 1,
    lycée: 1,
    medersa: 1,
    'école de musique': 1,
    'школа искусств': 1,
    'ecole coranique': 1,
    'government primary school': 1,
    'école primaire privée': 1,
    'government lower primary school': 1,
    'художественная школа': 1,
    'government high school': 1,
    'základní škola': 1,
    'начальная школа': 1,
    senai: 1,
    ccaa: 1,
    fisk: 1,
    colegio: 1,
    'cultura inglesa': 1,
    sltp: 1,
    apae: 1,
    'wall street english': 1,
    collège: 1,
    college: 1,
    'elementary school': 1,
    ils: 1,
    kindergarten: 1,
    'kids & us': 1,
    'kids&us': 1,
    'lower primary school': 1,
    madrasa: 1,
    madrasah: 1,
    primaria: 1,
    primarschule: 1,
    sd: 1,
    'shule ya msingi': 1,
    technikum: 1,
    telesecundaria: 1,
    vhs: 1,
    'école communale': 1,
    'école notre-dame': 1,
    'école publique': 1,
    'средняя школа': 1,
    цэцэрлэг: 1,
    escola: 1,
    'school of rock': 1,
    'british council': 1,
    'technical school': 1,
    'polytechnische schule': 1,
    hauptschule: 1,
    școala: 1,
    'școala gimnazială': 1,
    'church school': 1,
    'government school': 1,
    'central school': 1,
    'early stage': 1,
    'escuela secundaria': 1,
    'escuela de música': 1,
    'école coranique': 1,
    médersa: 1,
    متوسطة: 1,
    pesantren: 1,
    'حوزه علمیه': 1,
    'вечерняя школа': 1,
    'школа-интернат': 1,
    'воскресная школа': 1,
    primaire: 1,
    'studienkreis nachhilfe': 1,
    公文: 1,
    公文式: 1,
    日能研: 1,
    ecc外語学院: 1,
    個太郎塾: 1,
    森塾: 1,
    市進学院: 1,
    城南コベッツ: 1,
    inlingua: 1,
    sena: 1,
    senac: 1,
    microlins: 1,
    berufsschule: 1,
    'british school': 1,
    'cambridge school': 1,
    'community primary school': 1,
    'complexe scolaire': 1,
    cosinus: 1,
    'crazy salsa': 1,
    'école primaire publique': 1,
    'english time': 1,
    'girls high school': 1,
    'islamic primary school': 1,
    madrasha: 1,
    mittelschule: 1,
    'modern music school': 1,
    'publiczna szkoła podstawowa': 1,
    realschule: 1,
    scholars: 1,
    secundaria: 1,
    'stredná odborná škola': 1,
    'sylvan learning': 1,
    'vocational school': 1,
    yes: 1,
    ابتدائية: 1,
    ثانوية: 1,
    'كلية التمريض': 1,
    'مدرسه ابتدایی': 1,
    гимназия: 1,
    колледж: 1,
    лицей: 1,
    書道教室: 1,
    外国语学院: 1,
    acadomia: 1,
    'central elementary school': 1,
    'centro escolar': 1,
    'ecole nationale': 1,
    'english first': 1,
    'escuela rural': 1,
    'facultad de medicina': 1,
    förderschule: 1,
    'government secondary school': 1,
    'groupe scolaire': 1,
    ibb: 1,
    'language link': 1,
    landesmusikschule: 1,
    'maple bear': 1,
    'mortimer english club': 1,
    smp: 1,
    'städtische musikschule': 1,
    tpa: 1,
    uned: 1,
    unopar: 1,
    'wise up': 1,
    yazigi: 1,
    'school ground': 1,
    'école privée': 1,
    'základná škola s materskou školou': 1,
    'základní škola a mateřská škola': 1,
    məktəb: 1,
    'كلية الطب': 1,
    'كلية الزراعة': 1,
    'école maternelle et élémentaire': 1,
    'government college': 1,
    'govt. high school': 1,
    'govt. school': 1,
    'zespół szkół': 1,
    'sekolah dasar': 1,
    mts: 1,
    'government polytechnic': 1,
    'government pu college': 1,
    'faculty of engineering': 1,
    'facultad de psicología': 1,
    'international house': 1,
    'escola de música': 1,
    creche: 1,
    auditorium: 1,
    'escuela de enfermería': 1,
    'institución educativa': 1,
    escuelas: 1,
    gymnázium: 1,
    kreisvolkshochschule: 1,
    'montessori-schule': 1,
    'wall street institute': 1,
    'escuela de adultos': 1,
    'institut de formation en soins infirmiers': 1,
    'wild code school': 1,
    دبستان: 1,
    'ecole fondamentale': 1,
    'academy for mathematics & english': 1,
    'american school': 1,
    conservatoire: 1,
    'english house': 1,
    'english school': 1,
    'escuela especial': 1,
    'facultad de derecho': 1,
    'faculté de médecine': 1,
    gymnasium: 1,
    iti: 1,
    'middle school': 1,
    montessori: 1,
    'national school': 1,
    'nursery and primary school': 1,
    preuniversitario: 1,
    'sae institute': 1,
    waldschule: 1,
    إبتدائية: 1,
    'مدرسة متوسطة': 1,
    理学院: 1,
    'community school': 1,
    'community secondary school': 1,
    'education centre': 1,
    'materská škola': 1,
    'общеобразовательная школа': 1,
    сош: 1,
    دبیرستان: 1,
    медресе: 1,
    'медицинское училище': 1,
    كلية: 1,
    'szkoła policealna': 1,
    'școala primară': 1,
    'unidad educativa': 1,
    სკოლა: 1,
    'ავტო სკოლა': 1,
    'მუსიკალური სკოლა': 1,
    'christian school': 1,
    'conservatoire de musique': 1,
    'facultad de ciencias': 1,
    'facultad de ingeniería': 1,
    'facultad de odontología': 1,
    instituto: 1,
    'junior high school': 1,
    'law college': 1,
    library: 1,
    maternelle: 1,
    'royal academy': 1,
    'royal college': 1,
    'school grounds': 1,
    'universidad central': 1,
    zeneiskola: 1,
    'école maternelle publique': 1,
    'école élémentaire privée': 1,
    'التكوين المهني': 1,
    'مدرسة ثانوية': 1,
    'المدرسة الإبتدائية': 1,
    'مدرسة قرآنية': 1,
    'كلية الحقوق': 1,
    'كلية طب الأسنان': 1,
    preescolar: 1,
    'college of education': 1,
    'govt high school': 1,
    'govt school': 1,
    'government boys higher secondary school': 1,
    'government girls higher secondary school': 1,
    'central high school': 1,
    техникум: 1,
    'школа иностранных языков': 1,
    мектеп: 1,
    sapix: 1,
    河合塾: 1,
    kidsduo: 1,
    くもん: 1,
    ヤマハ英語教室: 1,
    ピアノ教室: 1,
    aeon: 1,
    profilingua: 1,
    folkuniversitetet: 1,
    長頸鹿美語: 1,
    'فنی حرفه ای': 1,
    'كلية الادارة والاقتصاد': 1,
    'كلية طب الاسنان': 1,
    'school land': 1,
    academia: 1,
    'arabic school': 1,
    "centre d'alphabétisation": 1,
    'escuela de artes': 1,
    'football ground': 1,
    'government girls school': 1,
    'government upper primary school': 1,
    ground: 1,
    'grupo escolar': 1,
    ince: 1,
    'jardín de infantes': 1,
    'lycée/ceg': 1,
    madarsa: 1,
    'oxford school': 1,
    'scholars education centre': 1,
    դպրոց: 1,
    小学: 1,
    体育学院: 1,
    生命科学学院: 1,
    berufskolleg: 1,
    bfw: 1,
    'international school': 1,
    'speak english': 1,
    'école élementaire': 1,
    musiikkiopisto: 1,
    'مدرسة إبتدائية': 1,
    'department of geography': 1,
    'department of mathematics': 1,
    english: 1,
    'montessori school': 1,
    'δημοτικό σχολείο': 1,
    'كلية الهندسة المدنية': 1,
    'كلية الهندسة المعمارية': 1,
    'دانشکده کشاورزی': 1,
    'دانشکده دندانپزشکی': 1,
    'دانشکده علوم انسانی': 1,
    'دانشکده علوم پایه': 1,
    'آموزشگاه موسیقی': 1,
    学習空間: 1,
    臨海セレクト: 1,
    コペル: 1,
    馬淵教室: 1,
    京葉学院: 1,
    日建学院: 1,
    浜学園: 1,
    itto個別指導学院: 1,
    帰国子女アカデミー: 1,
    セイハ英語学院: 1,
    'bridge international academy': 1,
    'champ école paysan': 1,
    'champs école paysanes': 1,
    "jardin d'enfants": 1,
    сургууль: 1,
    kinder: 1,
    'conafe secundaria comunitaria': 1,
    'secundaria para trabajadores': 1,
    'escuela telesecundaria': 1,
    'primaria bilinga�e': 1,
    'eye level learning center': 1,
    विद्यालय: 1,
    senati: 1,
    sti: 1,
    'girls college': 1,
    'girls school': 1,
    sp: 1,
    'sun school': 1,
    niit: 1,
    madrassa: 1,
    'modern primary school': 1,
    'modern school': 1,
    sekolah: 1,
    paud: 1,
    liceo: 1,
    unefa: 1,
    еврошкола: 1,
    спортшкола: 1,
    дши: 1,
    дюсш: 1,
    'учебный центр': 1,
    'художня школа': 1,
    'школа і ст.': 1,
    'cope centre': 1,
    'british international school': 1,
    'cambridge international school': 1,
    'escuela técnica': 1,
    'english language institute': 1,
    'escuela de inglés': 1,
    'escuela normal superior': 1,
    bildungszentrum: 1,
    'centro de apoyo escolar': 1,
    'centro de estudos de línguas': 1,
    'centro de formacion profesional': 1,
    'centro educativo': 1,
    'colegio inglés': 1,
    'colegio secundario': 1,
    colégio: 1,
    'creche municipal': 1,
    'english club': 1,
    'escuela pública': 1,
    'faculty of arts': 1,
    krankenpflegeschule: 1,
    'la escuelita': 1,
    'landwirtschaftliche fachschule': 1,
    'lycée municipal': 1,
    'musiqi məktəbi': 1,
    'osnovna škola': 1,
    'pravni fakultet': 1,
    'filozofski fakultet': 1,
    'school cum cyclone centre': 1,
    sonderschule: 1,
    'universal college': 1,
    skill: 1,
    smart: 1,
    infinitive: 1,
    'academy of learning': 1,
    'academy of music': 1,
    'city school': 1,
    'école normale supérieure': 1,
    'école secondaire': 1,
    'montessori schule': 1,
    schulhaus: 1,
    crèche: 1,
    'école franco arabe': 1,
    universidad: 1,
    'école primaire et maternelle': 1,
    institut: 1,
    'official school of languages': 1,
    'my english school': 1,
    'école du centre': 1,
    block: 1,
    'école elémentaire': 1,
    'école du ski français': 1,
    segpa: 1,
    iscom: 1,
    greta: 1,
    'digital campus': 1,
    'digital college': 1,
    'international language school': 1,
    'junior school': 1,
    'school of computing': 1,
    'memorial hall': 1,
    iskola: 1,
    'مدرسه راهنمایی': 1,
    'مدرسه راهنمایی دخترانه': 1,
    'private school': 1,
    'premier cycle': 1,
    'second cycle': 1,
    'مدرسة بنات': 1,
    'secundaria tecnica': 1,
    早稲田育英ゼミナール: 1,
    '1対1ネッツ': 1,
    総合資格学院: 1,
    中萬学院: 1,
    'kids duo': 1,
    ecc: 1,
    学研: 1,
    axis: 1,
    tomas: 1,
    東進: 1,
    フリーステップ: 1,
    個別指導塾スタンダード: 1,
    四谷大塚: 1,
    step: 1,
    城北スクール: 1,
    'english zone': 1,
    삼성영어: 1,
    'бэби-клуб': 1,
    'destination языковая школа': 1,
    'не школа барабанов': 1,
    упк: 1,
    'basic school': 1,
    'escuela preparatoria': 1,
    'model secondary school': 1,
    'academic block': 1,
    'branżowa szkoła i stopnia': 1,
    'centrum nauki i biznesu': 1,
    'college of law': 1,
    'comprehensive secondary school': 1,
    kulturskolan: 1,
    'learning centre': 1,
    university: 1,
    'детская музыкальная школа': 1,
    'детская художественная школа': 1,
    'детская школа искусств': 1,
    'институт усовершенствования учителей': 1,
    'межшкольный учебный комбинат': 1,
    'спортивная школа': 1,
    คณะพยาบาลศาสตร์: 1,
    คณะวิทยาศาสตร์: 1,
    คณะเศรษฐศาสตร์: 1,
    巨匠電腦: 1,
    巨匠美語: 1,
    芝麻街美語: 1,
    地球村美日語: 1,
    'початкова школа': 1,
    'resource centre': 1,
    'cope school': 1,
    'music school': 1,
    'smart school': 1,
    'grammar school': 1,
    'college ground': 1,
    'escuela de comercio': 1,
    'senior secondary school': 1,
    'modern secondary school': 1,
    slta: 1,
    mi: 1,
    ilp: 1,
    tpq: 1,
    dproc: 1,
    'block b': 1,
    'new generation': 1,
    'old main': 1,
    berufsförderungsinstitut: 1,
    best: 1,
    'clases de inglés': 1,
    dialog: 1,
    "drummer's focus": 1,
    'duden institut für lerntherapie': 1,
    erwachsenenschule: 1,
    'escuela de musica': 1,
    'escuela normal': 1,
    'instituto de educación superior': 1,
    lernquadrat: 1,
    musikheim: 1,
    musikum: 1,
    'neue mittelschule': 1,
    realgymnasium: 1,
    'school of english': 1,
    'sonderpädagogisches zentrum': 1,
    basisschool: 1,
    cafeteria: 1,
    'degree college': 1,
    'department of botany': 1,
    'department of zoology': 1,
    'ecole primaire satellite': 1,
    'ecole prmaire': 1,
    'école de santé': 1,
    'ekonomska škola': 1,
    'ekonomski fakultet': 1,
    'english academy': 1,
    'english language house': 1,
    gemeenteschool: 1,
    'level up': 1,
    'lycée communal': 1,
    'lycée privé': 1,
    'lycée technique': 1,
    'medicinski fakultet': 1,
    'open university': 1,
    playground: 1,
    'polytechnic college': 1,
    "projet d'école": 1,
    reception: 1,
    'profesionalna gimnaziya': 1,
    'city international school': 1,
    'centro educacional': 1,
    'escola estadual': 1,
    faculdade: 1,
    ciep: 1,
    cmei: 1,
    emef: 1,
    emuef: 1,
    reitoria: 1,
    'prepara cursos': 1,
    'escola de inglês': 1,
    'colégio estadual': 1,
    'american english center': 1,
    emei: 1,
    'unidade escolar': 1,
    'skill idiomas': 1,
    'park idiomas': 1,
    uptime: 1,
    sebrae: 1,
    'grau técnico': 1,
    acbeu: 1,
    people: 1,
    influx: 1,
    cetic: 1,
    'instituto mix': 1,
    dec: 1,
    'block c': 1,
    'c block': 1,
    'a block': 1,
    'pre school': 1,
    'school library': 1,
    'girls hostel': 1,
    'ecole publique': 1,
    'école maternelle et primaire': 1,
    'école catholique': 1,
    'catholic primary school': 1,
    'presbyterian school': 1,
    幼儿园: 1,
    商学院: 1,
    法学院: 1,
    音乐学院: 1,
    校史馆: 1,
    'escuela básica': 1,
    'jardin infantil': 1,
    'centro de desarrollo infantil': 1,
    'centro educativo rural': 1,
    'escuela de oficios': 1,
    'escuela rural primaria': 1,
    'escuela de idiomas': 1,
    'school of business administration': 1,
    'school of law': 1,
    'global college': 1,
    cfp: 1,
    iut: 1,
    sekundarschule: 1,
    gewerbschule: 1,
    'scuola elementare': 1,
    lernstudio: 1,
    mehrzweckhalle: 1,
    administration: 1,
    'aula de adultos': 1,
    berufsfachschule: 1,
    berufsoberschule: 1,
    'berufsbildende schule': 1,
    codelearn: 1,
    'école municipale': 1,
    'escuela basica': 1,
    'escuela de danza': 1,
    fachoberschule: 1,
    fachschule: 1,
    'faculty of medicine': 1,
    global: 1,
    landwirtschaftsschule: 1,
    musikgarten: 1,
    musikwerkstatt: 1,
    nachhilfe: 1,
    schülerscout: 1,
    schülernachhilfe: 1,
    sprachheilschule: 1,
    sprachschule: 1,
    studienkolleg: 1,
    'the academy': 1,
    welcome: 1,
    معهد: 1,
    'école de musique et de danse': 1,
    afpa: 1,
    'école internationale': 1,
    'conservatoire à rayonnement départemental': 1,
    'école de condé': 1,
    'institut de formation en masso-kinésithérapie': 1,
    als: 1,
    cnam: 1,
    'école municipale de musique': 1,
    "école primaire d'application": 1,
    'institut des métiers du notariat': 1,
    'école maternelle du centre': 1,
    'école de musique intercommunale': 1,
    adonis: 1,
    'studio m': 1,
    'ecole élémentaire': 1,
    'european communication school': 1,
    'école de batterie': 1,
    'école montessori': 1,
    alveus: 1,
    "l'atelier musical": 1,
    'rock school': 1,
    'ecole maternelle': 1,
    'école de management': 1,
    'doctoral school': 1,
    'school in hospital': 1,
    'tuition centre': 1,
    'university library': 1,
    'college of further education': 1,
    progress: 1,
    'catholic school': 1,
    'college of medicine': 1,
    'college of nursing': 1,
    'ecole evangelique': 1,
    'glazbena škola': 1,
    it: 1,
    'instituto básico': 1,
    kindergarden: 1,
    'музыкальное училище': 1,
    'police college': 1,
    'physics department': 1,
    'school of hygiene': 1,
    'sda school': 1,
    'sda primary school': 1,
    'the school': 1,
    'učiteljski fakultet': 1,
    νηπιαγωγείο: 1,
    قوتابخانە: 1,
    'قسم ادارة الاعمال': 1,
    'كلية المعلمين': 1,
    'الكلية التربوية المفتوحة': 1,
    'technical college': 1,
    دانشگاه: 1,
    دانشکده: 1,
    هنرستان: 1,
    آموزشگاه: 1,
    'دانشکده الهیات و معارف اسلامی': 1,
    'دانشکده فنی مهندسی': 1,
    'دانشکده مهندسی کامپیوتر': 1,
    'دانشکده ادبیات و علوم انسانی': 1,
    'دانشکده بهداشت': 1,
    法学部: 1,
    ろう学校: 1,
    'auto ecole': 1,
    bis: 1,
    'driving school': 1,
    ecd: 1,
    'early childhood centre': 1,
    'ecole privée': 1,
    'engineering building': 1,
    grădiniță: 1,
    'lyceum international school': 1,
    surguuli: 1,
    'tamil school': 1,
    'vocational training authority': 1,
    구몬학습: 1,
    경비실: 1,
    정상어학원: 1,
    パソコン教室: 1,
    体育館: 1,
    キャンパス: 1,
    'технологический колледж': 1,
    'технический колледж': 1,
    'юридический факультет': 1,
    'агротехнический колледж': 1,
    'المدرسة الإعدادية': 1,
    'كلية البنات': 1,
    'كلية التربية البدنية': 1,
    'școala sportivă': 1,
    'școala de arte': 1,
    cobach: 1,
    conalep: 1,
    buap: 1,
    'centro de estudios de bachillerato': 1,
    'preescolar comunitario': 1,
    'primaria general': 1,
    'primaria indigena': 1,
    'primaria bilingue': 1,
    educem: 1,
    'tabika kemas': 1,
    'heritage international school': 1,
    'command children school': 1,
    academy: 1,
    muziekschool: 1,
    'open universiteit': 1,
    roc: 1,
    'secondary boarding school': 1,
    'english boarding school': 1,
    'boarding school': 1,
    'higher secondary school': 1,
    'boys high school': 1,
    'boys school': 1,
    'comprehensive school': 1,
    'department of biotechnology': 1,
    'department of law': 1,
    'foundation public school': 1,
    'nursing school': 1,
    'school of nursing': 1,
    'szkoła językowa': 1,
    'szkoła muzyczna': 1,
    'szkoła specjalna': 1,
    'technikum ekonomiczne': 1,
    tesda: 1,
    'the educators school': 1,
    'university of education': 1,
    'wyższe seminarium duchowne': 1,
    'школа танцев': 1,
    'шахматная школа': 1,
    'школа бокса': 1,
    'реальная школа': 1,
    'старая школа': 1,
    'nursing college': 1,
    'public school': 1,
    'community college': 1,
    școală: 1,
    'școală generală': 1,
    музыкальная: 1,
    المدرسة: 1,
    'escola profissional': 1,
    'i̇lköğretim okulu': 1,
    'american life': 1,
    'study english': 1,
    discovery: 1,
    alibra: 1,
    ispeak: 1,
    диалог: 1,
    перспектива: 1,
    skillset: 1,
    'bright english': 1,
    'учи.ру': 1,
    'i can read': 1,
    cristofori: 1,
    'final kurs': 1,
    'friends language school': 1,
    'study academy': 1,
    'early learning centre': 1,
    "teacher's resource centre": 1,
    convent: 1,
    'standard primary school': 1,
    'vocational institute': 1,
    'pre university college': 1,
    'model school': 1,
    'early learning center': 1,
    sma: 1,
    smk: 1,
    sdn: 1,
    smkn: 1,
    slb: 1,
    mis: 1,
    'school number 5': 1,
    'sport school': 1,
    'real school': 1,
    'teacher training college': 1,
    'public administration academy': 1,
    'escuela de manualidades': 1,
    'escuela comercial': 1,
    'instituto de formación docente': 1,
    'academia de baile': 1,
    'escuela de bellas artes': 1,
    'escuela superior de música': 1,
    'escuela para adultos': 1,
    'bachillerato acelerado para adultos': 1,
    'centro de formación profesional': 1,
    'centro universitario de idiomas': 1,
    'escuela de educación primaria': 1,
    'escuela de educación secundaria': 1,
    'escuela de educación técnica': 1,
    'escuela de educación especial': 1,
    'instituto adventista': 1,
    'escuela superior': 1,
    'escuela municipal': 1,
    'escuela de educacion secundaria': 1,
    'escuela de educación': 1,
    facultad: 1,
    conservatorio: 1,
    lyceé: 1,
    egb: 1,
    ingles: 1,
    'go! english': 1,
    'the english corner': 1,
    'centro educativo complementario': 1,
    'escuela de artes y oficios': 1,
    'escuela de robótica': 1,
    'servicio de educación especial': 1,
    'centro de educación': 1,
    jardin: 1,
    schule: 1,
    landesberufsschule: 1,
    skischule: 1,
    schischule: 1,
    'freie schule': 1,
    'sport-mittelschule': 1,
    hort: 1,
    'escuela de cocina': 1,
    'escuela de hotelería': 1,
    'escuela de policia': 1,
    'escuela de rock': 1,
    'escuela del nivel secundario': 1,
    wings: 1,
    math: 1,
    science: 1,
    art: 1,
    tabor: 1,
    jam: 1,
    musicland: 1,
    'school of public health': 1,
    'montessori academy': 1,
    'international school of music': 1,
    'g4 guitar school': 1,
    'maths words not squiggles': 1,
    'avenues education': 1,
    'fruition tuition': 1,
    'maths tuition': 1,
    's block': 1,
    'state school': 1,
    'catholic college': 1,
    'christian college': 1,
    'state college': 1,
    'secondary college': 1,
    'international college': 1,
    'académie de musique': 1,
    'academie voor muziek, woord en dans': 1,
    'civil department': 1,
    "collège d'enseignement général": 1,
    'computer department': 1,
    'école primaire franco arabe': 1,
    'ecole franco-arabe': 1,
    'english language center': 1,
    'foundation school': 1,
    'gemeentelijke basisschool': 1,
    gps: 1,
    'junior secondary school': 1,
    kleuterschool: 1,
    'lycée professionnel': 1,
    'mašinski fakultet': 1,
    'school institute': 1,
    'srednja škola': 1,
    "teachers' training college": 1,
    'technical training center': 1,
    'vrije basisschool': 1,
    škola: 1,
    'ecole priimaire': 1,
    garderie: 1,
    'ecole a': 1,
    'centre de langue': 1,
    tienda: 1,
    'buena vista': 1,
    frontera: 1,
    samaria: 1,
    pucara: 1,
    'antigua escuela': 1,
    'centro universitário': 1,
    'colegio municipal': 1,
    'escola de artes': 1,
    'escola de yoga': 1,
    'escola de español': 1,
    'house of languages': 1,
    integral: 1,
    'oficina do estudante': 1,
    rectorado: 1,
    times: 1,
    universidade: 1,
    centro: 1,
    escolinha: 1,
    cna: 1,
    'cna inglês': 1,
    'up idiomas': 1,
    'natural english': 1,
    'britannia english school': 1,
    ce: 1,
    eeef: 1,
    eeefm: 1,
    eeem: 1,
    emeief: 1,
    emeb: 1,
    eepef: 1,
    eeuef: 1,
    em: 1,
    'escola agrícola': 1,
    'escola criativa': 1,
    'escola casa do estudante': 1,
    'centro educacional para a vida': 1,
    'centro educacional integração': 1,
    auditório: 1,
    beetools: 1,
    'casa thomas jefferson': 1,
    ceas: 1,
    cebrac: 1,
    ceec: 1,
    cep: 1,
    cemei: 1,
    'departamento de geografia': 1,
    'departamento de história': 1,
    'departamento de letras': 1,
    dia: 1,
    die: 1,
    'escola classe': 1,
    'escola de reforço': 1,
    'escola técnica': 1,
    estácio: 1,
    'follow me': 1,
    'grau tecnico': 1,
    'happy code': 1,
    ica: 1,
    ieg: 1,
    riff: 1,
    'sala dos professores': 1,
    seg: 1,
    simple: 1,
    unip: 1,
    'yes! idiomas': 1,
    educandario: 1,
    'centro de ensino': 1,
    'unidade integrada': 1,
    'jardim de infancia': 1,
    knn: 1,
    'salas de aula': 1,
    externato: 1,
    'staff room': 1,
    'dinning hall': 1,
    'academic block i': 1,
    'academic block ii': 1,
    'staff quarter i': 1,
    'staff quarter ii': 1,
    'staff quarter iii': 1,
    'вячэрняя школа': 1,
    'школа 19': 1,
    'школа-інтэрнат': 1,
    'mr english': 1,
    'native english': 1,
    englishpapa: 1,
    enriver: 1,
    'the learning centre': 1,
    'faculté des sciences': 1,
    'kumon math & reading centre': 1,
    'kumon math and reading centre': 1,
    'école centrale': 1,
    primary: 1,
    'école enfantine': 1,
    'altes schulhaus': 1,
    turnhalle: 1,
    kochschule: 1,
    'école française': 1,
    'école centre': 1,
    'salle de classe': 1,
    'lycée moderne': 1,
    'escuela básica municipal': 1,
    'centro educacional de adultos': 1,
    internado: 1,
    'liceo comercial': 1,
    'casa de la música': 1,
    'escuela particular': 1,
    'escuela de lenguaje': 1,
    'institut superieur': 1,
    'faculty of sciences': 1,
    'government nursery school': 1,
    'science laboratory': 1,
    学院: 1,
    中学: 1,
    教学楼: 1,
    实验楼: 1,
    图书馆: 1,
    研究生院: 1,
    'esc.': 1,
    escuelita: 1,
    institute: 1,
    politécnico: 1,
    cancha: 1,
    educarte: 1,
    emotion: 1,
    'escuela de deportes': 1,
    'escuela de economía': 1,
    'escuela de primaria': 1,
    'facultad de turismo': 1,
    'facultad obrero campesina': 1,
    'forestry college': 1,
    formatur: 1,
    gimnasio: 1,
    'hotelová škola': 1,
    jagdschule: 1,
    'learning zone': 1,
    lingo: 1,
    melody: 1,
    'metropolitan university': 1,
    'pre universitario': 1,
    'sede universitaria': 1,
    seminario: 1,
    'střední odborná škola': 1,
    'střední škola obchodu a služeb': 1,
    'střední škola polytechnická': 1,
    wirtschaftsgymnasium: 1,
    akademie: 1,
    caritas: 1,
    'die schule': 1,
    fachhochschule: 1,
    gitarrenschule: 1,
    gitarrenunterricht: 1,
    graduiertenschule: 1,
    hochschule: 1,
    'hörsaal 1': 1,
    'hörsaal 2': 1,
    'hörsaal 3': 1,
    klavierschule: 1,
    klinikschule: 1,
    'kumon-lerncenter': 1,
    lernhilfe: 1,
    lernkreis: 1,
    pflegeschule: 1,
    produktionsschule: 1,
    'school of music': 1,
    sekretariat: 1,
    sporthalle: 1,
    'staatliche berufsschule': 1,
    studiertreff: 1,
    tanzwerk: 1,
    universität: 1,
    lycee: 1,
    cem: 1,
    emc: 1,
    ef: 1,
    technicum: 1,
    veritas: 1,
    'police school': 1,
    'british language centre': 1,
    'english center': 1,
    'helendoron english': 1,
    'berlitz school of languages': 1,
    'centre de formation professionnelle': 1,
    'مدرسة خاصة لتعليم اللغات': 1,
    'روضة الأطفال': 1,
    'faculty of science': 1,
    'house of knowledge': 1,
    'escuela de arte': 1,
    'escuela universitaria de turismo': 1,
    biblioteca: 1,
    'english wonderland': 1,
    'global english': 1,
    'escuela municipal de música y danza': 1,
    'centro de adultos': 1,
    masterclass: 1,
    'escuela taller': 1,
    'escuela de música y danza': 1,
    'escuela de baile': 1,
    'surf school': 1,
    'academia de inglés': 1,
    'escuela de hostelería': 1,
    'english connection': 1,
    'escuela internacional de posgrado': 1,
    'escola municipal de música': 1,
    "escola d'adults": 1,
    'english language school': 1,
    'centro didáctico de formación integral': 1,
    'escuela de teatro': 1,
    'taller de artes escénicas': 1,
    'escuela de circo': 1,
    'escuela universitaria de enfermería': 1,
    "escola superior d'infermeria": 1,
    'escuela concertada': 1,
    'centre educatiu privat': 1,
    'deutsche schule': 1,
    'lycée français': 1,
    'scuola statale': 1,
    'istituto italiano': 1,
    'escuela suiza': 1,
    faculty: 1,
    'department of education': 1,
    'integrated music center': 1,
    centre: 1,
    'school of design': 1,
    'art school': 1,
    'diplomatic school': 1,
    collage: 1,
    'law school': 1,
    'vision school': 1,
    'adventist school': 1,
    auditorio: 1,
    'escola superior': 1,
    'escuela de profesiones': 1,
    'escuela de letras': 1,
    'escuela de tauromaquia': 1,
    kansalaisopisto: 1,
    escoles: 1,
    eskolak: 1,
    ikastetxe: 1,
    ikastetxea: 1,
    liceu: 1,
    'école publique maternelle': 1,
    'école de ski francais': 1,
    'école de ski internationale': 1,
    'conservatoire de musique et de danse': 1,
    'centre de loisirs': 1,
    'école de la vie': 1,
    cyberbase: 1,
    'écoles maternelle et primaire': 1,
    'restaurant scolaire': 1,
    "section d'enseignement général et professionnel adapté": 1,
    cantine: 1,
    'centre de formation coiffure': 1,
    'institut de préparation aux examens et concours': 1,
    'lycée général': 1,
    'douces maternelles': 1,
    'école elementaire': 1,
    'école de ski français': 1,
    'école supérieure': 1,
    "centre de formation d'apprentis": 1,
    "section d'enseignement professionnel": 1,
    internat: 1,
    'sciences plus': 1,
    'lycée agricole': 1,
    'école élémentaire spécialisée': 1,
    'école maternelle intercommunale': 1,
    'école de commerce': 1,
    'école de communication': 1,
    'école des arts': 1,
    'école du second degré': 1,
    'école de voile': 1,
    'student services': 1,
    'construction skills centre': 1,
    'centre de formation': 1,
    'centre de langues': 1,
    'centre musical': 1,
    'conservatoire municipal': 1,
    faculté: 1,
    périscolaire: 1,
    salle: 1,
    bâtiment: 1,
    batiment: 1,
    amphi: 1,
    cfa: 1,
    ufr: 1,
    'assembly hall': 1,
    'dance studio': 1,
    'primary academy': 1,
    'infant school': 1,
    'cofe primary school': 1,
    'infant and nursery school': 1,
    'business college': 1,
    'experimental jhs': 1,
    gumnasio: 1,
    musical: 1,
    'orphanage school': 1,
    'preparatory school': 1,
    'school of business': 1,
    'senior high school': 1,
    "teachers' quarters": 1,
    'upper primary': 1,
    "l'école": 1,
    გიმნაზია: 1,
    δημοτικό: 1,
    'γυμνάσιο-λύκειο': 1,
    'παιδικός σταθμός': 1,
    φροντιστήριο: 1,
    'the language school': 1,
    'the english academy': 1,
    'academy school': 1,
    'centre de formation classique': 1,
    'ecole baptiste': 1,
    'ecole communautaire': 1,
    'ecole conservatrice': 1,
    'ecole de musique': 1,
    'ecole des sciences': 1,
    'ecole des soeurs': 1,
    'ecole presbiterale': 1,
    'ecole professionnelle': 1,
    'ecole professionelle': 1,
    'happy english': 1,
    'hello english': 1,
    'institution mixte': 1,
    'iskola és óvoda': 1,
    katedra: 1,
    'katedra nyelviskola': 1,
    'learning resource centre': 1,
    nyelvstúdió: 1,
    'oxford nyelviskola': 1,
    'school of engineering': 1,
    'school of science': 1,
    'talent studio': 1,
    ابتدائيه: 1,
    قوتابخانه‌: 1,
    المدارس: 1,
    'تربية بنات': 1,
    'شؤون الطلبة': 1,
    'المعهد التقني': 1,
    'كليه الصيدله': 1,
    qutabxane: 1,
    اعدادية: 1,
    'مجمع مدارس': 1,
    'مدرسة للبنات': 1,
    'ثانوية للبنين': 1,
    amideast: 1,
    cis: 1,
    'king school': 1,
    مدرسە: 1,
    مد: 1,
    'department of civil engineering': 1,
    'دانشکده عمران': 1,
    'دانشکده مکانیک': 1,
    'آیلتس سنتر نسل فردا': 1,
    'دانشکده فنی': 1,
    'دانشکده مهندسی شیمی': 1,
    'دانشکده برق و کامپیوتر': 1,
    'مدرسه شبانه روزی': 1,
    'دانشکده کامپیوتر': 1,
    'هنرستان فنی': 1,
    'هنرستان دخترانه': 1,
    'کانون پرورش فکری کودکان و نوجوانان': 1,
    'مدرسه استثنایی': 1,
    'حوزه علمیه برادران': 1,
    'مجتمع فنی تهران': 1,
    'ستاد اسکان فرهنگیان': 1,
    کانون: 1,
    'شبانه روزی': 1,
    'آموزشگاه زبان': 1,
    'مدرسه ابتدایی پسرانه': 1,
    'مدرسه پسرانه': 1,
    دانش: 1,
    'آموزش و پرورش': 1,
    'دانشکده پزشکی': 1,
    'دانشکده دامپزشکی': 1,
    'دانشکده شیمی': 1,
    'دانشکده فیزیک': 1,
    'دبستان پسرانه': 1,
    'دبستان دخترانه': 1,
    'دبیرستان دخترانه': 1,
    'دبیرستان پسرانه': 1,
    'مدرسه دخترانه': 1,
    'business school': 1,
    経済学部: 1,
    小学校: 1,
    中学校: 1,
    高等学校: 1,
    養護学校: 1,
    私立: 1,
    県立: 1,
    市立: 1,
    町立: 1,
    スミス英会話: 1,
    ecc英会話: 1,
    lec: 1,
    駿台予備校: 1,
    'カワイ 音楽教室': 1,
    こども英会話のミネルヴァ: 1,
    アメリカンランゲージスクール: 1,
    rms音楽教室: 1,
    '個別指導 axis': 1,
    アビバ: 1,
    新星塾: 1,
    駿台: 1,
    子供英会話ペッピーキッズクラブ: 1,
    ベスト学院: 1,
    研伸館: 1,
    coco塾: 1,
    ベルリッツ: 1,
    'dr.関塾': 1,
    テスコ英会話: 1,
    個別指導の明光義塾: 1,
    'トライ＋プラス': 1,
    アーク学習塾: 1,
    メガブルーバード: 1,
    ロボ団: 1,
    河合塾wings: 1,
    花まる学習会: 1,
    個別指導学院フリーステップ: 1,
    全教研: 1,
    青二塾: 1,
    '子ども英会話 ペッピーキッズクラブ': 1,
    '個別指導 大沼総合教室': 1,
    英進館: 1,
    個別指導のアニー: 1,
    東京個別: 1,
    創学舎: 1,
    テスコ: 1,
    'school ie': 1,
    ノーバス: 1,
    そろばん教室88くん: 1,
    イーオン: 1,
    ena: 1,
    個別指導wam: 1,
    関西個別指導学院: 1,
    '個別指導塾　学習空間': 1,
    馬渕個別: 1,
    kec個別: 1,
    'international university': 1,
    'training center': 1,
    'computer lab': 1,
    'institute of foreign languages': 1,
    'national defense university': 1,
    'mission school': 1,
    driving: 1,
    soundskool: 1,
    'school 1': 1,
    'islamic center': 1,
    'senior school': 1,
    초등학교: 1,
    중학교: 1,
    대학교: 1,
    운동장: 1,
    정문: 1,
    상상학원: 1,
    최강학원: 1,
    대학본부: 1,
    쇼팽음악학원: 1,
    뮤엠영어: 1,
    에이플러스학원: 1,
    윤선생영어교실: 1,
    필아트미술학원: 1,
    스마트해법수학: 1,
    기탄사고력교실: 1,
    푸르넷공부방: 1,
    아소비학원: 1,
    윤선생우리집앞영어교실: 1,
    'king sejong institute': 1,
    'study plus education': 1,
    'школа каратэ': 1,
    автошкола: 1,
    'центр немецкого языка': 1,
    'школа гимназия': 1,
    mektep: 1,
    лаоши: 1,
    'tamil vidyalaya': 1,
    vidyalaya: 1,
    'muslim vidyalaya': 1,
    'school building': 1,
    'music factory': 1,
    'college of business administration': 1,
    'faculty of agriculture': 1,
    'child development center': 1,
    'graduate school': 1,
    'central college': 1,
    'collège privé': 1,
    'ecole primaire publique': 1,
    department: 1,
    'université privée': 1,
    'sală de sport': 1,
    روضة: 1,
    مركز: 1,
    قسم: 1,
    'مدرسة خاصة': 1,
    'baga сургууль': 1,
    "centre d'alphabetisation": 1,
    'école fondamentale': 1,
    'école franco-arabe': 1,
    'ecole coranique madersa': 1,
    'ecole de santé': 1,
    'escuela de educacion especial': 1,
    'facultad de filosofia': 1,
    'facultad de psicologia': 1,
    'jardin de niños': 1,
    "jardin d'enfants communautaire": 1,
    mederça: 1,
    medarsa: 1,
    'médersa franco arabe': 1,
    'primaria estatal': 1,
    tsetserleg: 1,
    'centro pedagogico': 1,
    'facultad de pedagogia': 1,
    'facultad de trabajo social': 1,
    'centro de atencion multiple': 1,
    'centro de desarrollo integral': 1,
    'centro tecnologico': 1,
    'escuela de trabajo': 1,
    preparatoria: 1,
    ces: 1,
    capa: 1,
    compuinglés: 1,
    'control escolar': 1,
    ep: 1,
    epsm: 1,
    kínder: 1,
    'lecture hall': 1,
    'main entrance': 1,
    'quick learning': 1,
    'école des cadres': 1,
    'command secondary school': 1,
    'community high school': 1,
    'comprehensive high school': 1,
    seminary: 1,
    'teachers resource centre': 1,
    'nomadic school': 1,
    nomadic: 1,
    skole: 1,
    skule: 1,
    'videregående skole': 1,
    høgskole: 1,
    'coaching center': 1,
    hogeschool: 1,
    universiteit: 1,
    volksuniversiteit: 1,
    dansacademie: 1,
    mbo: 1,
    'प्राथमिक विद्यालय': 1,
    'माध्यमिक विद्यालय': 1,
    'administrative building': 1,
    'lower secondary school': 1,
    'ma v': 1,
    'ni ma vi': 1,
    'pra v': 1,
    'pra bi': 1,
    'pra vi': 1,
    'english medium school': 1,
    'laboratory school': 1,
    'intermediate school': 1,
    'आधारभूत विद्यालय': 1,
    'प्रा वि': 1,
    'मा वि': 1,
    'आ वि': 1,
    बिद्यालय: 1,
    बिधालय: 1,
    pathshala: 1,
    gurukul: 1,
    'बाल विकास केन्द्र': 1,
    "girl's school": 1,
    'gulf college': 1,
    sencico: 1,
    unknown: 1,
    iberoamericano: 1,
    oriental: 1,
    panamericano: 1,
    politecnico: 1,
    ceba: 1,
    capullito: 1,
    creciendo: 1,
    genesis: 1,
    centenario: 1,
    'los educadores': 1,
    'los rosales': 1,
    'dental college': 1,
    'school of technology': 1,
    'computer college': 1,
    'learning center': 1,
    'national high school': 1,
    'computer school': 1,
    'learning nook': 1,
    'school supplies': 1,
    'daycare learning center': 1,
    'liceum ogólnokształcące': 1,
    'szkoła branżowa': 1,
    'szkoła rolnicza': 1,
    'branżowa szkoła': 1,
    'perfect english': 1,
    'empik school': 1,
    'prestige college': 1,
    'top school': 1,
    'funny english': 1,
    lincoln: 1,
    imagine: 1,
    'colorful english': 1,
    perfect: 1,
    'cool school': 1,
    hello: 1,
    level: 1,
    lider: 1,
    speaker: 1,
    britam: 1,
    riviera: 1,
    hakiel: 1,
    językownia: 1,
    'technikum zawodowe': 1,
    'technikum chemiczne': 1,
    'technikum ogrodnicze': 1,
    'technikum samochodowe': 1,
    'liceum plastyczne': 1,
    'academia de música': 1,
    'centro de estudos': 1,
    'centro de formação profissional': 1,
    'english institute': 1,
    'international flight academy': 1,
    'facultatea de inginerie': 1,
    'facultatea de drept': 1,
    'facultatea de biologie': 1,
    'facultatea de istorie': 1,
    'facultatea de agronomie': 1,
    'facultatea de chimie': 1,
    'școala generală': 1,
    'școala de șoferi': 1,
    'școala cu clasele': 1,
    'școala nr.': 1,
    'centar stranih jezika': 1,
    'средняя общеобразовательная школа': 1,
    'языковой центр': 1,
    'курсы иностранных языков': 1,
    'профессиональное училище': 1,
    'коррекционная школа': 1,
    'лингвистический центр': 1,
    'школа искуств': 1,
    'школа интернат': 1,
    'школа - интернат': 1,
    спортзал: 1,
    'спортивный зал': 1,
    'дом пионеров': 1,
    'коррекционная школа-интернат': 1,
    спецшкола: 1,
    'моя школа': 1,
    'сельская школа': 1,
    'детская школа искуств': 1,
    прогимназия: 1,
    'шахматный клуб': 1,
    мбоу: 1,
    нш: 1,
    community: 1,
    'music club': 1,
    'english studio': 1,
    общежитие: 1,
    'учебный корпус': 1,
    столовая: 1,
    'مدرسة بنين': 1,
    جامعة: 1,
    musikskolan: 1,
    'admin building': 1,
    академия: 1,
    'iq school': 1,
    'alpha school': 1,
    'family english': 1,
    'global village': 1,
    languagelink: 1,
    lingualab: 1,
    lingwood: 1,
    speakout: 1,
    okul: 1,
    'local school': 1,
    'technical high school': 1,
    โรงเรียน: 1,
    'eglise catholique': 1,
    epl: 1,
    ism: 1,
    isep: 1,
    'école 2': 1,
    aptech: 1,
    'easy abc': 1,
    levelup: 1,
    'english home': 1,
    'birey dershanesi': 1,
    'the dance station': 1,
    kindermusik: 1,
    'botany department': 1,
    'british time': 1,
    education: 1,
    'institute of adult education': 1,
    'playing ground': 1,
    'training centre': 1,
    'science lab': 1,
    補習班: 1,
    shule: 1,
    'barefoot college': 1,
    ліцей: 1,
    'музична школа': 1,
    'вечірня школа': 1,
    'дитячо-юнацька спортивна школа': 1,
    'школа молодших класів': 1,
    'дитяча хореографічна школа': 1,
    'будинок школяра': 1,
    'школа і ступеню': 1,
    'kiev art school': 1,
    'спортивна школа': 1,
    'мовна школа': 1,
    зош: 1,
    'курси англійської мови': 1,
    sky: 1,
    'community learning centre': 1,
    'training institute': 1,
    'vocational secondary school': 1,
    'primary teachers college': 1,
    'model primary school': 1,
    'teachers college': 1,
    'domestic science institute': 1,
    'preparatory primary school': 1,
    'seed secondary school': 1,
    'demonstration school': 1,
    'counselling centre': 1,
    'bible school': 1,
    'technical training institute': 1,
    "teachers' resource centre": 1,
    'early child development': 1,
    "children's centre": 1,
    'junior primary school': 1,
    'technical institute': 1,
    'farm institute': 1,
    'agricultural institute': 1,
    'early childhood development school': 1,
    'junior academy': 1,
    'quran school': 1,
    'moslem primary school': 1,
    'islamic centre': 1,
    maktab: 1,
    'tuition center': 1,
    'islamic boarding school': 1,
    'tk islam': 1,
    'fakultas pertanian': 1,
    'fakultas hukum': 1,
    'balai pengajian': 1,
    'tk aba': 1,
    'tk pkk': 1,
    'junior college': 1,
    sdlb: 1,
    'administrative block': 1,
    'anganvadi school': 1,
    anganavadi: 1,
    'convent school': 1,
    'governament school': 1,
    'goverment degree college': 1,
    'goverment higher secondary school': 1,
    'goverment school': 1,
    'govt sec school': 1,
    'government iti college': 1,
    'govt. boys school': 1,
    'govt. higher secondary school': 1,
    'govt. iti': 1,
    'govt. senior secondary school': 1,
    'last school': 1,
    'mechanical engineering': 1,
    'muncipal school': 1,
    'pharmacy block': 1,
    'up school': 1,
    workshop: 1,
    anganwadi: 1,
    'assembly ground': 1,
    'basketball court': 1,
    'computer science block': 1,
    'department of commerce': 1,
    'department of computer science': 1,
    'eee block': 1,
    'government arts and science college': 1,
    'government boys college': 1,
    'government central school': 1,
    'government industrial training institute': 1,
    'government inter college': 1,
    'government juniour college': 1,
    'government lp school': 1,
    'government polytechnic college': 1,
    'government school ground': 1,
    'government up school': 1,
    'governament high school': 1,
    'goverment middle school': 1,
    'goverment primary school': 1,
    'govt degree college': 1,
    'higher secondary block': 1,
    'industrial training institute': 1,
    'main block': 1,
    'mechanical block': 1,
    'tution centre': 1,
    'university press': 1,
    vidya: 1,
    'early childhood center': 1,
    center: 1,
    hall: 1,
    house: 1,
    'school district': 1,
    'grade school': 1,
    'magnet high school': 1,
    'charter schools': 1,
};
