let { genreMap } = require('./genres_map');

// Helper function to calculate string similarity using Levenshtein distance
function levenshteinDistance(str1, str2) {
    const track = Array(str2.length + 1).fill(null).map(() =>
        Array(str1.length + 1).fill(null));

    for (let i = 0; i <= str1.length; i++) {
        track[0][i] = i;
    }
    for (let j = 0; j <= str2.length; j++) {
        track[j][0] = j;
    }

    for (let j = 1; j <= str2.length; j++) {
        for (let i = 1; i <= str1.length; i++) {
            const indicator = str1[i - 1] === str2[j - 1] ? 0 : 1;
            track[j][i] = Math.min(
                track[j][i - 1] + 1,
                track[j - 1][i] + 1,
                track[j - 1][i - 1] + indicator
            );
        }
    }
    return track[str2.length][str1.length];
}

// Helper function to normalize string for comparison
function normalizeString(str) {
    return str.toLowerCase()
        .replace(/[^a-z0-9\s]/g, '') // Remove special characters
        .replace(/\s+/g, ' ') // Normalize spaces
        .trim();
}

// Helper function to find best matching genre
function findBestMatch(spotifyGenre, genreMap) {
    let bestMatch = null;
    let bestScore = Infinity;
    const normalizedSpotifyGenre = normalizeString(spotifyGenre);

    for (const [key, value] of Object.entries(genreMap)) {
        const normalizedKey = normalizeString(key);
        const score = levenshteinDistance(normalizedSpotifyGenre, normalizedKey);

        // Also check existing Spotify genres for exact matches
        const existingMatches = value.s ? value.s.some(g =>
            normalizeString(g) === normalizedSpotifyGenre) : false;

        if (existingMatches) {
            return key;
        }

        if (score < bestScore) {
            bestScore = score;
            bestMatch = key;
        }
    }

    // Only return a match if it's reasonably close (adjust threshold as needed)
    return bestScore < 10 ? bestMatch : null;
}

// Function to merge genres
function mergeGenres(spotifyGenres, genreMap) {
    const updates = {};
    const unmatched = [];

    spotifyGenres.forEach(genre => {
        const bestMatch = findBestMatch(genre, genreMap);

        if (bestMatch) {
            if (!updates[bestMatch]) {
                updates[bestMatch] = new Set(genreMap[bestMatch].s || []);
            }
            updates[bestMatch].add(genre);
        } else {
            unmatched.push(genre);
        }
    });

    // Convert updates back to arrays and merge with original map
    const mergedMap = {...genreMap};
    Object.entries(updates).forEach(([key, value]) => {
        mergedMap[key] = {
            ...mergedMap[key],
            s: Array.from(value)
        };
    });

    return {
        mergedMap,
        unmatched
    };
}

let spotifyGenres = [
    "cosmic american",
    "jam band",
    "psychedelic rock",
    "celtic",
    "irish folk",
    "mariachi",
    "ranchera",
    "classic schlager",
    "easy listening",
    "calypso",
    "country rock",
    "folk rock",
    "roots rock",
    "mellow gold",
    "soft rock",
    "europop",
    "swedish pop",
    "classic j-rock",
    "fado",
    "fado antigo",
    "fado de coimbra",
    "brighton indie",
    "celtic rock",
    "grebo",
    "canadian pop",
    "canadian rock",
    "pop rock",
    "post-grunge",
    "ectofolk",
    "british invasion",
    "nashville sound",
    "progressive rock",
    "symphonic rock",
    "funk metal",
    "instrumental rock",
    "shred",
    "canzone d'autore",
    "canzone genovese",
    "classic italian pop",
    "folk rock italiano",
    "italian adult pop",
    "musica sarda",
    "british folk",
    "classic pakistani pop",
    "filmi",
    "indian fusion",
    "pakistani folk",
    "qawwali",
    "sufi",
    "world",
    "american folk revival",
    "traditional folk",
    "new age",
    "dutch rock",
    "nederpop",
    "folk metal",
    "german metal",
    "hurdy-gurdy",
    "medieval rock",
    "neue deutsche harte",
    "gregorian dance",
    "operatic pop",
    "puirt-a-beul",
    "scottish rock",
    "progressive metal",
    "adult standards",
    "lounge",
    "rock-and-roll",
    "rockabilly",
    "vocal jazz",
    "alternative country",
    "chamber pop",
    "tucson indie",
    "afropop",
    "south african choral",
    "contemporary vocal jazz",
    "jazz pop",
    "neo mellow",
    "cantautor",
    "folklore argentino",
    "folklore surero",
    "guitarra argentina",
    "musica andina",
    "nueva cancion",
    "rock nacional",
    "trova",
    "zamba",
    "canadian singer-songwriter",
    "lilith",
    "permanent wave",
    "blues rock",
    "british blues",
    "electric blues",
    "lo-fi",
    "outsider",
    "classic swedish pop",
    "folkmusik",
    "svensk progg",
    "visor",
    "latin pop",
    "puerto rican pop",
    "irish country",
    "bluegrass",
    "instrumental bluegrass",
    "jamgrass",
    "jazz violin",
    "mandolin",
    "progressive bluegrass",
    "british industrial",
    "experimental",
    "industrial",
    "neofolk",
    "banjo",
    "bluegrass gospel",
    "irish rock",
    "scottish new wave",
    "deep christian rock",
    "jesus movement",
    "anarcho-punk",
    "psychedelic folk",
    "chanson",
    "american primitive",
    "fingerstyle",
    "celtic metal",
    "dutch metal",
    "neo classical metal",
    "prog metal",
    "sci-fi metal",
    "symphonic metal",
    "experimental rock",
    "industrial rock",
    "jazz guitar",
    "beat italiano",
    "trop rock",
    "drone folk",
    "canzone napoletana",
    "euskal rock",
    "spanish folk",
    "medieval folk",
    "rune folk",
    "contemporary folk",
    "classic texas country",
    "australian indigenous music",
    "australian rock",
    "canterbury scene",
    "doo-wop",
    "ecm-style jazz",
    "jazz piano",
    "norwegian jazz",
    "torch song",
    "canadian celtic",
    "breton folk",
    "french rock",
    "jangle pop",
    "power pop",
    "solo wave",
    "modern folk rock",
    "modern rock",
    "stomp and holler",
    "uk americana",
    "classic uk pop",
    "acoustic rock",
    "folk punk",
    "australian pop",
    "vocal harmony group",
    "prepared piano",
    "acoustic blues",
    "country blues",
    "modern blues",
    "piedmont blues",
    "pastoral",
    "library music",
    "cancion melodica",
    "pop romantico",
    "yorkshire folk",
    "bolero",
    "folklore ecuatoriano",
    "musica popular colombiana",
    "british comedy",
    "jazz clarinet",
    "nl folk",
    "steampunk",
    "corsican folk",
    "polyphonies corses",
    "polyphony",
    "irish singer-songwriter",
    "freak folk",
    "new weird america",
    "scottish folk",
    "scottish gaelic folk",
    "indie folk",
    "new americana",
    "neo-classical",
    "traditional british folk",
    "classic country pop",
    "old-time",
    "video game music",
    "north carolina indie",
    "north carolina roots",
    "acid rock",
    "roots worship",
    "bagpipe",
    "traditional scottish folk",
    "scottish singer-songwriter",
    "country gospel",
    "traditional country",
    "south african jazz",
    "cascadia psych",
    "free folk",
    "noise rock",
    "ambient folk",
    "melancholia",
    "spectra",
    "spanish pop",
    "folk-pop",
    "new wave pop",
    "folclore tucumano",
    "garage rock",
    "palm desert scene",
    "italian progressive rock",
    "philly indie",
    "alternative rock",
    "anti-folk",
    "countrygaze",
    "noise pop",
    "japanese singer-songwriter",
    "classic garage rock",
    "modern power pop",
    "scottish indie",
    "shoegaze",
    "art rock",
    "acoustic punk",
    "pov: indie",
    "flamenco",
    "rumba",
    "neo-progressive",
    "christian uplift",
    "baroque pop",
    "beatlesque",
    "martial industrial",
    "swedish americana",
    "swedish country",
    "anadolu rock",
    "karadeniz turkuleri",
    "turkish psych",
    "turkish rock",
    "bolero mexicano",
    "nova canco",
    "british singer-songwriter",
    "flamenco guitar",
    "scottish hush",
    "liedermacher",
    "balkan brass",
    "klezmer",
    "alpine yodeling",
    "australian americana",
    "australian country",
    "acoustic pop",
    "indie anthem-folk",
    "neo-singer-songwriter",
    "uk pop",
    "viral pop",
    "classic mandopop",
    "taiwan campus folk",
    "taiwan singer-songwriter",
    "virginia indie",
    "appalachian folk",
    "kentucky mountain folk",
    "mountain dulcimer",
    "string folk",
    "indie pop",
    "piano rock",
    "audiophile vocal",
    "flute rock",
    "gothic americana",
    "chilean rock",
    "musica andina chilena",
    "dutch prog",
    "latin rock",
    "rock en espanol",
    "spanish folk metal",
    "spanish metal",
    "eau claire indie",
    "alternative roots rock",
    "narodna muzika",
    "turbo folk",
    "british power metal",
    "comic metal",
    "pirate",
    "power metal",
    "scottish metal",
    "denton tx indie",
    "polka",
    "gothenburg indie",
    "swedish indie folk",
    "swedish indie pop",
    "swedish singer-songwriter",
    "irish neo-traditional",
    "norske viser",
    "grunge",
    "native american flute",
    "native american traditional",
    "navajo",
    "irish accordion",
    "jazz metal",
    "norwegian alternative rock",
    "norwegian experimental",
    "norwegian prog",
    "norwegian psychedelic",
    "norwegian punk",
    "norwegian rock",
    "schlager",
    "britpop",
    "harp",
    "krautrock",
    "space rock",
    "argentine rock",
    "musica de intervencao",
    "portuguese folk",
    "new age piano",
    "metropopolis",
    "tape club",
    "latin alternative",
    "smooth jazz",
    "yacht rock",
    "musica nublensina",
    "psicodelia chilena",
    "australian blues",
    "australian singer-songwriter",
    "australian alternative rock",
    "perth indie",
    "cowboy western",
    "new mexico music",
    "outlaw country",
    "classic belgian pop",
    "flemish folk",
    "kleinkunst",
    "black metal",
    "doom metal",
    "downtempo",
    "drone metal",
    "norwegian black metal",
    "norwegian metal",
    "post-metal",
    "classic norwegian pop",
    "trondersk musikk",
    "gothic metal",
    "gothic symphonic metal",
    "swiss metal",
    "german rock",
    "seemannslieder",
    "nashville singer-songwriter",
    "neo-pagan",
    "candy pop",
    "argentine ambient",
    "latin classical",
    "latin soundtrack",
    "orchestral soundtrack",
    "soundtrack",
    "classic indonesian rock",
    "gbvfi",
    "post-hardcore",
    "slacker rock",
    "western mass indie",
    "australian indie folk",
    "australian reggae fusion",
    "rock of gibraltar",
    "sean-nos singing",
    "classic polish pop",
    "polish pop",
    "sung poetry",
    "glam rock",
    "classic nz pop",
    "nz pop",
    "nz singer-songwriter",
    "gaian doom",
    "post-rock",
    "supergroup",
    "german prog",
    "hammond organ",
    "jazz rock",
    "finnish metal",
    "nordic folk metal",
    "viking metal",
    "charango",
    "folklore boliviano",
    "tinku",
    "edmonton indie",
    "lo-fi indie",
    "paracana",
    "canadian americana",
    "canadian country",
    "michigan indie",
    "gainesville indie",
    "orgcore",
    "skate punk",
    "finnish folk",
    "karelian folk",
    "nordic folk",
    "art pop",
    "slowcore",
    "washington indie",
    "bubblegum pop",
    "sunshine pop",
    "bow pop",
    "neoclassical darkwave",
    "canadian indie",
    "canadian indie folk",
    "ontario indie",
    "toronto indie",
    "merseybeat",
    "bush ballad",
    "cambridgeshire indie",
    "canadian blues",
    "classic canadian rock",
    "ukulele",
    "accordion",
    "bandoneon",
    "classical accordion",
    "french jazz",
    "italian contemporary jazz",
    "jazz accordion",
    "chamber folk",
    "traditional english folk",
    "dixieland",
    "jazz trombone",
    "jazz trumpet",
    "dalarna indie",
    "swedish garage rock",
    "swedish indie rock",
    "folklore veracruzano",
    "mariachi cristiano",
    "cloud rap",
    "dark trap",
    "experimental guitar",
    "french folk",
    "classic danish pop",
    "dansktop",
    "norwegian pop",
    "women's music",
    "compositional ambient",
    "classic icelandic pop",
    "icelandic folk",
    "icelandic pop",
    "icelandic rock",
    "icelandic singer-songwriter",
    "drone",
    "blasmusik",
    "volkspop",
    "devon indie",
    "austin singer-songwriter",
    "irish pub song",
    "zolo",
    "australian indie",
    "canadian folk",
    "nu jazz",
    "polish alternative rock",
    "polish post-punk",
    "polish rock",
    "balkan beats",
    "sevdah",
    "protest folk",
    "alternative metal",
    "nu metal",
    "nuevo flamenco",
    "pop flamenco",
    "balfolk",
    "nyckelharpa",
    "estonian metal",
    "estonian rock",
    "slavic metal",
    "brooklyn indie",
    "classic oklahoma country",
    "folclore salteno",
    "bulgarian pop",
    "children's folk",
    "olympia wa indie",
    "contemporary r&b",
    "chill pop",
    "texas country",
    "canadian soundtrack",
    "folk black metal",
    "irish black metal",
    "irish metal",
    "pagan black metal",
    "symphonic black metal",
    "fantasy metal",
    "italian folk metal",
    "italian metal",
    "italian power metal",
    "melodic metal",
    "tolkien metal",
    "neue deutsche welle",
    "ostrock",
    "folclore castilla y leon",
    "classic opm",
    "nasheed",
    "montana indie",
    "classic portuguese pop",
    "portuguese rock",
    "dark folk",
    "viking folk",
    "boston folk",
    "new england americana",
    "narodnozabavna",
    "slovenian pop",
    "slovenian rock",
    "french indie pop",
    "louisiana blues",
    "swamp rock",
    "cello",
    "dark cabaret",
    "rhode island indie",
    "australian ska",
    "ska jazz",
    "detroit house",
    "kundiman",
    "protopunk",
    "cancion infantil latinoamericana",
    "musica para ninos",
    "nottingham indie",
    "irish contemporary classical",
    "orkney and shetland folk",
    "scottish fiddle",
    "belgian rock",
    "uilleann pipes",
    "deep neofolk",
    "icelandic indie",
    "ottawa indie",
    "morna",
    "semba",
    "german power metal",
    "street band",
    "desert blues",
    "malian blues",
    "moroccan rock",
    "musique touareg",
    "tuareg guitar",
    "western saharan folk",
    "cantautora mexicana",
    "musica indigena latinoamericana",
    "musica oaxaquena",
    "nuevo folklore mexicano",
    "oaxaca indie",
    "rock quebecois",
    "american grindcore",
    "noisecore",
    "welsh rock",
    "auteur-compositeur-interprete quebecois",
    "folklore quebecois",
    "portuguese pop",
    "baglama",
    "bozlak",
    "turkish folk",
    "nouvelle chanson francaise",
    "cape breton folk",
    "chanson quebecois",
    "prog quebec",
    "gypsy punk",
    "iowa indie",
    "classical mandolin",
    "irish fiddle",
    "jig and reel",
    "essex indie",
    "kindie rock",
    "cajun",
    "autonomous black metal",
    "depressive black metal",
    "usbm",
    "irish dance",
    "gaita",
    "galician folk",
    "latin arena pop",
    "mexican pop",
    "french pop",
    "shiver pop",
    "gospel singers",
    "south african gospel",
    "folktronica",
    "comedia",
    "collage pop",
    "modern alternative rock",
    "stomp pop",
    "christian indie",
    "indy indie",
    "alt z",
    "chinese indie",
    "chinese minyao",
    "singer-songwriter pop",
    "grave wave",
    "bedroom pop",
    "musica folk asturiana",
    "chamber psych",
    "freakbeat",
    "swedish metal",
    "viking black metal",
    "ambient country",
    "tennessee experimental",
    "alternative americana",
    "traditional bluegrass",
    "canto popular uruguayo",
    "folklore uruguayo",
    "rock independant francais",
    "experimental folk",
    "experimental psych",
    "newcastle indie",
    "british experimental",
    "latin metal",
    "spanish prog",
    "reggae fusion",
    "reggae rock",
    "anime score",
    "slack-key guitar",
    "surf music",
    "indonesian experimental",
    "indonesian psychedelia",
    "modern psychedelic folk",
    "alternative emo",
    "bubblegrunge",
    "emo",
    "lo-fi emo",
    "small room",
    "swamp pop",
    "zydeco",
    "german pop",
    "shimmer pop",
    "raga rock",
    "gothic rock",
    "cantautor catala",
    "musica pitiusa",
    "rock catala",
    "laboratorio",
    "turkish trap pop",
    "chinese metal",
    "oriental metal",
    "russian folk rock",
    "austin americana",
    "soul blues",
    "melodic death metal",
    "hammered dulcimer",
    "indie punk",
    "bergen indie",
    "norwegian indie",
    "canadian children's music",
    "neo-traditional bluegrass",
    "kent indie",
    "medway sound",
    "punk blues",
    "modern old-time",
    "duluth indie",
    "weirdcore",
    "portland punk",
    "jazz quartet",
    "post-punk argentina",
    "melbourne indie",
    "abstractro",
    "polish folk metal",
    "polish metal",
    "slavic folk metal",
    "neo-psychedelic",
    "portland indie",
    "celtic harp",
    "irish pop",
    "scottish indie folk",
    "russian metal",
    "russian rock",
    "heartland rock",
    "new jersey hardcore",
    "new jersey indie",
    "new jersey punk",
    "modern indie pop",
    "arabesk",
    "neo honky tonk",
    "dark wave",
    "ethereal wave",
    "drone rock",
    "celtic punk",
    "finnish experimental",
    "new weird finland",
    "italian folk",
    "neo soul",
    "r&b",
    "urban contemporary",
    "austropop",
    "neue volksmusik",
    "vermont indie",
    "shanty",
    "dallas indie",
    "russian punk",
    "deep contemporary country",
    "old-time fiddle",
    "cornish folk",
    "comic",
    "dark pop",
    "neo-synthpop",
    "swedish electropop",
    "swedish synthpop",
    "pop soul",
    "turkish singer-songwriter",
    "uk post-punk revival",
    "norwegian folk rock",
    "c86",
    "uk post-punk",
    "maine indie",
    "german melodeath",
    "pop quebecois",
    "doomgaze",
    "sacramento indie",
    "string band",
    "nashville americana",
    "chillwave",
    "electronica",
    "indietronica",
    "wonky",
    "classic finnish pop",
    "classic iskelma",
    "appalachian black metal",
    "atmospheric black metal",
    "bosnian electronic",
    "forest black metal",
    "kentucky metal",
    "voidgaze",
    "dream pop",
    "spirituals",
    "classic persian pop",
    "clawhammer banjo",
    "czech folk",
    "czech rock",
    "czech singer-songwriter",
    "irish flute",
    "geek folk",
    "deep acoustic pop",
    "musica occitana",
    "japanese indie pop",
    "modern progressive rock",
    "polish prog",
    "bluegrass fiddle",
    "queer country",
    "kingston on indie",
    "western americana",
    "swedish power metal",
    "british soul",
    "welsh indie",
    "starogradska",
    "ann arbor indie",
    "detroit indie",
    "electro-pop francais",
    "french indie folk",
    "swiss rock",
    "andean panpipe",
    "asbury park indie",
    "austindie",
    "saskatchewan indie",
    "la indie",
    "scottish americana",
    "neon pop punk",
    "pop punk",
    "azeri traditional",
    "northumbrian folk",
    "irish banjo",
    "new jack swing",
    "psychobilly",
    "manitoba indie",
    "swedish jazz",
    "traditional southern folk",
    "finnish indie",
    "suomi rock",
    "bosnian pop",
    "utah indie",
    "furry",
    "dutch pop",
    "chinese folk",
    "christian power metal",
    "israeli metal",
    "talent show",
    "oth indie",
    "electra",
    "rock in opposition",
    "ukrainian folk",
    "muzica lautareasca",
    "muzica populara",
    "muzica usoara",
    "romanian folk",
    "veracruz indie",
    "etherpop",
    "mande pop",
    "kantele",
    "dutch folk",
    "sami",
    "jacksonville indie",
    "arab folk",
    "manila sound",
    "opm",
    "rochester ny indie",
    "ccm",
    "christian alternative rock",
    "christian music",
    "fantasy",
    "sefardi",
    "vienna indie",
    "novelty",
    "san marcos tx indie",
    "garage punk blues",
    "baltic classical",
    "latvian pop",
    "bahamian folk",
    "midwest americana",
    "ghazal",
    "pakistani pop",
    "belgian pop",
    "estonian pop",
    "balearic",
    "bay area indie",
    "laulaja-lauluntekija",
    "idaho indie",
    "michigan folk",
    "baltimore indie",
    "children's music",
    "spanish indie folk",
    "spanish indie pop",
    "south african alternative",
    "charlottesville indie",
    "classic hungarian rock",
    "hungarian pop",
    "swedish fiddle",
    "swedish prog",
    "hamilton on indie",
    "psychedelic space rock",
    "black americana",
    "pei indie",
    "cornwall indie",
    "russian folk metal",
    "welsh folk",
    "vancouver indie",
    "grand rapids indie",
    "modern country pop",
    "cumbia",
    "salsa colombiana",
    "vallenato moderno",
    "deep ccm",
    "world worship",
    "worship",
    "british post-rock",
    "instrumental post-rock",
    "stomp and flutter",
    "v-pop",
    "kabyle",
    "rai",
    "nashville indie",
    "leicester indie",
    "german pagan metal",
    "finnish psychedelic rock",
    "finnish pop",
    "iskelma",
    "country dawn",
    "dainuojamoji poezija",
    "lithuanian indie",
    "dutch indie",
    "dutch indie rock",
    "dutch singer-songwriter",
    "norwegian country",
    "rogaland musikk",
    "classic finnish rock",
    "albany ny indie",
    "baltic folk",
    "estonian folk",
    "estonian indie",
    "lexington ky indie",
    "deathgrass",
    "throat singing",
    "chalga",
    "atmospheric doom",
    "blackgaze",
    "cascadian black metal",
    "portland metal",
    "polish punk",
    "folk brasileiro",
    "griot",
    "kora",
    "world fusion",
    "euroska",
    "ska",
    "ska revival",
    "deep progressive rock",
    "latin jazz",
    "musica tradicional cubana",
    "musica de fondo",
    "lancaster pa indie",
    "pittsburgh indie",
    "hungarian metal",
    "brno indie",
    "czech indie",
    "trad quebecois",
    "australian children's music",
    "nz folk",
    "hungarian folk",
    "modern dream pop",
    "armenian folk",
    "contemporary jazz",
    "modern jazz piano",
    "finnish jazz",
    "oslo indie",
    "atlanta indie",
    "ukrainian black metal",
    "czech pop",
    "vancouver punk",
    "argentine indie",
    "electronica argentina",
    "experimental pop",
    "pop folk",
    "brazilian metal",
    "folk metal latinoamericano",
    "metal mineiro",
    "indie quebecois",
    "deep folk metal",
    "icelandic metal",
    "icelandic punk",
    "russian folk",
    "scottish smallpipe",
    "contra dance",
    "dunedin indie",
    "isle of man indie",
    "mongolian folk",
    "new england experimental",
    "modern indie folk",
    "victoria bc indie",
    "musica popular uruguaya",
    "eastern bloc groove",
    "modern hard rock",
    "ny roots",
    "instrumental stoner rock",
    "swedish stoner rock",
    "columbus ohio indie",
    "kayokyoku",
    "bristol indie",
    "faroese rock",
    "musica lombarda",
    "xhosa",
    "mundart",
    "omaha indie",
    "southern americana",
    "middle earth",
    "turkish alternative",
    "turkish metal",
    "auckland indie",
    "variete francaise",
    "electro jazz",
    "abstract hip hop",
    "new tribe",
    "canadian contemporary country",
    "african rock",
    "arab metal",
    "maghreb metal",
    "tunisian alternative",
    "plugg",
    "pluggnb",
    "rage rap",
    "jazz drums",
    "swiss jazz",
    "ceilidh",
    "memphis indie",
    "malagasy folk",
    "crossover prog",
    "norwegian americana",
    "modern blues rock",
    "esperanto",
    "norwegian singer-songwriter",
    "indiecoustica",
    "finnish progressive rock",
    "minneapolis indie",
    "liverpool indie",
    "classic psychedelic rock",
    "icelandic black metal",
    "finnish hip hop",
    "nova mpb",
    "pop nacional",
    "friese muziek",
    "streektaal",
    "musique acadienne",
    "chicago indie",
    "popgaze",
    "israeli singer-songwriter",
    "belarusian metal",
    "alternative pop",
    "irish gaelic folk",
    "southern rock",
    "portuguese indie",
    "irish rebel song",
    "volksmusik",
    "baltic black metal",
    "latvian folk",
    "latvian metal",
    "deathrock",
    "czech metal",
    "shamanic",
    "indie catala",
    "norwegian folk",
    "belly dance",
    "persian alternative",
    "quebec indie",
    "chilean indie",
    "indie surf",
    "newfoundland indie",
    "canadian indigenous music",
    "gaming edm",
    "pop edm",
    "ukrainian metal",
    "middle eastern black metal",
    "experimental techno",
    "inuit pop",
    "avant-garde metal",
    "balkan folk metal",
    "romanian black metal",
    "romanian metal",
    "danish black metal",
    "danish metal",
    "post-black metal",
    "egyptian traditional",
    "nubian traditional",
    "oud",
    "escape room",
    "rebel blues",
    "old west",
    "gypsy jazz",
    "austrian indie",
    "euskal metal",
    "irish indie",
    "freestyle",
    "hi-nrg",
    "minneapolis sound",
    "post-disco",
    "new orleans americana",
    "german indie",
    "red dirt",
    "japanese blues",
    "japanese folk",
    "panamanian pop",
    "riot grrrl",
    "argentine telepop",
    "alternative r&b",
    "indie soul",
    "hawaiian",
    "desi pop",
    "modern bollywood",
    "nz indie",
    "wellington indie",
    "japanese death metal",
    "deep new americana",
    "lithuanian folk",
    "vietnamese bolero",
    "montreal indie",
    "rwandan pop",
    "rwandan traditional",
    "finnish power metal",
    "mongolian alternative",
    "instrumental acoustic guitar",
    "faroese folk",
    "canadian indie rock",
    "queercore",
    "cymraeg",
    "canadian metal",
    "glam metal",
    "melodic hard rock",
    "ok indie",
    "country quebecois",
    "danish pop",
    "danish singer-songwriter",
    "neue deutsche todeskunst",
    "modern alternative pop",
    "turkish pop",
    "la pop",
    "macedonian folk",
    "high vibe",
    "berlin school",
    "chinderlieder",
    "indie triste",
    "hardingfele",
    "arkansas country",
    "dreamgaze",
    "indie fuzzpop",
    "swedish ebm",
    "swedish synth",
    "polish hip hop",
    "chinese black metal",
    "washboard",
    "rochester mn indie",
    "indian folk",
    "indie veneto",
    "italian ska",
    "ska espanol",
    "sydney indie",
    "electroacoustic improvisation",
    "traditional blues",
    "pixie",
    "corrosion",
    "country rap",
    "taiwan metal",
    "nuevo folklore argentino",
    "french reggae",
    "danish folk",
    "no wave",
    "post-punk",
    "harsh noise wall",
    "australian ambient",
    "australian experimental",
    "metal catala",
    "salsa international",
    "normal indie",
    "beatboxing",
    "dutch punk",
    "transpop",
    "ambient post-rock",
    "russian post-rock",
    "romanian rock",
    "dance rock",
    "madchester",
    "dusseldorf indie",
    "chill abstract hip hop",
    "classic romanian pop",
    "romanian pop",
    "quebec punk",
    "gen z singer-songwriter",
    "experimental indie",
    "acoustic guitar cover",
    "taiwan instrumental",
    "native american black metal",
    "native american metal",
    "west virginia metal",
    "pink noise",
    "polish folk",
    "didgeridoo",
    "rock en asturiano",
    "spanish punk",
    "luxembourgian hip hop",
    "turkish alt pop",
    "euskal musica",
    "denver metal",
    "melodic doom",
    "cape town indie",
    "boston indie",
    "hindi indie",
    "indian indie",
    "indian singer-songwriter",
    "alabama indie",
    "italo disco",
    "nwobhm",
    "bangla pop",
    "classic bangla pop",
    "russian hip hop",
    "russian trap",
    "rock progressif francais",
    "lithuanian rock",
    "zhenskiy rep",
    "wisconsin indie",
    "reggae catala",
    "tavern",
    "finnish black metal",
    "finnish doom metal",
    "nice indie",
    "geek rock",
    "german blues",
    "crack rock steady",
    "siberian folk",
    "trip hop",
    "latintronica",
    "dutch r&b",
    "canadian shoegaze",
    "bahai",
    "british black metal",
    "chinese metalcore",
    "taiwan pop",
    "alaska indie",
    "alaska roots",
    "swedish progressive metal",
    "christchurch indie",
    "dunedin sound",
    "indonesian folk",
    "indonesian indie",
    "indonesian indie pop",
    "israeli pop",
    "italian blues",
    "uk alternative pop",
    "indie jazz",
    "modern chamber music",
    "knoxville indie",
    "granada indie",
    "spanish noise pop",
    "swiss alternative rock",
    "swiss indie",
    "canadian psychedelic rock",
    "psych gaze",
    "girl group",
    "classic disco polo",
    "goralski",
    "koledy",
    "nueva ola peruana",
    "peruvian rock",
    "musica rondoniense",
    "british country",
    "american early music",
    "strut",
    "sheffield indie",
    "classic hardstyle",
    "euphoric hardstyle",
    "rawstyle",
    "post-doom metal",
    "uk doom metal",
    "indonesian pop",
    "spanish new wave",
    "one-person band",
    "animal singing",
    "indie asturiana",
    "georgian folk",
    "georgian pop",
    "kansas indie",
    "cincinnati indie",
    "italian black metal",
    "spanish folk rock",
    "p funk",
    "faroese pop",
    "classical oboe",
    "medieval",
    "indie viet",
    "fantasy synth",
    "chinese singer-songwriter",
    "canadian psychedelic",
    "psychedelic folk rock",
    "ukrainian experimental",
    "ukrainian folk rock",
    "ukrainian indie",
    "bhajan",
    "hindustani classical",
    "hindustani vocal",
    "indian classical",
    "khayal",
    "jamaican dancehall",
    "new england black metal",
    "new england metal",
    "early american folk",
    "muzica ardeleneasca",
    "muzica banateana",
    "makossa",
    "malaysian pop",
    "ghent indie",
    "oxford indie",
    "swiss singer-songwriter",
    "serbian metal",
    "manitoba country",
    "trekkspill",
    "rock alternatif francais",
    "punjabi folk",
    "classic bulgarian pop",
    "chabad niggunim",
    "movie tunes",
    "uk post-metal",
    "cork indie",
    "german dnb",
    "neurofunk",
    "neurostep",
    "muzica moldoveneasca",
    "psychedelic soul",
    "czech punk",
    "musica etnica",
    "underground power pop",
    "cowpunk",
    "swiss experimental",
    "west end",
    "stutter house",
    "garage pop",
    "indie garage rock",
    "channel pop",
    "lebanese indie",
    "metal galego",
    "spanish black metal",
    "stomp and whittle",
    "polish black metal",
    "milan indie",
    "seattle indie",
    "folclore extremeno",
    "epic black metal",
    "swiss black metal",
    "danish death metal",
    "cumbia pop",
    "slayer",
    "kentucky roots",
    "pittsburgh indie rock",
    "persian pop",
    "persian traditional",
    "psychedelic doom",
    "stoner metal",
    "stoner rock",
    "gypsy fusion",
    "american modern classical",
    "avant-garde",
    "deep free jazz",
    "hip hop quebecois",
    "nyc pop",
    "underground grunge",
    "hauntology",
    "german indie folk",
    "french folk pop",
    "gypsy",
    "progressive deathcore",
    "malagasy pop",
    "maltese pop",
    "j-acoustic",
    "japanese alternative rock",
    "japanese indie folk",
    "chattanooga indie",
    "classic bollywood",
    "multidisciplinary",
    "chihuahua indie",
    "mexican indie",
    "mexican rock",
    "classic ukrainian pop",
    "ukrainian folk pop",
    "uk reggae",
    "firenze indie",
    "nwothm",
    "london rap",
    "uk drill",
    "glam punk",
    "pakistani indie",
    "polka nortena",
    "london on indie",
    "albuquerque indie",
    "retro metal",
    "tatar folk",
    "tatar pop",
    "swedish folk pop",
    "indonesian folk pop",
    "manchester indie",
    "thai folk",
    "austrian metal",
    "symphonic power metal",
    "belarusian rock",
    "hong kong indie",
    "hong kong rock",
    "uk diy punk",
    "anthem emo",
    "baltic post-punk",
    "lithuanian electronic",
    "swiss indie folk",
    "swazi pop",
    "traprun",
    "deutschrock",
    "pixel",
    "san antonio indie",
    "grupera",
    "gruperas inmortales",
    "musica mexicana",
    "norteno",
    "bergamo indie",
    "derry indie",
    "slaskie piosenki",
    "emo rap",
    "sacramento hip hop",
    "croatian metal",
    "croatian rock",
    "bhangra",
    "emotional black metal",
    "american shoegaze",
    "fast melodic punk",
    "argentine metal",
    "deep german punk",
    "indian metal",
    "ethnotronica",
    "greek indie rock",
    "stuttgart indie",
    "southern soul",
    "montenegrin pop",
    "pinoy indie",
    "southeast asian post-rock",
    "east coast hip hop",
    "queens hip hop",
    "psychedelic pop",
    "boston rock",
    "country road",
    "cypriot pop",
    "afrofuturism",
    "experimental r&b",
    "ska argentino",
    "idol",
    "aarhus indie",
    "fallen angel",
    "basel indie",
    "norwegian doom metal",
    "australian house",
    "progressive black metal",
    "vintage french psychedelic",
    "cardiff indie",
    "sadcore",
    "northern irish indie",
    "retro soul",
    "dresden indie",
    "german hard rock",
    "german stoner rock",
    "avant-garde black metal",
    "lithuanian metal",
    "swedish psychedelic rock",
    "galway indie",
    "indie rock mexicano",
    "melodipop",
    "burmese pop",
    "conscious hip hop",
    "classic anime",
    "dungeon synth",
    "irish ballad",
    "ukrainian jazz",
    "bhojpuri folk",
    "bhojpuri pop",
    "maithili",
    "moldovan pop",
    "roots americana",
    "hip pop",
    "progressive jazz fusion",
    "danspunk",
    "corrido",
    "corridos alternativos",
    "sierreno",
    "svensk indie",
    "belgian metal",
    "cologne indie",
    "indonesian jazz",
    "classic korean pop",
    "melodic thrash",
    "5th wave emo",
    "bosstown sound",
    "alt-idol",
    "argentine alternative rock",
    "vintage radio show",
    "crank wave",
    "tin pan alley",
    "nurnberg indie",
    "jaw harp",
    "dutch blues",
    "gothic post-punk",
    "czsk black metal",
    "slovak metal",
    "chinese indie rock",
    "rajasthani pop",
    "kenyan alternative",
    "arkansas indie",
    "instrumental hip hop",
    "uk post-hardcore",
    "ukhc",
    "rva indie",
    "muzica etno",
    "spanish psychedelic rock",
    "classic nz country",
    "south african punk",
    "musica gaucha tradicionalista",
    "fort wayne indie",
    "old school dancehall",
    "british indie rock",
    "dance-punk",
    "new rave",
    "new italo disco",
    "turkish instrumental",
    "indie psychedelic rock",
    "worcester ma indie",
    "polish indie",
    "ambient industrial",
    "dub metal",
    "r&drill",
    "uk contemporary r&b",
    "kaseko",
    "greek shoegaze",
    "ukrainian hip hop",
    "ukrainian pop",
    "ukrainian viral pop",
    "ambient psychill",
    "psychill",
    "belfast indie",
    "symphonic death metal",
    "musica calabrese",
    "indie rock peruano",
    "peruvian indie",
    "classic dutch pop",
    "bulgarian folk",
    "spanish modern rock",
    "experimental ambient",
    "bossbeat",
    "post-disco soul",
    "barbershop",
    "indie platense",
    "modern mod",
    "trash rock",
    "croatian pop",
    "nepali indie",
    "balochi folk",
    "rock viet",
    "liquid funk",
    "luxembourgian indie",
    "cavernous death metal",
    "hungarian rock",
    "magyar alternative",
    "kolo",
    "swedish black metal",
    "indie r&b",
    "brazilian indie rock",
    "rock goiano",
    "hampton roads indie",
    "indie rock italiano",
    "ukrainian rock",
    "kazakh viral pop",
    "korean singer-songwriter",
    "tuvan folk",
    "isle of wight indie",
    "ambient pop",
    "minneapolis punk",
    "pittsburgh rock",
    "traditional irish singing",
    "medieval black metal",
    "buffalo ny indie",
    "austin metal",
    "diy emo",
    "boston metal",
    "aussietronica",
    "tempe indie",
    "glasgow indie",
    "australian indie rock",
    "danseband",
    "brazilian power metal",
    "metal gaucho",
    "manele",
    "kenyan r&b",
    "african metal",
    "midwest emo",
    "instrumental black metal",
    "k-indie",
    "musique pour enfant quebecois",
    "minnesota metal",
    "alberta country",
    "microtonal",
    "greek metal",
    "neo-trad metal",
    "malaysian indie",
    "experimental jazz",
    "bath indie",
    "lithuanian pop",
    "progressive alternative",
    "cumbia ecuatoriana",
    "electric bass",
    "jazz fusion",
    "cdmx indie",
    "psicodelia mexicana",
    "faroese indie",
    "azeri pop",
    "black metal argentino",
    "newcastle nsw indie",
    "indie folk argentino",
    "spiritual jazz",
    "umea indie",
    "east anglia indie",
    "melodic house",
    "manso indie",
    "math pop",
    "chinese manyao",
    "israeli punk",
    "musica costarricense",
    "folclore santiagueno",
    "uk contemporary jazz",
    "musiqi-ye zanan",
    "austrian black metal",
    "concepcion indie",
    "hoerspiel",
    "pansori",
    "emoplugg",
    "glitchcore",
    "indie cordoba",
    "contemporary country",
    "country pop",
    "brazilian jazz",
    "neo-kraut",
    "poznan indie",
    "swedish doom metal",
    "dutch black metal",
    "palestinian pop",
    "scottish indie rock",
    "synth prog",
    "missouri indie",
    "indie folk italiano",
    "taiwan post-rock",
    "scottish jazz",
    "malayalam indie",
    "greek rock",
    "progressive doom",
    "sludge metal",
    "gauze pop",
    "workout product",
    "guitarra andina",
    "huayno",
    "musica ayacuchana",
    "asheville indie",
    "indonesian punk",
    "psychedelic jazz fusion",
    "q-pop",
    "melodic techno",
    "greek psychedelic rock",
    "north east england indie",
    "polish blues",
    "psychedelic trance",
    "indie pop rock",
    "belgian hip hop",
    "lo-fi chill",
    "death doom",
    "zimdancehall",
    "detskie rasskazy",
    "american post-punk",
    "austrian punk",
    "indonesian pop rock",
    "italian hip hop",
    "italian pop",
    "bern indie",
    "bulgarian rock",
    "german singer-songwriter",
    "belarusian indie",
    "black thrash",
    "scottish techno",
    "french black metal",
    "lancashire indie",
    "ambient black metal",
    "german black metal",
    "belgian punk",
    "dutch punk rock",
    "pinoy rock",
    "candombe",
    "miami indie",
    "lute",
    "sound art",
    "halifax indie",
    "pibroch",
    "melodic black metal",
    "progressive power metal",
    "spanish progressive rock",
    "guadalajara indie",
    "polish electronica",
    "graz indie",
    "rap francais",
    "russian dance pop",
    "aggrotech",
    "cyberpunk",
    "ebm",
    "futurepop",
    "industrial metal",
    "nepali pop",
    "musica canaria",
    "jazz vibraphone",
    "musique nigerienne",
    "rap guineen",
    "canadian black metal",
    "minneapolis metal",
    "aberdeen indie",
    "myanmar indie",
    "channel islands indie",
    "connecticut indie",
    "raw black metal",
    "german hip hop",
    "albanian pop",
    "electro-industrial",
    "new beat",
    "r&b brasileiro",
    "experimental hip hop",
    "jazz rap",
    "south african electronic",
    "birmingham indie",
    "lo-fi vgm",
    "italogaze",
    "american post-rock",
    "neo r&b",
    "greek underground rap",
    "christlicher rap",
    "classic russian pop",
    "soviet synthpop",
    "rock kapak",
    "musica piauiense",
    "mongolian pop",
    "limerick indie",
    "nu age",
    "organic ambient",
    "belo horizonte indie",
    "brazilian emo",
    "modern darkwave",
    "brisbane indie",
    "greek indie",
    "irish indie rock",
    "phleng phuea chiwit",
    "belgian dnb",
    "canadian ccm",
    "bangladeshi indie",
    "african shoegaze",
    "malmo indie",
    "mississippi indie",
    "persian neo-traditional",
    "mumbai indie",
    "dansband",
    "c64",
    "demoscene",
    "edinburgh metal",
    "mexican metal",
    "mexican power metal",
    "trap dominicano",
    "trap latino",
    "bolivian metal",
    "singaporean singer-songwriter",
    "austin rock",
    "electro swing",
    "vlaamse rap",
    "slowed and reverb",
    "indie salvadoreno",
    "new romantic",
    "new wave",
    "sophisti-pop",
    "classic praise",
    "epicore",
    "chant religieux",
    "baroque ensemble",
    "british orchestra",
    "classical performance",
    "historically informed performance",
    "scorecore",
    "theme",
    "otacore",
    "melodic hardcore",
    "ambient worship",
    "japanese vgm",
    "lo-fi cover",
    "lo-fi product",
    "barockinterpreten",
    "disco house",
    "vocal house",
    "messianic praise",
    "tagalog worship",
    "sound team",
    "uk experimental electronic",
    "christian a cappella",
    "sda a cappella",
    "british electroacoustic",
    "british soundtrack",
    "classify",
    "touhou",
    "music box",
    "vgm instrumental",
    "big beat",
    "indie pop rap",
    "underground rap",
    "chiptune",
    "darksynth",
    "elephant 6",
    "future bass",
    "vapor twitch",
    "austrian orchestra",
    "sped up",
    "german dance",
    "slap house",
    "experimental dub",
    "spanish electropop",
    "anime rap",
    "instrumental djent",
    "sleep",
    "spa",
    "early synthpop",
    "french post-punk",
    "french synthpop",
    "free improvisation",
    "japanese new wave",
    "abstract",
    "ambient techno",
    "drill and bass",
    "glitch",
    "intelligent dance music",
    "danish electro",
    "power noise",
    "rap inde",
    "nursery",
    "preschool children's music",
    "dfw rap",
    "dirty south rap",
    "singeli",
    "japanese beats",
    "modern ebm",
    "british dance band",
    "vaudeville",
    "vintage jazz",
    "uk house",
    "christian pop",
    "deep house",
    "background music",
    "dinner jazz",
    "chamber orchestra",
    "italian orchestra",
    "string orchestra",
    "k-rap",
    "korean underground rap",
    "musique traditionnelle congolaise",
    "glitch pop",
    "filter house",
    "desi hip hop",
    "indian edm",
    "german worship",
    "anthem worship",
    "pop worship",
    "p-pop",
    "meme",
    "sillycore",
    "therapy",
    "eurodance",
    "czech hip hop",
    "czsk hip hop",
    "deep italo disco",
    "christian afrobeat",
    "jazztronica",
    "proto-hyperpop",
    "australian hip hop",
    "brisbane hip hop",
    "south sudanese pop",
    "soca",
    "uk garage",
    "elektropunk",
    "nerdcore",
    "rhythm game",
    "gym phonk",
    "mexican hip hop",
    "rap regio",
    "trap mexicano",
    "hip house",
    "synthpop",
    "tanzanian pop",
    "sgija",
    "punjabi hip hop",
    "electro latino",
    "modern bhajan",
    "waiata maori",
    "pop reggaeton",
    "urbano latino",
    "pet calming",
    "bajan soca",
    "russian pixel",
    "super eurobeat",
    "italian industrial",
    "italian new wave",
    "noise",
    "indie game soundtrack",
    "rap marseille",
    "kodomo no ongaku",
    "early music ensemble",
    "honky tonk",
    "rare groove",
    "musique ancienne",
    "recorder",
    "italian trance",
    "italo dance",
    "healing",
    "canadian experimental",
    "indie electronica",
    "vbs",
    "game mood",
    "atlanta punk",
    "j-indie",
    "japanese r&b",
    "deep space rock",
    "city pop",
    "metal cover",
    "wrestling",
    "anglican liturgy",
    "british contemporary classical",
    "choral",
    "chinese soundtrack",
    "deep new wave",
    "midwest shoegaze",
    "zoomergaze",
    "finnish pop punk",
    "finnish punk",
    "power-pop punk",
    "german oi",
    "german punk",
    "german street punk",
    "new wave of glam metal",
    "phoenix indie",
    "socal indie",
    "destroy techno",
    "french techno",
    "belgian indie",
    "english renaissance",
    "ecuadorian alternative rock",
    "ecuadorian indie",
    "polish psychedelia",
    "santa fe indie",
    "college a cappella",
    "czech hardcore",
    "corridos tumbados",
    "french hip hop",
    "pop urbaine",
    "r&b francais",
    "ohio hardcore",
    "cascadia shoegaze",
    "christian trap",
    "east coast reggae",
    "monterrey indie",
    "english indie rock",
    "deep discofox",
    "discofox",
    "partyschlager",
    "greek hip hop",
    "taiwan indie",
    "deep disco",
    "teen pop",
    "louisville indie",
    "symphonic deathcore",
    "indorock",
    "polish noise rock",
    "indonesian post-punk",
    "latin american heavy psych",
    "stl indie",
    "hyper-rock",
    "j-core",
    "austrian stoner rock",
    "quebec hardcore",
    "atmospheric post-metal",
    "huzunlu sarkilar",
    "classic israeli pop",
    "instrumental surf",
    "rap conciencia",
    "mandible",
    "thai indie",
    "thai indie rock",
    "funeral doom",
    "neo-rockabilly",
    "japanese instrumental",
    "brazilian post-rock",
    "australian psych",
    "dutch rap pop",
    "deep melodic metalcore",
    "gospel rap",
    "balkan hip hop",
    "balkan trap",
    "serbian hip hop",
    "desi emo rap",
    "desi trap",
    "swedish hard rock",
    "new wave of screamo",
    "screamo",
    "skramz",
    "chinese experimental",
    "canadian rockabilly",
    "guatemalan indie",
    "american oi",
    "australian garage punk",
    "boy band",
    "new orleans jazz",
    "classic soul",
    "souldies",
    "traditional soul",
    "gangster rap",
    "hardcore hip hop",
    "goregrind",
    "pornogrind",
    "grim death metal",
    "mathcore",
    "powerviolence",
    "technical grindcore",
    "cleveland indie",
    "arab electronic",
    "organic electronic",
    "gabber",
    "progressive breaks",
    "argentine punk",
    "xtra raw",
    "deep classic garage rock",
    "uk stoner rock",
    "caribbean metal",
    "puerto rican indie",
    "puerto rican metal",
    "italian punk",
    "punk rock italiano",
    "diva house",
    "happy hardcore",
    "bass house",
    "old school bassline",
    "uk funky",
    "coverchill",
    "dutch stoner rock",
    "drum and bass",
    "jungle",
    "polish post-rock",
    "makina",
    "australian post-hardcore",
    "modern melodic hardcore",
    "gambian pop",
    "indie emo",
    "nu disco",
    "punk 'n' roll",
    "brazilian gospel",
    "rock gospel brasileiro",
    "early us punk",
    "french rockabilly",
    "motown",
    "philly soul",
    "quiet storm",
    "ambient lo-fi",
    "colombian pop",
    "italian stoner rock",
    "rap algerien",
    "northern soul",
    "future ambient",
    "classic japanese jazz",
    "japanese jazz fusion",
    "mizo pop",
    "northeast indian indie",
    "milwaukee indie",
    "swiss hip hop",
    "southampton indie",
    "emo punk",
    "emocore",
    "reggaeton chileno",
    "german ska",
    "muzica crestina",
    "speed metal",
    "russian ska",
    "shoegaze brasileiro",
    "swansea indie",
    "indonesian emo",
    "spacewave",
    "synthwave",
    "technical thrash",
    "microhouse",
    "german ccm",
    "rez country",
    "canadian contemporary r&b",
    "dark r&b",
    "trap soul",
    "nyc indie rock",
    "brazilian stoner rock",
    "beach music",
    "northern irish punk",
    "post-rock latinoamericano",
    "trap brasileiro",
    "punk cover",
    "swedish gangsta rap",
    "swedish hip hop",
    "swedish trap pop",
    "rock alternativo espanol",
    "hard rock brasileiro",
    "rap metalcore",
    "southern gospel",
    "full on",
    "progressive psytrance",
    "shoegaze chileno",
    "rautalanka",
    "bangladeshi rock",
    "proto-metal",
    "pub rock",
    "deep soul house",
    "chicago soul",
    "indonesian alternative rock",
    "paraguayan rock",
    "brazilian punk rock",
    "rock curitibano",
    "belgian dance",
    "indie liguria",
    "italian emo",
    "uk dnb",
    "hard house",
    "nordic shoegaze",
    "rap belge",
    "cubaton",
    "australian surf rock",
    "trap italiana",
    "south african pop",
    "korean indie rock",
    "korean shoegaze",
    "hindi hip hop",
    "shatta",
    "cumbia peruana",
    "australian metal",
    "old school rap francais",
    "t-pop",
    "thai rock",
    "hardgroove",
    "bengali metal",
    "bc underground hip hop",
    "canadian underground hip hop",
    "goa psytrance",
    "goa trance",
    "thall",
    "cinematic post-rock",
    "funk",
    "korean r&b",
    "musica quintanarroense",
    "uk noise rock",
    "pop lgbtq+ brasileira",
    "pop teen brasileiro",
    "deep pop edm",
    "nu gaze",
    "nwocr",
    "swedish melodic rock",
    "jazz house",
    "orlando indie",
    "moombahton",
    "nigerian pop",
    "electronic trap",
    "vapor soul",
    "rhythm and blues",
    "derby indie",
    "electropop",
    "indie poptimism",
    "dark clubbing",
    "deep northern soul",
    "twee pop",
    "bubble trance",
    "german techno",
    "hardcore techno",
    "battle rap",
    "deep german hip hop",
    "dark rock",
    "alternative hip hop",
    "g funk",
    "deep psychobilly",
    "classic j-pop",
    "dutch post-punk",
    "darkstep",
    "nz dnb",
    "nz electronic",
    "malaysian hip hop",
    "jazz funk",
    "kannada hip hop",
    "canadian house",
    "metallic hardcore",
    "bulgarian metal",
    "diy pop punk",
    "chinese electronic",
    "idol game",
    "la hardcore",
    "denver indie",
    "mod revival",
    "chill lounge",
    "chillsynth",
    "jazz double bass",
    "oeteldonk",
    "scottish electronic",
    "neo-psicodelia brasileira",
    "rock mineiro",
    "electronica chilena",
    "italian alternative",
    "italian indie pop",
    "maimouna",
    "chill dream pop",
    "hopebeat",
    "portsmouth indie",
    "dc indie",
    "christian punk",
    "urbano ecuatoriano",
    "cali rap",
    "pop argentino",
    "hamburg hip hop",
    "indonesian neo-psychedelia",
    "nederlandse hardstyle",
    "new england emo",
    "jump up",
    "grunge argentina",
    "musica baiana",
    "melodic progressive metal",
    "chilean hardcore",
    "punk chileno",
    "punk melodico chileno",
    "colorado hardcore",
    "british math rock",
    "new jack smooth",
    "visual kei",
    "dark post-punk",
    "swedish melodeath",
    "dancefloor dnb",
    "belgian stoner rock",
    "thai indie pop",
    "west australian hip hop",
    "neo-shibuya-kei",
    "shibuya-kei",
    "long island punk",
    "polish shoegaze",
    "lo-fi house",
    "dutch shoegaze",
    "new england hardcore",
    "syrian hip hop",
    "lo-fi jazzhop",
    "filthstep",
    "shoegaze peruano",
    "greek pop",
    "laiko",
    "christelijk",
    "carnatic",
    "mantra",
    "peruvian metal",
    "arkansas metal",
    "italian gothic",
    "deep eurodance",
    "lo-fi beats",
    "christian lo-fi",
    "edinburgh indie",
    "memphis soul",
    "modern noise rock",
    "german heavy metal",
    "new wave of speed metal",
    "new orleans funk",
    "swedish rock-and-roll",
    "nottingham hip hop",
    "atl hip hop",
    "memphis hip hop",
    "trap",
    "brasilia indie",
    "surf punk",
    "indonesian rock",
    "brit funk",
    "dublin indie",
    "deep turkish pop",
    "indonesian lo-fi pop",
    "brazilian hip hop",
    "pinoy alternative rock",
    "tijuana electronic",
    "nz post-punk",
    "afghan rap",
    "classic dubstep",
    "brisbane punk",
    "south african hip hop",
    "azonto",
    "hiplife",
    "romanian rap",
    "modern southern rock",
    "slovak pop",
    "slovak punk",
    "slovak rock",
    "rap nacional antigo",
    "classic progressive house",
    "world chill",
    "blackened hardcore",
    "phonk",
    "australian thrash metal",
    "drikkelek",
    "russelater",
    "garage rock revival",
    "reading indie",
    "uk dance",
    "lovecraftian metal",
    "indian jazz",
    "classic girl group",
    "seattle hip hop",
    "classic greek pop",
    "harlem hip hop",
    "southern hip hop",
    "jamaican ska",
    "arab groove",
    "soda pop",
    "kc indie",
    "hamburg electronic",
    "ethereal gothic",
    "korean superband",
    "oldschool deutschrap",
    "indian rock",
    "new delhi indie",
    "hardtekk",
    "tekk",
    "quebec metal",
    "rocksteady",
    "ukrainian metalcore",
    "black speed metal",
    "fremantle indie",
    "lowlands hardcore",
    "norwegian hardcore",
    "hip-hop experimental",
    "britpop revival",
    "birmingham grime",
    "birmingham hip hop",
    "uk hip hop",
    "uk82",
    "oi",
    "skinhead oi",
    "california hardcore",
    "classical baritone",
    "jazz saxophone",
    "straight-ahead jazz",
    "german trap",
    "warrington indie",
    "funky breaks",
    "bounce",
    "ukg revival",
    "bassline",
    "japanese emo",
    "australian r&b",
    "korean city pop",
    "mollywood",
    "electroclash",
    "synth punk",
    "chillstep",
    "indonesian death metal",
    "nz jazz",
    "tulsa indie",
    "swedish heavy metal",
    "popping",
    "synth funk",
    "comedy",
    "deep comedy",
    "viral afropop",
    "norwegian death metal",
    "riddim dubstep",
    "spacegrunge",
    "boston hip hop",
    "german hyperpop",
    "post-screamo",
    "italian progressive metal",
    "german death metal",
    "italian heavy metal",
    "classic k-pop",
    "belgian death metal",
    "disco polo",
    "christian metal",
    "metal tico",
    "technical melodic death metal",
    "occult black metal",
    "alabama metal",
    "atlanta metal",
    "arabic instrumental",
    "social media pop",
    "brutal deathcore",
    "deathcore",
    "bedroom r&b",
    "swedish death metal",
    "blackened crust",
    "neo metal",
    "saxony metal",
    "thai metal",
    "thai pop",
    "old school thrash",
    "german thrash metal",
    "finnish death metal",
    "bristol electronic",
    "drumfunk",
    "minimal dnb",
    "dutch death metal",
    "christian death metal",
    "south carolina metal",
    "beatdown",
    "j-metal",
    "horrorcore",
    "french movie tunes",
    "utah metal",
    "full on groove",
    "latincore",
    "trancecore",
    "polish viral pop",
    "polish viral rap",
    "finnish heavy metal",
    "south african metal",
    "oulu metal",
    "russian death metal",
    "technical brutal death metal",
    "neo-crust",
    "french death metal",
    "canadian hip hop",
    "hip hop",
    "pop rap",
    "rap",
    "chicano rap",
    "australian black metal",
    "symphonic melodic death metal",
    "rusyn folk",
    "brutal death metal",
    "slam death metal",
    "crust punk",
    "stenchcore",
    "rap antillais",
    "trap antillais",
    "zouk riddim",
    "acid techno",
    "progressive metalcore",
    "portuguese post-rock",
    "chain punk",
    "us power metal",
    "central american metal",
    "rock catracho",
    "frenchcore",
    "sigilkore",
    "melodic deathcore",
    "brazilian black metal",
    "brazilian death metal",
    "gothenburg metal",
    "gothic black metal",
    "deathrash",
    "chicago hardcore",
    "australian metalcore",
    "brazilian edm",
    "turkish punk",
    "gothenburg hip hop",
    "swedish drill",
    "swedish trap",
    "portuguese metal",
    "polish death metal",
    "vampiric black metal",
    "slovenian metal",
    "pinoy hip hop",
    "tagalog rap",
    "deathgrind",
    "greek black metal",
    "ecuadorian pop",
    "new wave of thrash metal",
    "black death",
    "metal uruguayo",
    "downtempo bass",
    "experimental bass",
    "glitch hop",
    "metal baiano",
    "metal colombiano",
    "thrash metal",
    "brazilian heavy metal",
    "virginia metal",
    "chilean black metal",
    "metal nortista",
    "street punk",
    "mexican edm",
    "trance mexicano",
    "neo-trad doom metal",
    "quebec death metal",
    "dark electro",
    "deep neo-synthpop",
    "power electronics",
    "swedish experimental",
    "spanish death metal",
    "german grindcore",
    "necrogrind",
    "progressive death metal",
    "progressive technical death metal",
    "technical death metal",
    "christian hardcore",
    "rabm",
    "uptempo hardcore",
    "rap metal espanol",
    "cyber metal",
    "industrial black metal",
    "brazilian thrash metal",
    "danish post-punk",
    "italian metalcore",
    "swedish thrash metal",
    "russian power metal",
    "dutch dnb",
    "maltese metal",
    "mizrahi",
    "drill brasileiro",
    "trinibad",
    "melodic groove metal",
    "covertronica",
    "hypertechno",
    "seattle metal",
    "progressive groove metal",
    "belfast metal",
    "grisly death metal",
    "swedish grindcore",
    "psychedelic blues-rock",
    "canadian death metal",
    "french metal",
    "russian pop",
    "chilean metal",
    "unblack metal",
    "tennessee metal",
    "blackened deathcore",
    "texas death metal",
    "opera metal",
    "british death metal",
    "norwegian hip hop",
    "bouncy house",
    "deep happy hardcore",
    "freeform hardcore",
    "indonesian indie rock",
    "lombok indie",
    "finnish post-punk",
    "australian hardcore",
    "pop emo",
    "polish reggae",
    "pop violin",
    "bleakgaze",
    "ballroom",
    "organic house",
    "italo beats",
    "american contemporary classical",
    "tzadik",
    "vapor pop",
    "japanese teen pop",
    "deep freestyle",
    "ryukyu ongaku",
    "ghanaian pop",
    "chaotic hardcore",
    "rally house",
    "pinoy idol pop",
    "musica mallorquina",
    "drill francais",
    "rap calme",
    "rap francais nouvelle vague",
    "chill house",
    "tropical house",
    "classic hungarian pop",
    "progressive post-hardcore",
    "swancore",
    "substep",
    "hard dance",
    "deep dnb",
    "deep liquid bass",
    "future garage",
    "uk bass",
    "slovak hip hop",
    "mappila paattu",
    "rap politico",
    "spanish hip hop",
    "irish post-punk",
    "central asian hip hop",
    "uzbek hip hop",
    "uzbek pop",
    "irish punk",
    "cumbia sonorense",
    "birmingham metal",
    "welsh hip hop",
    "atmospheric dnb",
    "horror punk",
    "j-pop girl group",
    "gym hardstyle",
    "jumpstyle",
    "jumptek",
    "art punk",
    "egg punk",
    "german tech house",
    "italian baroque ensemble",
    "yugoslav rock",
    "pop dance",
    "hyperpop",
    "chicago rap",
    "scenecore",
    "dutch trance",
    "deep vocal house",
    "crunk",
    "deep dubstep",
    "minimal dubstep",
    "sky room",
    "hands up",
    "cantaditas",
    "westcoast flow",
    "aesthetic rap",
    "bmore",
    "euro hi-nrg",
    "free jazz",
    "jazzcore",
    "sad rap",
    "nyc rap",
    "bulgarian hip hop",
    "finnish dance pop",
    "mexican pop punk",
    "adoracion pentecostal",
    "big band",
    "swing",
    "saxophone house",
    "west yorkshire indie",
    "corridos cristianos",
    "meme rap",
    "hungarian hip hop",
    "redneck",
    "electrofox",
    "funktronica",
    "hard rock",
    "romanian house",
    "greek trap",
    "modern country rock",
    "brazilian ccm",
    "reggaeton flow",
    "flamenco electronica",
    "chill guitar",
    "texasgaze",
    "krajiska muzika",
    "nintendocore",
    "sasscore",
    "tierra caliente",
    "techno rave",
    "karaoke",
    "latin worship",
    "boom bap brasileiro",
    "belgian hardcore",
    "h8000",
    "alternative metalcore",
    "belgian techno",
    "vintage french electronic",
    "complextro",
    "university choir",
    "bachata",
    "ragga jungle",
    "israeli hip hop",
    "kizomba antigas",
    "pinoy r&b",
    "bronx hip hop",
    "wu fam",
    "dutch house",
    "electro house",
    "commons",
    "light music",
    "russian experimental electronic",
    "russian techno",
    "bogor indie",
    "afro house",
    "medieval ensemble",
    "konkani pop",
    "tejano",
    "latin christian",
    "rap cristiano",
    "reggaeton cristiano",
    "hard trance",
    "drift",
    "indonesian worship",
    "magyar mulatos",
    "croatian indie",
    "png pop",
    "reunion pop",
    "albanian rock",
    "brazilian rock",
    "hard techno",
    "rap ivoire",
    "afrobeats",
    "nigerian hip hop",
    "brostep",
    "polish alternative rap",
    "handpan",
    "dakke dak",
    "norwegian house",
    "tribal house",
    "deep latin alternative",
    "indie hidrocalido",
    "rap montrealais",
    "deep full on",
    "suomisaundi",
    "glitch beats",
    "hardstyle",
    "modern performance",
    "space age pop",
    "2-step",
    "christian hip hop",
    "modern jazz trio",
    "tearout",
    "electropowerpop",
    "grime",
    "brega",
    "pop nacional antigas",
    "miami bass",
    "argentine heavy metal",
    "finlandssvenska musik",
    "rap sardegna",
    "new french touch",
    "puglia indie",
    "noise punk",
    "ambient synth",
    "grimewave",
    "cumbia surena",
    "huayno peruano",
    "huayno popular",
    "bboy",
    "brass band",
    "guided meditation",
    "kizomba",
    "musica angolana",
    "classic bhangra",
    "canadian indigenous hip hop",
    "ottawa rap",
    "german reggae",
    "south carolina hip hop",
    "grungegaze",
    "electro bailando",
    "praise",
    "belarusian electronic",
    "g-house",
    "fake",
    "dance pop",
    "japanese bedroom pop",
    "florida hardcore",
    "metal paraguayo",
    "a cappella",
    "ruta destroy",
    "carnaval",
    "arrocha",
    "brega paraense",
    "deep liquid",
    "australian comedy",
    "classic nepali pop",
    "classic city pop",
    "soul flow",
    "brazilian hardcore",
    "sandalwood",
    "naija worship",
    "cristiana para ninos",
    "russian dance",
    "tech house",
    "persian electronic",
    "alternative ccm",
    "old school ebm",
    "chicago pop punk",
    "easycore",
    "sinhala indie",
    "black punk",
    "new comedy",
    "magyar retro dance",
    "funky tech house",
    "cuarteto",
    "cumbia villera",
    "melodic dubstep",
    "kompa gouyad",
    "oshare kei",
    "haryanvi pop",
    "pop cristiano",
    "rap angolano",
    "t-pop boy group",
    "kawaii edm",
    "djent",
    "canadian metalcore",
    "russian alt pop",
    "deep soft rock",
    "swiss pop",
    "ukrainian punk",
    "singaporean punk",
    "tropical alternativo",
    "hmong pop",
    "d-beat",
    "swedish hardcore",
    "solipsynthm",
    "kazakh pop",
    "8d",
    "denver rap",
    "north carolina emo",
    "tontipop",
    "athens indie",
    "moderne ludovky",
    "slovak folk",
    "japanese pop punk",
    "zillertal",
    "cedm",
    "canadian electropop",
    "garage psych",
    "electro trash",
    "fidget house",
    "russian electronic",
    "french post-rock",
    "israeli rock",
    "chicago punk",
    "san diego indie",
    "copla",
    "math rock",
    "milwaukee hip hop",
    "danish indie pop",
    "afrikaans",
    "south african country",
    "modern jangle pop",
    "australian shoegaze",
    "swiss punk",
    "classic australian country",
    "italian pop punk",
    "leeds indie",
    "classic turkish pop",
    "cocuk masallari",
    "icelandic electronic",
    "modern goth",
    "uk pop punk",
    "go-go",
    "early french punk",
    "azeri rap",
    "swedish emo",
    "swedish post-hardcore",
    "modern ska punk",
    "indie dream pop",
    "hyperpop en espanol",
    "rome indie",
    "german indie pop",
    "new school turkce rap",
    "turkce drill",
    "turkish hip hop",
    "sevilla indie",
    "blackened screamo",
    "macedonian indie",
    "hamburg indie",
    "experimental house",
    "finnish metalcore",
    "austrian pop",
    "naija old school",
    "dancehall guyanaise",
    "t-pop girl group",
    "spanish shoegaze",
    "experimental electronic",
    "weightless",
    "vietnamese hip hop",
    "swiss reggae",
    "brazilian rockabilly",
    "norwegian punk rock",
    "indie tico",
    "post-punk mexicano",
    "afro r&b",
    "afro soul",
    "south african r&b",
    "writing",
    "industrial hip hop",
    "german viral rap",
    "pop house",
    "afghan pop",
    "bouyon",
    "balkan punk",
    "funk carioca",
    "lithuanian hip hop",
    "drumless hip hop",
    "detroit rock",
    "japanese hyperpop",
    "adelaide indie",
    "neo grime",
    "wave",
    "spanish pop rock",
    "tape music",
    "bulgarian electronic",
    "minimal wave",
    "norrbotten indie",
    "belgian singer-songwriter",
    "frankfurt indie",
    "german alternative rock",
    "japanese indie rock",
    "kyushu indie",
    "rap espanol",
    "kalmar indie",
    "k-pop girl group",
    "oakland indie",
    "polish emo",
    "hyperpop italiano",
    "deep hardcore punk",
    "eurobeat",
    "azontobeats",
    "coupe-decale",
    "zouglou",
    "canadian pop punk",
    "miami metal",
    "cumbia chilena",
    "classic russian rock",
    "russian heavy metal",
    "rap dominicano",
    "australian alternative pop",
    "deep german indie",
    "chillhop",
    "german shoegaze",
    "finnish electro",
    "deep indie rock",
    "russian oi",
    "st petersburg fl indie",
    "punjabi pop",
    "belgian indie rock",
    "action rock",
    "japanese dance pop",
    "japanese shoegaze",
    "swiss techno",
    "indie electropop",
    "cosmic black metal",
    "french indietronica",
    "german house",
    "neoperreo",
    "indie valenciana",
    "gymcore",
    "dark synthpop",
    "detroit hardcore",
    "straight edge",
    "frauenrap",
    "kosovan pop",
    "new hampshire indie",
    "galician indie",
    "talentkonkurrence",
    "adelaide punk",
    "future bounce",
    "rap feminino nacional",
    "pop r&b",
    "bulgarian r&b",
    "indian lo-fi",
    "shimmer psych",
    "london indie",
    "kolsche karneval",
    "scottish hip hop",
    "sinogaze",
    "panpipe",
    "classical mezzo-soprano",
    "deep idm",
    "modular synth",
    "fussball",
    "arizona punk",
    "canadian punk",
    "romanian indie",
    "belgian electronic",
    "swedish pop rap",
    "southern metal",
    "north alabama indie",
    "old school atlanta hip hop",
    "west coast reggae",
    "indie tucumano",
    "minimal synth",
    "oc indie",
    "new york shoegaze",
    "nederreggae",
    "21st century classical",
    "contemporary classical",
    "early modern classical",
    "spanish invasion",
    "german alternative rap",
    "deep dance pop",
    "progressive electro house",
    "latin shoegaze",
    "leon gto indie",
    "shoegaze mexicano",
    "indiana indie",
    "spanish post-punk",
    "sunset lounge",
    "instrumental worship",
    "lafayette indie",
    "andean flute",
    "nu-cumbia",
    "nueva ola chilena",
    "chennai indie",
    "scam rap",
    "trap queen",
    "japanese electropop",
    "italian pop rock",
    "vancouver metal",
    "slovenian hip hop",
    "rotterdam indie",
    "scottish shoegaze",
    "emo mexicano",
    "sinaloa indie",
    "moroccan pop",
    "rap maroc",
    "glitch ambient",
    "latin talent show",
    "rosary",
    "arab pop",
    "vegas indie",
    "south african house",
    "rap conscient",
    "latin tek",
    "focus beats",
    "boogie",
    "pakistani hip hop",
    "spanish post-rock",
    "deep latin christian",
    "acid house",
    "chicago house",
    "classic house",
    "dirty texas rap",
    "houston rap",
    "k-pop boy group",
    "black sludge",
    "cumbia uruguaya",
    "cypriot metal",
    "orebro indie",
    "new tejano",
    "deep punk rock",
    "charva",
    "danish hip hop",
    "belgian edm",
    "hypnagogic pop",
    "indie boliviano",
    "czech electronic",
    "urbano espanol",
    "rock nica",
    "deep progressive trance",
    "swedish metalcore",
    "indie nica",
    "new isolationism",
    "yogyakarta indie",
    "ambeat",
    "political hip hop",
    "traditional funk",
    "piratenmuziek",
    "dutch hip hop",
    "texas pop punk",
    "ugandan pop",
    "neo-manele",
    "classical clarinet",
    "british jazz",
    "czech contemporary classical",
    "nashville hip hop",
    "background jazz",
    "deep tropical house",
    "korean punk",
    "jazz organ",
    "modern swing",
    "vintage swing",
    "jazz brass",
    "jazz guitar trio",
    "swedish jazz orkester",
    "japanese jazz",
    "hot jazz",
    "highlife",
    "palm wine guitar",
    "drill espanol",
    "danish modern jazz",
    "broken beat",
    "schrammelmusik",
    "future rock",
    "bossa nova jazz",
    "german jazz",
    "classical trumpet",
    "drama",
    "hard alternative",
    "irish modern jazz",
    "czech jazz",
    "belgian jazz",
    "greek jazz",
    "nordnorsk musikk",
    "ambient dub techno",
    "dub techno",
    "blues band",
    "russian jazz",
    "israeli jazz",
    "indonesian singer-songwriter",
    "arabic jazz",
    "classic female blues",
    "harlem renaissance",
    "spanish jazz",
    "vintage schlager",
    "hard motivation",
    "canadian modern jazz",
    "deep latin jazz",
    "turkish jazz",
    "deep funk",
    "speed garage",
    "zeuhl",
    "turkish modern jazz",
    "cha-cha-cha",
    "jazz cubano",
    "jazz flute",
    "ragtime",
    "swiss contemporary classical",
    "modern funk",
    "avant-garde jazz",
    "african-american classical",
    "south african modern jazz",
    "san diego rap",
    "trance brasileiro",
    "decije pesme",
    "italian jazz",
    "polish experimental",
    "paidika tragoudia",
    "danish contemporary classical",
    "progressive uplifting trance",
    "tech trance",
    "uplifting trance",
    "cape breton indie",
    "cologne electronic",
    "pop ambient",
    "groove room",
    "traditional rockabilly",
    "japanese psychedelic rock",
    "indian techno",
    "vocaloid",
    "vocaloid metal",
    "jazz caraibes",
    "musique guadeloupe",
    "afrobeat fusion",
    "deep smooth jazz",
    "stride",
    "french stoner rock",
    "deep vocal jazz",
    "greek folk",
    "lithuanian jazz",
    "ngoni",
    "classical horn",
    "k-rock",
    "japanese dream pop",
    "uk alternative hip hop",
    "rwandan hip hop",
    "egyptian hip hop",
    "chinese punk",
    "korean electropop",
    "korean pop",
    "joseon pop",
    "trot",
    "new orleans indie",
    "space ambient",
    "funk rock",
    "christian thrash metal"
];

const result = mergeGenres(spotifyGenres, genreMap);
console.log('Merged map:', result.mergedMap);
console.log('Unmatched genres:', result.unmatched);